import type { Pattern } from "@/types/content";

export const arraysHashing: Pattern = {
  slug: "arrays-hashing",
  title: "Arrays & Hashing",
  tagline: "Indexing, sets, and prefix tricks.",
  status: "live",
  icon: "Hash",
  topics: [
    {
      slug: "two-sum",
      title: "Two Sum",
      difficulty: "Easy",
      status: "live",
      description: "Given an array and a target, return indices of the two numbers that add to the target.",
      problem:
        "Given an array of integers `nums` and an integer `target`, return the indices of the two numbers such that they add up to `target`. Each input is guaranteed to have exactly one solution, and you may not use the same element twice. Return the answer in any order. Example: `nums = [2,7,11,15], target = 9` returns `[0,1]`. Edge cases: arrays of length 2, negative numbers, and duplicates where both copies are not allowed at the same index.",
      askedAt: ["Amazon", "Google", "Apple", "Microsoft"],
      code: {
        lang: "python",
        lines: [
          "def two_sum_brute(nums, target):",
          "    n = len(nums)",
          "    for i in range(n):",
          "        for j in range(i + 1, n):",
          "            if nums[i] + nums[j] == target:",
          "                return [i, j]",
          "    return []",
        ],
      },
      annotations: {
        1: "Outer loop picks the first candidate index i.",
        4: "Inner loop pairs i with every j strictly greater than i, guaranteeing each pair is considered once.",
        5: "Stop as soon as the sum matches; the problem guarantees exactly one such pair exists.",
      },
      approaches: [
        {
          id: "brute",
          name: "Brute Force",
          time: "O(n²)",
          space: "O(1)",
          opsEstimate: (n) => n * n,
          defaultInput: { array: [2, 7, 11, 15], target: 9 },
          steps: [
            { id: 0, narration: "Try every pair (i, j).", pointers: { i: 0, j: 1 }, highlight: [0, 1], opCount: 0 },
            { id: 1, narration: "2 + 7 = 9 == target. Found!", pointers: { i: 0, j: 1 }, highlight: [0, 1], opCount: 1, done: true },
          ],
        },
        {
          id: "hash",
          name: "Hash Map",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [2, 7, 11, 15], target: 9 },
          steps: [
            { id: 0, narration: "Initialize empty map.", variables: { map: "{}" }, opCount: 0 },
            { id: 1, narration: "i=0: need 7. Insert 2→0.", variables: { map: "{2→0}" }, pointers: { i: 0 }, highlight: [0], opCount: 1 },
            { id: 2, narration: "i=1: need 2. Hit! 2 + 7 = 9.", variables: { map: "{2→0}" }, pointers: { i: 1 }, highlight: [0, 1], opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "contains-duplicate",
      title: "Contains Duplicate",
      difficulty: "Easy",
      status: "live",
      description: "Return true if any value appears at least twice.",
      problem:
        "Given an integer array `nums`, return `true` if any value appears at least twice, and `false` if every element is distinct. Example: `[1,2,3,1]` returns `true`; `[1,2,3,4]` returns `false`. The values fit in a 32-bit signed integer but the array length can reach 10^5. Edge cases: empty array (answer is `false`), single element (answer is `false`), and inputs like `[0,0]` that contain an adjacent duplicate.",
      askedAt: ["Amazon", "Apple", "Adobe"],
      code: {
        lang: "python",
        lines: [
          "def contains_duplicate(nums):",
          "    n = len(nums)",
          "    for i in range(n):",
          "        for j in range(i + 1, n):",
          "            if nums[i] == nums[j]:",
          "                return True",
          "    return False",
        ],
      },
      annotations: {
        4: "Compare each element against every later element.",
        5: "Return immediately on first duplicate to avoid wasted work.",
      },
      approaches: [
        {
          id: "sort",
          name: "Sort + Adjacent Compare",
          time: "O(n log n)",
          space: "O(1)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { array: [1, 2, 3, 1] },
          steps: [
            { id: 0, narration: "Sort the array.", highlight: [0, 1, 2, 3], variables: { sorted: "[1,1,2,3]" }, opCount: 0 },
            { id: 1, narration: "Compare adjacent pairs. 1 == 1. Duplicate found.", pointers: { i: 0, j: 1 }, highlight: [0, 1], opCount: 1, done: true },
          ],
        },
        {
          id: "hash",
          name: "Hash Set",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 1] },
          steps: [
            { id: 0, narration: "Initialize empty set.", variables: { set: "{}" }, opCount: 0 },
            { id: 1, narration: "i=0: 1 not in set. Insert.", variables: { set: "{1}" }, pointers: { i: 0 }, highlight: [0], opCount: 1 },
            { id: 2, narration: "i=1: 2 not in set. Insert.", variables: { set: "{1,2}" }, pointers: { i: 1 }, highlight: [1], opCount: 2 },
            { id: 3, narration: "i=2: 3 not in set. Insert.", variables: { set: "{1,2,3}" }, pointers: { i: 2 }, highlight: [2], opCount: 3 },
            { id: 4, narration: "i=3: 1 IS in set. Duplicate!", variables: { set: "{1,2,3}" }, pointers: { i: 3 }, highlight: [3], opCount: 4, done: true },
          ],
        },
      ],
    },
    {
      slug: "top-k-frequent",
      title: "Top K Frequent Elements",
      difficulty: "Medium",
      status: "live",
      description: "Return the k most frequent elements.",
      problem:
        "Given an integer array `nums` and an integer `k`, return the `k` most frequent elements. The answer may be returned in any order. Example: `nums = [1,1,1,2,2,3], k = 2` returns `[1,2]`. The runtime must be better than O(n log n) for full credit. Edge cases: `k == len(nums)` (return everything), all elements identical, and ties — when ties occur, any of the tied values is acceptable.",
      askedAt: ["Amazon", "Meta", "Google", "Yelp"],
      code: {
        lang: "python",
        lines: [
          "def top_k_frequent(nums, k):",
          "    freq = {}",
          "    for x in nums:",
          "        freq[x] = freq.get(x, 0) + 1",
          "    pairs = list(freq.items())",
          "    pairs.sort(key=lambda p: -p[1])",
          "    return [pairs[i][0] for i in range(k)]",
        ],
      },
      annotations: {
        3: "Build a frequency map in one pass.",
        5: "Sort the items by descending count; the heaviest items come first.",
        6: "Take the keys of the first k pairs in the sorted list.",
      },
      approaches: [
        {
          id: "sort",
          name: "Sort by Frequency",
          time: "O(n log n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 1, 1, 2, 2, 3], k: 2 },
          steps: [
            { id: 0, narration: "Count frequencies: {1:3, 2:2, 3:1}.", variables: { freq: "{1:3, 2:2, 3:1}" }, opCount: 0 },
            { id: 1, narration: "Sort entries by count desc.", variables: { sorted: "[(1,3),(2,2),(3,1)]" }, opCount: 1 },
            { id: 2, narration: "Take the first k=2: [1, 2].", variables: { answer: "[1, 2]" }, highlight: [0, 1], opCount: 2, done: true },
          ],
        },
        {
          id: "bucket",
          name: "Bucket Sort",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 1, 1, 2, 2, 3], k: 2 },
          steps: [
            { id: 0, narration: "Count frequencies: {1:3, 2:2, 3:1}.", variables: { freq: "{1:3, 2:2, 3:1}" }, opCount: 0 },
            { id: 1, narration: "Bucket by frequency: bucket[3]=[1], bucket[2]=[2], bucket[1]=[3].", variables: { buckets: "[ ] [ ] [2] [1] [ ]" }, opCount: 1 },
            { id: 2, narration: "Walk buckets from high → low. Take 1, then 2.", variables: { answer: "[1, 2]" }, highlight: [0, 1], opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "valid-anagram",
      title: "Valid Anagram",
      difficulty: "Easy",
      status: "live",
      description: "Decide whether two strings are anagrams of each other.",
      problem:
        "Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise. An anagram uses exactly the same characters with exactly the same multiplicities, in any order. Example: `s='anagram', t='nagaram'` returns `true`; `s='rat', t='car'` returns `false`. The strings contain only lowercase English letters and can each be up to 5·10^4 characters long. Edge cases: strings of different lengths are immediately not anagrams; empty strings anagram to each other.",
      askedAt: ["Amazon", "Meta", "Microsoft", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def is_anagram_brute(s, t):",
          "    if len(s) != len(t): return False",
          "    s_sorted = sorted(s)",
          "    t_sorted = sorted(t)",
          "    for i in range(len(s_sorted)):",
          "        if s_sorted[i] != t_sorted[i]:",
          "            return False",
          "    return True",
        ],
      },
      annotations: {
        2: "Different lengths cannot be anagrams — short circuit.",
        3: "Sort both strings so identical characters line up at the same index.",
        7: "All matched positions means one is a permutation of the other.",
      },
      approaches: [
        {
          id: "sort",
          name: "Sort & Compare",
          time: "O(n log n)",
          space: "O(1) or O(n) depending on sort",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { s: "anagram", t: "nagaram" },
          steps: [
            { id: 0, narration: "Sort s → 'aaagmnr'. Sort t → 'aaagmnr'. Equal?", variables: { s: "'anagram'", t: "'nagaram'" }, opCount: 0 },
            { id: 1, narration: "s_sorted='aaagmnr', t_sorted='aaagmnr'. Compare index by index.", variables: { s: "'aaagmnr'", t: "'aaagmnr'" }, opCount: 1 },
            { id: 2, narration: "All 7 chars match. Return true.", variables: { answer: "true" }, opCount: 2, done: true },
          ],
        },
        {
          id: "hash-count",
          name: "Hash Count",
          time: "O(n)",
          space: "O(1) (26 keys)",
          opsEstimate: (n) => n,
          defaultInput: { s: "anagram", t: "nagaram" },
          steps: [
            { id: 0, narration: "Count chars of s: {a:3, n:1, g:1, r:1, m:1}.", variables: { count: "{a:3, n:1, g:1, r:1, m:1}" }, opCount: 0 },
            { id: 1, narration: "Walk t. Decrement counts. Final count all zero → anagram.", variables: { count: "{a:0,n:0,g:0,r:0,m:0}" }, opCount: 1, done: true },
          ],
        },
      ],
    },
    {
      slug: "group-anagrams",
      title: "Group Anagrams",
      difficulty: "Medium",
      status: "live",
      description: "Group strings that are anagrams of each other.",
      problem:
        "Given an array of strings `strs`, group the anagrams together. The answer may be returned in any order, and groups themselves can be in any order. Example: `strs=['eat','tea','tan','ate','nat','bat']` returns `[['bat'],['nat','tan'],['ate','eat','tea']]`. Strings may be up to length 100, and the array can hold up to 10^4 strings. Edge cases: single-element input, all strings already anagrams of each other, and strings with a mix of repeated characters.",
      askedAt: ["Amazon", "Meta", "Uber", "Google"],
      code: {
        lang: "python",
        lines: [
          "def group_anagrams_brute(strs):",
          "    groups = []",
          "    for s in strs:",
          "        placed = False",
          "        for g in groups:",
          "            if sorted(g[0]) == sorted(s):",
          "                g.append(s)",
          "                placed = True",
          "                break",
          "        if not placed:",
          "            groups.append([s])",
          "    return groups",
        ],
      },
      annotations: {
        4: "Try every existing group; pick the one whose first element shares the same sorted signature.",
        5: "Sorted representations identify anagrams in O(L log L) per comparison.",
        9: "If no group matches, this string starts a new group by itself.",
      },
      approaches: [
        {
          id: "sort-key",
          name: "Sorted Signature (Hash)",
          time: "O(n · k log k)",
          space: "O(n · k)",
          opsEstimate: (n) => n,
          defaultInput: { strs: ["eat", "tea", "tan", "ate", "nat", "bat"] },
          steps: [
            { id: 0, narration: "Init map {} keyed by sorted signature.", variables: { map: "{}" }, opCount: 0 },
            { id: 1, narration: "'eat' → 'aet'. map = {'aet':['eat']}.", variables: { map: "{aet:[eat]}" }, highlight: [0], opCount: 1 },
            { id: 2, narration: "'tea' → 'aet'. Group exists, append.", variables: { map: "{aet:[eat,tea]}" }, highlight: [1], opCount: 2 },
            { id: 3, narration: "'tan' → 'ant'. New group.", variables: { map: "{aet:[eat,tea], ant:[tan]}" }, highlight: [2], opCount: 3 },
            { id: 4, narration: "'ate' → 'aet'. Append.", variables: { map: "{aet:[eat,tea,ate], ant:[tan]}" }, highlight: [3], opCount: 4 },
            { id: 5, narration: "'nat' → 'ant'. Append.", variables: { map: "{aet:[eat,tea,ate], ant:[tan,nat]}" }, highlight: [4], opCount: 5 },
            { id: 6, narration: "'bat' → 'abt'. New group.", variables: { map: "{aet:[eat,tea,ate], ant:[tan,nat], abt:[bat]}" }, highlight: [5], opCount: 6, done: true },
          ],
        },
        {
          id: "count-key",
          name: "Char-Count Signature",
          time: "O(n · k)",
          space: "O(n · k)",
          opsEstimate: (n) => n,
          defaultInput: { strs: ["eat", "tea", "tan", "ate", "nat", "bat"] },
          steps: [
            { id: 0, narration: "Build a 26-count tuple per string: counts of 'a','b',…,'z'.", variables: { map: "{}" }, opCount: 0 },
            { id: 1, narration: "'eat' → counts (1,0,…,1,0,0,1,…). Use as key.", variables: { map: "{(1,0,…,1): [eat]}" }, highlight: [0], opCount: 1 },
            { id: 2, narration: "'tea' → same count. Append.", variables: { map: "{(1,0,…,1): [eat,tea]}" }, highlight: [1], opCount: 2 },
            { id: 3, narration: "'ate' → same count. Append.", variables: { map: "{(1,0,…,1): [eat,tea,ate]}" }, highlight: [3], opCount: 3 },
            { id: 4, narration: "'tan' different counts → new bucket.", variables: { map: "{(1,0,…,1): […], (1,0,…,1,t): [tan]}" }, highlight: [2], opCount: 4 },
            { id: 5, narration: "'nat' matches second bucket.", variables: { map: "{…, (1,0,…,1,t): [tan,nat]}" }, highlight: [4], opCount: 5 },
            { id: 6, narration: "'bat' has different counts → third bucket.", variables: { map: "{…: [[bat]]}" }, highlight: [5], opCount: 6, done: true },
          ],
        },
      ],
    },
    {
      slug: "product-except-self",
      title: "Product of Array Except Self",
      difficulty: "Medium",
      status: "live",
      description: "Return an array where each element is the product of all other elements.",
      problem:
        "Given an integer array `nums`, return an array `answer` such that `answer[i]` equals the product of all the elements of `nums` except `nums[i]`. The solution must run in O(n) time and must not use the division operator. Example: `nums=[1,2,3,4]` returns `[24,12,8,6]`. Edge cases: arrays containing zero (one zero flips the product for all but that index), arrays with multiple zeros (every product is 0), and length-2 arrays.",
      askedAt: ["Amazon", "Meta", "Microsoft", "Apple"],
      code: {
        lang: "python",
        lines: [
          "def product_except_self_brute(nums):",
          "    n = len(nums)",
          "    ans = [1] * n",
          "    for i in range(n):",
          "        for j in range(n):",
          "            if i != j:",
          "                ans[i] *= nums[j]",
          "    return ans",
        ],
      },
      annotations: {
        4: "For each output slot, scan all input slots except the current one.",
        6: "Skip the self-index, then multiply the running product.",
      },
      approaches: [
        {
          id: "prefix-suffix",
          name: "Prefix × Suffix",
          time: "O(n)",
          space: "O(1) extra",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4] },
          steps: [
            { id: 0, narration: "ans = [1,1,1,1]. Compute prefix products left→right.", variables: { ans: "[1,1,1,1]" }, opCount: 0 },
            { id: 1, narration: "ans[0]=1. Pass: ans[1]=ans[0]*2=2. ans[2]=2*3=6. ans[3]=6*4=24.", variables: { ans: "[1,2,6,24]" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "Now multiply by suffix on the right. suffix=1. ans[3]*=1 → 24.", variables: { ans: "[1,2,6,24]", suffix: 1 }, pointers: { i: 3 }, opCount: 2 },
            { id: 3, narration: "suffix=4. ans[2]*=4 → 24.", variables: { ans: "[1,2,24,24]", suffix: 4 }, pointers: { i: 2 }, opCount: 3 },
            { id: 4, narration: "suffix=4*3=12. ans[1]*=12 → 24.", variables: { ans: "[1,24,24,24]", suffix: 12 }, pointers: { i: 1 }, opCount: 4 },
            { id: 5, narration: "suffix=12*2=24. ans[0]*=24 → 24.", variables: { ans: "[24,24,24,24]", suffix: 24 }, pointers: { i: 0 }, opCount: 5, done: true },
          ],
        },
        {
          id: "two-arrays",
          name: "Two Arrays",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4] },
          steps: [
            { id: 0, narration: "Compute prefix[] and suffix[] separately.", variables: { pref: "[1]", suff: "[24,24,12,4,1]" }, opCount: 0 },
            { id: 1, narration: "prefix = [1,1,2,6]; suffix = [24,12,4,1].", variables: { pref: "[1,1,2,6]", suff: "[24,12,4,1]" }, opCount: 1 },
            { id: 2, narration: "ans[i] = prefix[i] · suffix[i+1].", variables: { ans: "[1·24, 1·12, 2·4, 6·1]" }, opCount: 2 },
            { id: 3, narration: "Final: [24, 12, 8, 6].", variables: { ans: "[24,12,8,6]" }, opCount: 3, done: true },
          ],
        },
      ],
    },
    {
      slug: "longest-consecutive-sequence",
      title: "Longest Consecutive Sequence",
      difficulty: "Medium",
      status: "live",
      description: "Find the length of the longest run of consecutive integers.",
      problem:
        "Given an unsorted array of integers `nums`, return the length of the longest sequence of consecutive elements. The sequence must be contiguous integers but they can appear in any order in the array. The algorithm must run in O(n) time. Example: `[100,4,200,1,3,2]` → longest is `[1,2,3,4]` with length 4. Edge cases: empty array (answer 0), single element (answer 1), and inputs with duplicates (duplicates do not extend the run).",
      askedAt: ["Amazon", "Google", "Meta", "Adobe"],
      code: {
        lang: "python",
        lines: [
          "def longest_consecutive_brute(nums):",
          "    nums_set = set(nums)",
          "    best = 0",
          "    for x in nums_set:",
          "        length = 0",
          "        y = x",
          "        while y in nums_set:",
          "            length += 1",
          "            y += 1",
          "        if length > best: best = length",
          "    return best",
        ],
      },
      annotations: {
        6: "Walk forward from x as long as the next integer is in the set.",
        7: "Counts how many consecutive integers we can chain together starting at x.",
        9: "Track the longest run seen over all starting points.",
      },
      approaches: [
        {
          id: "sort",
          name: "Sort + Linear Scan",
          time: "O(n log n)",
          space: "O(1)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { array: [100, 4, 200, 1, 3, 2] },
          steps: [
            { id: 0, narration: "Sort: [1,2,3,4,100,200].", variables: { sorted: "[1,2,3,4,100,200]" }, opCount: 0 },
            { id: 1, narration: "1→2 (consecutive). 2→3 (consecutive). 3→4 (consecutive).", variables: { run: 4 }, highlight: [0,1,2,3], opCount: 1 },
            { id: 2, narration: "4→100 (gap). Start new run. 100→200 (gap). Run=2.", variables: { run: 2 }, highlight: [4, 5], opCount: 2 },
            { id: 3, narration: "Best run = 4. Answer = 4.", variables: { answer: 4 }, opCount: 3, done: true },
          ],
        },
        {
          id: "set-seeds",
          name: "Set (seeds only)",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [100, 4, 200, 1, 3, 2] },
          steps: [
            { id: 0, narration: "Set={1,2,3,4,100,200}. A seed has no predecessor in the set.", variables: { set: "{1,2,3,4,100,200}" }, opCount: 0 },
            { id: 1, narration: "1 is a seed (no 0). Walk 1→2→3→4. length=4. best=4.", variables: { set: "{1,2,3,4,100,200}", length: 4 }, highlight: [3], opCount: 1 },
            { id: 2, narration: "2,3,4 are NOT seeds — skip them (prev exists).", variables: { set: "..." }, opCount: 2 },
            { id: 3, narration: "100 is a seed. Walk 100 → 200. length=2.", variables: { length: 2 }, highlight: [4], opCount: 3 },
            { id: 4, narration: "200 is not a seed (199 absent).", variables: { set: "..." }, opCount: 4 },
            { id: 5, narration: "Best = 4. Answer = 4.", variables: { answer: 4 }, opCount: 5, done: true },
          ],
        },
      ],
    },
    {
      slug: "encode-decode-strings",
      title: "Encode and Decode Strings",
      difficulty: "Medium",
      status: "live",
      description: "Design an algorithm to encode a list of strings to a single string, then decode it back.",
      problem:
        "Design an algorithm to encode a list of strings into a single string, and decode that string back into the original list. The encoded string should be decodable without losing any data. Strings can contain any UTF-8 characters (including separators). Example: `['lint','code','love','you']` encodes to something decodable back to the original list. Edge cases: empty strings inside the list, very long strings (10^5 chars), and a list with thousands of short strings.",
      askedAt: ["Amazon", "Google", "Meta"],
      code: {
        lang: "python",
        lines: [
          "def encode_brute(strs):",
          "    delim = chr(0)",
          "    return delim.join(s.replace(delim, ' ') for s in strs)",
          "",
          "def decode_brute(s):",
          "    delim = chr(0)",
          "    return [piece.replace(' ', delim) for piece in s.split(delim)]",
        ],
      },
      annotations: {
        2: "Use a non-printable delimiter so it cannot collide with text inside strings.",
        4: "Replace any accidental occurrences of the delimiter inside strings before joining.",
        7: "Split on the delimiter, then restore the escaped characters inside each piece.",
      },
      approaches: [
        {
          id: "length-prefix",
          name: "Length-Prefix Encoding",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { strs: ["lint", "code", "love", "you"] },
          steps: [
            { id: 0, narration: "Prepend each string with its length and '#'. Works for any characters.", variables: { out: "[]" }, opCount: 0 },
            { id: 1, narration: "Encode 'lint' → '4#lint'. out = '4#lint'.", variables: { out: "'4#lint'" }, highlight: [0], opCount: 1 },
            { id: 2, narration: "Append '4#code'.", variables: { out: "'4#lint4#code'" }, highlight: [1], opCount: 2 },
            { id: 3, narration: "Append '4#love' and '3#you'.", variables: { out: "'4#lint4#code4#love3#you'" }, highlight: [2, 3], opCount: 3, done: true },
          ],
        },
        {
          id: "chunked",
          name: "Chunked Transfer",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { strs: ["lint", "code", "love", "you"] },
          steps: [
            { id: 0, narration: "Take each string in fixed-size chunks of k=3 (pad last with # if short).", variables: { chunks: "[]" }, opCount: 0 },
            { id: 1, narration: "'lint' → ['lin','t#'] (lengths 3, 2).", variables: { chunks: "[lin, t#]" }, highlight: [0], opCount: 1 },
            { id: 2, narration: "'code' → ['cod','e#']; 'love' → ['lov','e#']; 'you' → ['you'].", variables: { chunks: "[lin, t#, cod, e#, lov, e#, you]" }, opCount: 2, done: true },
          ],
        },
      ],
    },
  ],
};
