import type { Pattern } from "@/types/content";

export const backtracking: Pattern = {
  slug: "backtracking",
  title: "Backtracking",
  tagline: "Choose, explore, unchoose — exhaustively.",
  status: "live",
  icon: "CornerDownLeft",
  topics: [
    {
      slug: "subsets",
      title: "Subsets",
      difficulty: "Medium",
      status: "live",
      description: "Generate all subsets of a set of distinct integers.",
      problem:
        "Given an integer array `nums` of distinct elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets, and subsets may be returned in any order. Example: `nums=[1,2,3]` → `[[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]`. Edge cases: empty input (only the empty set), single element (two subsets), and arrays up to length 10 where the output has 2^n entries.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def subsets_brute(nums):",
          "    from itertools import chain, combinations",
          "    return list(chain.from_iterable(",
          "        combinations(nums, r) for r in range(len(nums) + 1)))",
        ],
      },
      annotations: {
        1: "Brute: enumerate all combinations of length 0 to n using itertools.combinations.",
      },
      approaches: [
        {
          id: "iterative",
          name: "Iterative",
          time: "O(n * 2^n)",
          space: "O(2^n)",
          opsEstimate: (n) => n * Math.pow(2, Math.min(n, 16)),
          defaultInput: { nums: [1, 2, 3] },
          steps: [
            {
              id: 0,
              narration: "Start with res = [[]] (only the empty subset).",
              variables: { res: "[[]]", curr: "[]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Process 1: for every subset in res, add 1 to a copy.",
              variables: { res: "[[],[1]]", curr: "[1]" },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Process 2: copy each subset in res and append 2.",
              variables: { res: "[[],[1],[2],[1,2]]", curr: "[2]" },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Process 3: copy each subset in res and append 3.",
              variables: { res: "[[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]]", curr: "[3]" },
              highlight: [2],
              opCount: 3,
              done: true,
            },
          ],
        },
        {
          id: "backtracking",
          name: "Backtracking (choose / explore / unchoose)",
          time: "O(n * 2^n)",
          space: "O(n)",
          opsEstimate: (n) => n * Math.pow(2, Math.min(n, 16)),
          defaultInput: { nums: [1, 2, 3] },
          steps: [
            {
              id: 0,
              narration: "Start at index 0 with empty path.",
              variables: { path: "[]", res: "[]" },
              pointers: { i: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "CHOOSE 1 → path=[1]. Record [1]. EXPLORE deeper.",
              variables: { path: "[1]", res: "[[],[1]]" },
              pointers: { i: 1 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "CHOOSE 2 → path=[1,2]. Record [1,2].",
              variables: { path: "[1,2]", res: "[[],[1],[1,2]]" },
              pointers: { i: 2 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "At i=2, no more to choose. UNCHOOSE 2 → path=[1]. Try i=2's 3.",
              variables: { path: "[1,3]", res: "[[],[1],[1,2],[1,3]]" },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Backtrack to root. UNCHOOSE 1 → path=[]. CHOOSE 2 → [2].",
              variables: { path: "[2]", res: "[[],[1],[1,2],[1,3],[2]]" },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 4,
            },
            {
              id: 5,
              narration: "From [2], CHOOSE 3 → [2,3]. Record.",
              variables: { path: "[2,3]", res: "[[],[1],[1,2],[1,3],[2],[2,3]]" },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 5,
            },
            {
              id: 6,
              narration: "Backtrack to root. CHOOSE 3 → [3]. Record.",
              variables: { path: "[3]", res: "[[],[1],[1,2],[1,3],[2],[2,3],[3]]" },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 6,
            },
            {
              id: 7,
              narration: "All branches explored. 2^3 = 8 subsets.",
              variables: { res: "[[],[1],[1,2],[1,3],[2],[2,3],[3],[1,2,3]]" },
              opCount: 7,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "permutations",
      title: "Permutations",
      difficulty: "Medium",
      status: "live",
      description: "Generate all permutations of a set of distinct integers.",
      problem:
        "Given an array `nums` of distinct integers, return all possible permutations. The answer can be in any order. Example: `[1,2,3]` → `[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]`. Edge cases: empty array (single empty permutation), single element (one permutation), and inputs up to length 8 (where n! is still tractable).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "from itertools import permutations",
          "perms_brute = list(permutations(nums))",
        ],
      },
      annotations: {
        1: "Brute: use itertools.permutations — clean but builds them all up front.",
      },
      approaches: [
        {
          id: "used-set",
          name: "Backtracking with used[]",
          time: "O(n * n!)",
          space: "O(n)",
          opsEstimate: (n) => n * 24,
          defaultInput: { nums: [1, 2, 3] },
          steps: [
            {
              id: 0,
              narration: "path=[], used=[F,F,F]. Start at depth 0.",
              variables: { path: "[]", used: "[F,F,F]", res: "[]" },
              pointers: { depth: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Pick i=0 (val=1): used[0]=T. path=[1].",
              variables: { path: "[1]", used: "[T,F,F]", res: "[]" },
              pointers: { depth: 1 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Pick i=1 (val=2): used[1]=T. path=[1,2].",
              variables: { path: "[1,2]", used: "[T,T,F]", res: "[]" },
              pointers: { depth: 2 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Pick i=2 (val=3): used[2]=T. path=[1,2,3] → record.",
              variables: { path: "[1,2,3]", used: "[T,T,T]", res: "[[1,2,3]]" },
              pointers: { depth: 3 },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Unchoose i=2: used[2]=F. No more options. Unchoose i=1, try i=2.",
              variables: { path: "[1,3]", used: "[T,F,T]", res: "[[1,2,3]]" },
              pointers: { depth: 2 },
              highlight: [2],
              opCount: 4,
            },
            {
              id: 5,
              narration: "path=[1,3] → record. Unchoose all the way.",
              variables: { path: "[]", used: "[F,F,F]", res: "[[1,2,3],[1,3,2]]" },
              pointers: { depth: 0 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "Pick i=1 (val=2). Continue → produces [2,1,3] and [2,3,1].",
              variables: { res: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1]]" },
              opCount: 6,
            },
            {
              id: 7,
              narration: "Pick i=2 (val=3). Continue → produces [3,1,2] and [3,2,1]. Total 6.",
              variables: { res: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]" },
              opCount: 7,
              done: true,
            },
          ],
        },
        {
          id: "swap-in-place",
          name: "Backtracking with swap-in-place",
          time: "O(n * n!)",
          space: "O(n)",
          opsEstimate: (n) => n * 24,
          defaultInput: { nums: [1, 2, 3] },
          steps: [
            {
              id: 0,
              narration: "Fix index 0. Swap candidates with index 0 to pick the first element.",
              variables: { arr: "[1,2,3]", res: "[]" },
              pointers: { fix: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Pick 1: fix index 0 (1 stays). Recurse on suffix [2,3].",
              variables: { arr: "[1,2,3]", res: "[]" },
              pointers: { fix: 0 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Swap arr[0]↔arr[1]: fix index 1 with 2. Recurse on [3].",
              variables: { arr: "[1,2,3]", res: "[]" },
              pointers: { fix: 1 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Single element [3] → record [1,2,3]. Backtrack (swap back).",
              variables: { arr: "[1,2,3]", res: "[[1,2,3]]" },
              pointers: { fix: 2 },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Swap arr[1]↔arr[2]: fix index 1 with 3. Recurse on [2].",
              variables: { arr: "[1,3,2]", res: "[[1,2,3]]" },
              pointers: { fix: 1 },
              highlight: [2],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Single element [2] → record [1,3,2]. Swap back to [1,2,3].",
              variables: { arr: "[1,2,3]", res: "[[1,2,3],[1,3,2]]" },
              pointers: { fix: 2 },
              highlight: [1],
              opCount: 5,
            },
            {
              id: 6,
              narration: "Back to fix=0. Swap arr[0]↔arr[1]: now fix=0 holds 2.",
              variables: { arr: "[2,1,3]", res: "[[1,2,3],[1,3,2]]" },
              pointers: { fix: 0 },
              highlight: [0],
              opCount: 6,
            },
            {
              id: 7,
              narration: "Recurse on [1,3]. Produces [2,1,3] and [2,3,1]. Total 6.",
              variables: { arr: "[3,2,1]", res: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]" },
              pointers: { fix: 0 },
              highlight: [0],
              opCount: 7,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "combination-sum",
      title: "Combination Sum",
      difficulty: "Medium",
      status: "live",
      description: "Find all unique combinations of candidates that sum to target. Each candidate may be reused.",
      problem:
        "Given an array of distinct integers `candidates` and a target integer `target`, return a list of all unique combinations of `candidates` where the chosen numbers sum to `target`. The same number may be chosen from `candidates` an unlimited number of times. Combinations must be non-descending and unique. Example: `candidates=[2,3,6,7], target=7` → `[[2,2,3],[7]]`. Edge cases: target=0 (return []), candidates with single element, no valid combinations.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def combination_sum_brute(candidates, target):",
          "    res = set()",
          "    n = len(candidates)",
          "    for mask in range(1 << (n * 10)):",
          "        path = []",
          "        for i in range(n):",
          "            count = (mask >> (i * 2)) & 0x3",
          "            path.extend([candidates[i]] * count)",
          "        if sum(path) == target:",
          "            res.add(tuple(sorted(path)))",
          "    return [list(t) for t in res]",
        ],
      },
      annotations: {
        3: "Brute: 2 bits per candidate for unlimited counts — exponential in n.",
      },
      approaches: [
        {
          id: "backtracking",
          name: "Backtracking",
          time: "O(n^(t/min))",
          space: "O(t/min)",
          opsEstimate: (n) => Math.pow(n, 4),
          defaultInput: { candidates: [2, 3, 6, 7], target: 7 },
          steps: [
            {
              id: 0,
              narration: "path=[], start=0. Try each candidate from index 0.",
              variables: { path: "[]", res: "[]" },
              pointers: { start: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "CHOOSE 2 → path=[2]. target becomes 5.",
              variables: { path: "[2]", target: 5, res: "[]" },
              pointers: { start: 0 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Re-use 2 → path=[2,2]. target becomes 3.",
              variables: { path: "[2,2]", target: 3, res: "[]" },
              pointers: { start: 0 },
              highlight: [0],
              opCount: 2,
            },
            {
              id: 3,
 narration: "Re-use 2 → path=[2,2,2]. target becomes 1.",
              variables: { path: "[2,2,2]", target: 1, res: "[]" },
              pointers: { start: 0 },
              highlight: [0],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Re-use 2 → path=[2,2,2,2]. target = -1 < 0. Prune.",
              variables: { path: "[2,2,2,2]", target: -1, res: "[]" },
              pointers: { start: 0 },
              highlight: [0],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Backtrack. From path=[2,2] try 3 → path=[2,2,3]. target=1, prune.",
              variables: { path: "[2,2,3]", target: 1, res: "[]" },
              pointers: { start: 1 },
              highlight: [1],
              opCount: 5,
            },
            {
              id: 6,
              narration: "Backtrack. Try 6 → [2,2,6] sum=10 > 7, prune. Backtrack to [2].",
              variables: { path: "[2]", target: 5, res: "[]" },
              pointers: { start: 0 },
              highlight: [0],
              opCount: 6,
            },
            {
              id: 7,
              narration: "Skip 3, try 6 → [2,6] sum=8 > 7, prune. Try 7 → [2,7] sum=9, prune.",
              variables: { path: "[]", target: 7, res: "[]" },
              pointers: { start: 1 },
              opCount: 7,
            },
            {
              id: 8,
              narration: "Backtrack to root. Skip 3 (no path reaches 7). Try 6 → [6] need 1, prune. Try 7 → [7] sum=7. Record.",
              variables: { path: "[]", res: "[[7]]" },
              pointers: { start: 3 },
              highlight: [3],
              opCount: 8,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "word-search",
      title: "Word Search",
      difficulty: "Medium",
      status: "live",
      description: "Find a word in a board of letters, using adjacent cells.",
      problem:
        "Given an m x n grid of characters `board` and a string `word`, return `true` if `word` exists in the grid. The word can be constructed from letters of sequentially adjacent cells (horizontally or vertically). The same cell may not be used more than once. Example: `board=[[A,B,C,E],[S,F,C,S],[A,D,E,E]], word='ABCCED'` → true. Edge cases: empty word (false), single-character word (true if letter is in grid), and board with single row/column.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def exist_brute(board, word):",
          "    from itertools import product",
          "    rows, cols = len(board), len(board[0])",
          "    def in_bounds(r, c): return 0 <= r < rows and 0 <= c < cols",
          "    for sr, sc in product(range(rows), range(cols)):",
          "        if board[sr][sc] != word[0]: continue",
          "        visited = set()",
          "        def dfs(r, c, idx):",
          "            if idx == len(word): return True",
          "            if not in_bounds(r, c) or (r, c) in visited: return False",
          "            if board[r][c] != word[idx]: return False",
          "            visited.add((r, c))",
          "            for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):",
          "                if dfs(r+dr, c+dc, idx+1): return True",
          "            visited.discard((r, c))",
          "            return False",
          "        if dfs(sr, sc, 0): return True",
          "    return False",
        ],
      },
      annotations: {
        4: "Brute DFS with backtracking — no optimization over search order.",
      },
      approaches: [
        {
          id: "backtrack-board",
          name: "Backtracking DFS",
          time: "O(m·n·4^L)",
          space: "O(L)",
          opsEstimate: (n) => n,
          defaultInput: { board: [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word: "ABCCED" },
          steps: [
            { id: 0, narration: "Try every starting cell. DFS to spell the word.", variables: { board: "A B C E | S F C S | A D E E" }, opCount: 0 },
            { id: 1, narration: "Start at (0,0)='A'. Match w[0]. Continue to (0,1)='B'.", pointers: { r: 0, c: 0 }, highlight: [0, 1], variables: { path: "(0,0)" }, opCount: 1 },
            { id: 2, narration: "(0,1)='B' matches w[1]. Continue to (0,2)='C'.", pointers: { r: 0, c: 1 }, highlight: [0, 1, 2], variables: { path: "(0,0)→(0,1)" }, opCount: 2 },
            { id: 3, narration: "(0,2)='C' matches w[2]. Continue: w[3]='C' neighbors: (0,3)='E', (1,2)='C' ✓.", pointers: { r: 0, c: 2 }, highlight: [0, 1, 2, 7], variables: { path: "(0,0)→(0,1)→(0,2)" }, opCount: 3 },
            { id: 4, narration: "(1,2)='C' matches. w[4]='E' neighbors include (2,2)='E' ✓.", pointers: { r: 1, c: 2 }, highlight: [2, 7, 12], variables: { path: "…→(1,2)" }, opCount: 4 },
            { id: 5, narration: "(2,2)='E' matches. w[5]='D' neighbors: (2,1)='D' ✓.", pointers: { r: 2, c: 2 }, highlight: [7, 12, 13], variables: { path: "…→(2,2)" }, opCount: 5 },
            { id: 6, narration: "(2,1)='D' matches. idx == len(word). Return true!", variables: { answer: "true" }, opCount: 6, done: true },
          ],
        },
        {
          id: "trie-prune",
          name: "Trie + DFS (multi-word)",
          time: "O(m·n·4^L)",
          space: "O(L · words)",
          opsEstimate: (n) => n,
          defaultInput: { board: [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word: "ABCCED" },
          steps: [
            { id: 0, narration: "Same DFS but trie prunes dead prefixes if there were multiple words.", variables: { trie: "{root: {a:...,b:...,c:...}}" }, opCount: 0 },
            { id: 1, narration: "Walk cell-by-cell following trie edges; backtrack on dead end.", variables: { word: "ABCCED" }, opCount: 1, done: true },
          ],
        },
      ],
    },
    {
      slug: "letter-combinations",
      title: "Letter Combinations of a Phone Number",
      difficulty: "Medium",
      status: "live",
      description: "Return all letter combinations a digit string maps to on a phone keypad.",
      problem:
        "Given a string containing digits from 2-9 inclusive, return every possible letter combination that the number could represent based on the telephone keypad mapping (2→abc, 3→def, ..., 9→wxyz). Combinations may be in any order, and the answer is the Cartesian product over the digit sets. Example: `'23'` → `['ad','ae','af','bd','be','bf','cd','ce','cf']`. Edge cases: empty input (return []), single-digit input, and the 7 and 9 mappings (which have 4 letters instead of 3).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def letter_combos_brute(digits):",
          "    if not digits: return []",
          "    from itertools import product",
          "    mapping = {'2':'abc','3':'def','4':'ghi','5':'jkl',",
          "               '6':'mno','7':'pqrs','8':'tuv','9':'wxyz'}",
          "    pools = [mapping[d] for d in digits]",
          "    return [''.join(p) for p in product(*pools)]",
        ],
      },
      annotations: {
        4: "Brute: Cartesian product using itertools.product.",
      },
      approaches: [
        {
          id: "backtracking",
          name: "Backtracking",
          time: "O(4^n · n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { digits: "23" },
          steps: [
            { id: 0, narration: "Choose a letter from each digit's set, recurse, unchoose.", variables: { path: "" }, opCount: 0 },
            { id: 1, narration: "Pick 'a' for digit 2. path='a'.", variables: { path: "'a'", res: "[]" }, pointers: { i: 0 }, highlight: [0], opCount: 1 },
            { id: 2, narration: "Branch on 'd','e','f' for digit 3 → 'ad','ae','af'.", variables: { path: "'a'", res: "['ad','ae','af']" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "Backtrack. Try 'b' for digit 2. Branch on 3 → 'bd','be','bf'.", variables: { path: "'b'", res: "[..., 'bd','be','bf']" }, pointers: { i: 0 }, highlight: [1], opCount: 3 },
            { id: 4, narration: "Try 'c' for digit 2. Branch → 'cd','ce','cf'.", variables: { res: "['ad','ae','af','bd','be','bf','cd','ce','cf']" }, pointers: { i: 0 }, highlight: [2], opCount: 4, done: true },
          ],
        },
        {
          id: "iterative-bfs",
          name: "Iterative (BFS-ish)",
          time: "O(4^n · n)",
          space: "O(4^n · n)",
          opsEstimate: (n) => n,
          defaultInput: { digits: "23" },
          steps: [
            { id: 0, narration: "Start with ['']. For each digit, replace each prefix with prefix+letter.", variables: { res: "['']" }, opCount: 0 },
            { id: 1, narration: "After digit 2 → ['a','b','c'].", variables: { res: "['a','b','c']" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "After digit 3 → ['ad','ae','af','bd','be','bf','cd','ce','cf'].", variables: { res: "['ad','ae','af','bd','be','bf','cd','ce','cf']" }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "generate-parentheses",
      title: "Generate Parentheses",
      difficulty: "Medium",
      status: "live",
      description: "Generate all well-formed combinations of n pairs of parentheses.",
      problem:
        "Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses. Example: n=3 → `['((()))','(()())','(())()','()(())','()()()']`. Order does not matter but it's typically given in a canonical order. Edge cases: n=0 (return ['']), n=1 (return ['()']), and large n where the count is the n-th Catalan number.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def gen_brute(n):",
          "    from itertools import product",
          "    candidates = []",
          "    for seq in product('()', repeat=2*n):",
          "        s = ''.join(seq)",
          "        if is_balanced(s): candidates.append(s)",
          "    return candidates",
        ],
      },
      annotations: {
        1: "Brute: enumerate all 2^(2n) strings and filter for balance.",
      },
      approaches: [
        {
          id: "backtracking",
          name: "Backtracking (close count)",
          time: "O(C_n · n)",
          space: "O(n) call stack",
          opsEstimate: (n) => n,
          defaultInput: { n: 3 },
          steps: [
            { id: 0, narration: "Track open and close counts. Add '(' if open<n. Add ')' if close<open.", variables: { open: 0, close: 0, s: "" }, opCount: 0 },
            { id: 1, narration: "Add '(' → s='('", variables: { open: 1, s: "'('" }, pointers: { step: 1 }, opCount: 1 },
            { id: 2, narration: "Add '(' → s='(('", variables: { open: 2, s: "'(('" }, opCount: 2 },
            { id: 3, narration: "Add '(' → s='((('", variables: { open: 3, s: "'((('" }, opCount: 3 },
            { id: 4, narration: "Add ')' three times → '((()))'. Record.", variables: { close: 3, s: "'((()))'", res: "['((()))']" }, opCount: 4 },
            { id: 5, narration: "Backtrack. Try '(()())' next, then the other combinations. Total 5.", variables: { res: "[...]" }, opCount: 5, done: true },
          ],
        },
        {
          id: "dp-construct",
          name: "DP Construction",
          time: "O(C_n · n)",
          space: "O(n · C_n)",
          opsEstimate: (n) => n,
          defaultInput: { n: 3 },
          steps: [
            { id: 0, narration: "Construct from n-1: wrap each with '()' + outer pair, or split into two halves.", variables: { dp: "[]" }, opCount: 0 },
            { id: 1, narration: "n=1: dp = ['()'].", variables: { dp: "[()]" }, opCount: 1 },
            { id: 2, narration: "n=2: dp = ['()()','(())'].", variables: { dp: "[()(), (())]" }, opCount: 2 },
            { id: 3, narration: "n=3: combine '()'+dp[2] AND '('+dp[k]+')'+dp[n-1-k]. 5 results.", variables: { dp: "[5 strings]" }, opCount: 3, done: true },
          ],
        },
      ],
    },
    {
      slug: "palindrome-partitioning",
      title: "Palindrome Partitioning",
      difficulty: "Medium",
      status: "live",
      description: "Partition a string into substrings that are all palindromes.",
      problem:
        "Given a string `s`, partition `s` such that every substring of the partition is a palindrome. Return all possible palindrome partitionings of `s`. Example: `'aab'` → `[['a','a','b'],['aa','b']]`. Edge cases: empty string (one partition [['']]), single character (one partition), and inputs up to length 16.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def partition_brute(s):",
          "    res = []",
          "    def is_pal(sub): return sub == sub[::-1]",
          "    def dfs(start, path):",
          "        if start == len(s):",
          "            res.append(path[:])",
          "            return",
          "        for end in range(start + 1, len(s) + 1):",
          "            sub = s[start:end]",
          "            if is_pal(sub):",
          "                path.append(sub)",
          "                dfs(end, path)",
          "                path.pop()",
          "    dfs(0, [])",
          "    return res",
        ],
      },
      annotations: {
        7: "Brute backtracking with O(L^3) palindrome checks — same complexity as smart version but no memoized isP table.",
      },
      approaches: [
        {
          id: "backtrack",
          name: "Backtracking + Palindrome Check",
          time: "O(n · 2^n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { s: "aab" },
          steps: [
            { id: 0, narration: "Cut at every prefix that's a palindrome. Recurse from there.", variables: { path: "[]", res: "[]" }, pointers: { start: 0 }, opCount: 0 },
            { id: 1, narration: "Cut 'a' (pal). path=['a']. Recurse at start=1.", variables: { path: "['a']", res: "[]" }, pointers: { start: 1 }, highlight: [0], opCount: 1 },
            { id: 2, narration: "Cut 'a' (pal). path=['a','a']. Recurse at start=2.", variables: { path: "['a','a']" }, pointers: { start: 2 }, highlight: [1], opCount: 2 },
            { id: 3, narration: "Cut 'b' (pal). path=['a','a','b']. At end → record.", variables: { path: "['a','a','b']", res: "[['a','a','b']]" }, pointers: { start: 3 }, highlight: [2], opCount: 3 },
            { id: 4, narration: "Backtrack. At start=1 cut 'ab'? No. Backtrack to start=0.", variables: { path: "['a']" }, pointers: { start: 1 }, opCount: 4 },
            { id: 5, narration: "Cut 'aa' (pal). path=['aa']. Recurse at start=2: 'b' → record.", variables: { path: "['aa','b']", res: "[[...], ['aa','b']]" }, pointers: { start: 2 }, highlight: [0, 1], opCount: 5, done: true },
          ],
        },
        {
          id: "dp-memo",
          name: "DP Precompute + Backtrack",
          time: "O(n²)",
          space: "O(n²)",
          opsEstimate: (n) => n,
          defaultInput: { s: "aab" },
          steps: [
            { id: 0, narration: "Precompute isPal[l][r] via DP so cuts are O(1) to validate.", variables: { isPal: "{}" }, opCount: 0 },
            { id: 1, narration: "isPal filled: a,a; aa; a,a,a; b; ab; aab (subset).", variables: { isPal: "{a:True,aa:True,b:True}" }, opCount: 1 },
            { id: 2, narration: "DFS uses isPal[0:1], isPal[0:2], … to enumerate valid cuts.", variables: { res: "[['a','a','b'],['aa','b']]" }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "n-queens",
      title: "N-Queens",
      difficulty: "Hard",
      status: "live",
      description: "Place n queens on an n×n chessboard with no two attacking each other.",
      problem:
        "The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other. Given an integer `n`, return all distinct solutions, each as a list of strings representing the board ('Q' for queen, '.' for empty). Example: `n=4` → 2 solutions. Edge cases: n=1 (one solution: ['Q']), n=2 (no solution), n=3 (no solution), and n=4 (two solutions).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def solve_n_queens_brute(n):",
          "    from itertools import permutations",
          "    res = []",
          "    for perm in permutations(range(n)):",
          "        ok = True",
          "        for i in range(n):",
          "            for j in range(i + 1, n):",
          "                if abs(i - j) == abs(perm[i] - perm[j]):",
          "                    ok = False; break",
          "            if not ok: break",
          "        if ok: res.append(perm)",
          "    return res",
        ],
      },
      annotations: {
        2: "Brute: try every column permutation (assumes 1 per row) and reject diagonal collisions.",
      },
      approaches: [
        {
          id: "backtrack-sets",
          name: "Backtracking",
          time: "O(n!)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { n: 4 },
          steps: [
            { id: 0, narration: "Track occupied columns and diagonals. Place queen row-by-row.", variables: { cols: "{}", d1: "{}", d2: "{}" }, pointers: { row: 0 }, opCount: 0 },
            { id: 1, narration: "row=0, try col=1. cols={1}, d1={1}, d2={-1}.", variables: { cols: "{1}", d1: "{1}", d2: "{-1}", board: ".Q.." }, highlight: [1], opCount: 1 },
            { id: 2, narration: "row=1: col=3 free. cols={1,3}, d1={1,4}, d2={-1,-2}.", variables: { board: ".Q.. ...Q" }, highlight: [5], opCount: 2 },
            { id: 3, narration: "row=2: col=0 free. d1={1,4,2}, d2={-1,-2,2}? conflict. col=2? free. Place.", variables: { board: ".Q.. ...Q ..Q." }, highlight: [6], opCount: 3 },
            { id: 4, narration: "row=3: only col=2 available. d1={1,4,2,5}, d2={-1,-2,2,1}. Conflict? Check d1: 5 not used. d2: 1 used. Conflict. Backtrack.", variables: { board: "… stuck" }, opCount: 4 },
            { id: 5, narration: "Backtrack row=2. col=4? free. Place. row=3: col=2 free. d1=4+3=7; d2=4-3=1 conflict. Backtrack further...", variables: { board: "...Q" }, opCount: 5 },
            { id: 6, narration: "Solution 1 found: row=[1,3,0,2] → board '.Q..', '...Q', 'Q...', '..Q.'. Two solutions for n=4.", variables: { solutions: 2, answer: 2 }, opCount: 6, done: true },
          ],
        },
        {
          id: "bit-mask",
          name: "Bit-Mask Optimization",
          time: "O(n!) but with smaller constants",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { n: 4 },
          steps: [
            { id: 0, narration: "Use bit masks for cols/diag1/diag2. 'available' = ~(c|d1|d2) & mask.", variables: { c: 0, d1: 0, d2: 0, m: 0b1111 }, opCount: 0 },
            { id: 1, narration: "available = ~0 & mask = 0b1111. lowbit=0b0001 → place.", variables: { placed: 1 }, opCount: 1 },
            { id: 2, narration: "Same logic walks the search space but with branchless bit tricks.", variables: { explores: "faster" }, opCount: 2, done: true },
          ],
        },
      ],
    },
  ],
};