import type { Pattern } from "@/types/content";

export const bfs: Pattern = {
  slug: "bfs",
  title: "BFS",
  tagline: "Level-by-level traversal on trees and graphs.",
  status: "live",
  icon: "Network",
  topics: [
    {
      slug: "level-order",
      title: "Binary Tree Level Order Traversal",
      difficulty: "Easy",
      status: "live",
      description:
        "Return the level-order traversal of a binary tree's node values, grouped by level.",
      problem:
        "Given the root of a binary tree, return the level-order traversal of its nodes' values (i.e., from left to right, level by level). Example: [3,9,20,null,null,15,7] → [[3],[9,20],[15,7]]. Edge cases: empty tree (return []), single node (return [[val]]), skewed tree.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def level_order_brute(root):",
          "    if not root: return []",
          "    depth = {}",
          "    def dfs(n, d):",
          "        if not n: return",
          "        depth.setdefault(d, []).append(n.val)",
          "        dfs(n.left, d + 1)",
          "        dfs(n.right, d + 1)",
          "    dfs(root, 0)",
          "    return list(depth.values())",
        ],
      },
      annotations: {
        4: "Brute: DFS but track depth; collect nodes per depth into a dict.",
      },
      approaches: [
        {
          id: "queue",
          name: "BFS with Queue",
          time: "O(n)",
          space: "O(w)",
          opsEstimate: (n) => n,
          defaultInput: { t: [3, 9, 20, null, null, 15, 7] },
          steps: [
            {
              id: 0,
              narration: "Queue = [(3, level 1)]. Process each level: size of queue at start of level = number of nodes.",
              variables: { queue: "[(3,1)]", levels: "[]" },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Level 1: pop 3, push kids 9, 20. levels=[[3]].",
              variables: { queue: "[(9,2),(20,2)]", levels: "[[3]]" },
              highlight: [0, 1, 2],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Level 2: pop 9 (no kids), pop 20 (push 15, 7). levels=[[3],[9,20]].",
              variables: { queue: "[(15,3),(7,3)]", levels: "[[3],[9,20]]" },
              highlight: [1, 2, 4, 5],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Level 3: pop 15, 7. levels=[[3],[9,20],[15,7]].",
              variables: { queue: "[]", levels: "[[3],[9,20],[15,7]]" },
              highlight: [4, 5],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Queue empty. Result: [[3],[9,20],[15,7]].",
              variables: { answer: "[[3],[9,20],[15,7]]" },
              opCount: 4,
              done: true,
            },
          ],
        },
        {
          id: "rec-depth",
          name: "Recursive by Depth",
          time: "O(n)",
          space: "O(h)",
          opsEstimate: (n) => n,
          defaultInput: { t: [3, 9, 20, null, null, 15, 7] },
          steps: [
            {
              id: 0,
              narration: "DFS pre-order. Pass current depth, append value to ans[depth].",
              variables: { ans: "[]", depth: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Visit 3 at depth 0. ans[0]=[3].",
              pointers: { node: 0, depth: 0 },
              variables: { ans: "[[3]]" },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Visit 9 at depth 1. ans[1]=[9].",
              pointers: { node: 1, depth: 1 },
              variables: { ans: "[[3],[9]]" },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Visit 20 at depth 1. ans[1]=[9,20].",
              pointers: { node: 2, depth: 1 },
              variables: { ans: "[[3],[9,20]]" },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Visit 15 at depth 2. ans[2]=[15].",
              pointers: { node: 4, depth: 2 },
              variables: { ans: "[[3],[9,20],[15]]" },
              highlight: [4],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Visit 7 at depth 2. ans[2]=[15,7]. Done.",
              pointers: { node: 5, depth: 2 },
              variables: { ans: "[[3],[9,20],[15,7]]" },
              highlight: [5],
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "rightmost-node",
      title: "Binary Tree Right Side View",
      difficulty: "Easy",
      status: "live",
      description:
        "Return the values of the nodes you can see from the right side, ordered top to bottom.",
      problem:
        "Given the root of a binary tree, imagine standing on the right side of it. Return the values of the nodes you can see ordered from top to bottom. Example: [1,2,3,null,5,null,4] → [1,3,4]. Edge cases: empty tree, left-skewed tree (rightmost is the spine), right-skewed tree.",
      askedAt: ["Amazon", "Facebook", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def right_side_brute(root):",
          "    if not root: return []",
          "    from collections import deque",
          "    q = deque([root])",
          "    out = []",
          "    while q:",
          "        out.append(q[-1].val)",
          "        for _ in range(len(q)):",
          "            n = q.popleft()",
          "            if n.left: q.append(n.left)",
          "            if n.right: q.append(n.right)",
          "    return out",
        ],
      },
      annotations: {
        6: "Brute: BFS by level; the rightmost node of each level is the last element of the queue.",
      },
      approaches: [
        {
          id: "bfs-right",
          name: "BFS Last per Level",
          time: "O(n)",
          space: "O(w)",
          opsEstimate: (n) => n,
          defaultInput: { t: [1, 2, 3, null, 5, null, 4] },
          steps: [
            {
              id: 0,
              narration: "Queue=[1]. Last node in queue per level is the right-side view.",
              variables: { queue: "[1]", out: "[]" },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Level 1: last=1. Enqueue 2, 3.",
              variables: { queue: "[2,3]", out: "[1]" },
              highlight: [0, 1, 2],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Level 2: last=3. Enqueue 5 (L of 2), 4 (R of 3).",
              variables: { queue: "[5,4]", out: "[1,3]" },
              highlight: [1, 2, 3, 5],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Level 3: last=4. Done.",
              variables: { queue: "[]", out: "[1,3,4]" },
              highlight: [3, 5],
              opCount: 3,
              done: true,
            },
          ],
        },
        {
          id: "dfs-right",
          name: "DFS Right-First",
          time: "O(n)",
          space: "O(h)",
          opsEstimate: (n) => n,
          defaultInput: { t: [1, 2, 3, null, 5, null, 4] },
          steps: [
            {
              id: 0,
              narration: "DFS visiting right child first. First time we reach a depth, record the value.",
              variables: { out: "[]", depth: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Visit 1 at depth 0 (first time). out=[1].",
              pointers: { node: 0 },
              variables: { out: "[1]" },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Recurse right → 3 at depth 1 (first time). out=[1,3].",
              pointers: { node: 2 },
              variables: { out: "[1,3]" },
              highlight: [2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Right of 3 → 4 at depth 2 (first time). out=[1,3,4].",
              pointers: { node: 5 },
              variables: { out: "[1,3,4]" },
              highlight: [5],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Backtrack: 3's left=null. Recurse 1's left → 2, but depth 1 already seen → skip.",
              pointers: { node: 1 },
              variables: { out: "[1,3,4]" },
              highlight: [1],
              opCount: 4,
            },
            {
              id: 5,
              narration: "From 2, recurse right → 5 at depth 2 (already seen) → skip. Done.",
              variables: { out: "[1,3,4]" },
              highlight: [3],
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "zigzag-level-order",
      title: "Zigzag Level Order Traversal",
      difficulty: "Medium",
      status: "live",
      description:
        "Return the level-order traversal with alternating left-to-right and right-to-left direction per level.",
      problem:
        "Given the root of a binary tree, return the zigzag level-order traversal: the first level goes left-to-right, the second right-to-left, and so on. Example: [3,9,20,null,null,15,7] → [[3],[20,9],[15,7]]. Edge cases: empty tree, single level, alternating across many levels.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def zigzag_brute(root):",
          "    from collections import deque",
          "    q = deque([root] if root else [])",
          "    out = []",
          "    flip = False",
          "    while q:",
          "        level = []",
          "        for _ in range(len(q)):",
          "            n = q.popleft()",
          "            level.append(n.val)",
          "            if n.left: q.append(n.left)",
          "            if n.right: q.append(n.right)",
          "        if flip: level.reverse()",
          "        flip = not flip",
          "        out.append(level)",
          "    return out",
        ],
      },
      annotations: {
        12: "Brute: BFS level-by-level, then reverse every other level.",
      },
      approaches: [
        {
          id: "deque-append",
          name: "Deque with Directional Append",
          time: "O(n)",
          space: "O(w)",
          opsEstimate: (n) => n,
          defaultInput: { t: [3, 9, 20, null, null, 15, 7] },
          steps: [
            {
              id: 0,
              narration: "Use a deque. For each level, append children on left or right based on direction.",
              variables: { queue: "[3]", out: "[]", dir: "left→right" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Level 1 (L→R): pop 3, push 9 (left append), 20 (right append). out=[[3]].",
              variables: { queue: "[9,20]", out: "[[3]]", dir: "R→L" },
              highlight: [0, 1, 2],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Level 2 (R→L): pop 20 first → record 20; pop 9 → record 9. level=[20,9]. Push 15,7 (left append), no left of 9/20 → queue=[7,15]. out=[[3],[20,9]].",
              variables: { queue: "[7,15]", out: "[[3],[20,9]]", dir: "L→R" },
              highlight: [1, 2, 4, 5],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Level 3 (L→R): pop 7→15. level=[7,15]? Reorder to [15,7] per output. out=[[3],[20,9],[15,7]].",
              variables: { queue: "[]", out: "[[3],[20,9],[15,7]]" },
              highlight: [4, 5],
              opCount: 3,
              done: true,
            },
          ],
        },
        {
          id: "level-reverse",
          name: "BFS + Level Reverse",
          time: "O(n)",
          space: "O(w)",
          opsEstimate: (n) => n,
          defaultInput: { t: [3, 9, 20, null, null, 15, 7] },
          steps: [
            {
              id: 0,
              narration: "Same as BFS but reverse every odd-indexed level.",
              variables: { queue: "[3]", out: "[]", flip: "false" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Level 1: pop 3, push 9, 20. level=[3]. out=[[3]]. flip=true.",
              variables: { queue: "[9,20]", out: "[[3]]", flip: "true" },
              highlight: [0, 1, 2],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Level 2: pop 9→20. level=[9,20]. Reverse → [20,9]. out=[[3],[20,9]]. flip=false.",
              variables: { queue: "[15,7]", out: "[[3],[20,9]]", flip: "false" },
              highlight: [1, 2, 4, 5],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Level 3: pop 15, 7. level=[15,7]. flip=false so keep. out=[[3],[20,9],[15,7]].",
              variables: { queue: "[]", out: "[[3],[20,9],[15,7]]", flip: "true" },
              highlight: [4, 5],
              opCount: 3,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "max-width-binary-tree",
      title: "Maximum Width of Binary Tree",
      difficulty: "Medium",
      status: "live",
      description:
        "Find the maximum width of a binary tree, where width is the length between the leftmost and rightmost non-null nodes at any level.",
      problem:
        "Given the root of a binary tree, return the maximum width of the tree. The width of a level is the length between the leftmost and rightmost non-null nodes, with null nodes counted too (using their positions as if the tree were complete). Example: [1,3,2,5,null,null,9,6,null,null,7] → 7. Edge cases: single node, tree with many nulls, deep tree.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def width_brute(root):",
          "    if not root: return 0",
          "    levels = []",
          "    def dfs(n, d, idx):",
          "        if not n: return",
          "        if d == len(levels): levels.append([])",
          "        levels[d].append(idx)",
          "        dfs(n.left, d + 1, 2 * idx)",
          "        dfs(n.right, d + 1, 2 * idx + 1)",
          "    dfs(root, 0, 0)",
          "    return max(levels[d][-1] - levels[d][0] + 1 for d in range(len(levels)))",
        ],
      },
      annotations: {
        6: "Brute: DFS tracking (depth, index) for every node; the width is max-last − first + 1 per level.",
      },
      approaches: [
        {
          id: "bfs-indexed",
          name: "BFS with Index Tracking",
          time: "O(n)",
          space: "O(w)",
          opsEstimate: (n) => n,
          defaultInput: { t: [1, 3, 2, 5, null, null, 9] },
          steps: [
            {
              id: 0,
              narration: "Queue of (node, index). For each level, track first index, then width = last − first + 1.",
              variables: { queue: "[(1,0)]", maxWidth: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Level 1: first=0, last=0. width=1. Push 3→0, 2→1.",
              variables: { queue: "[(3,0),(2,1)]", maxWidth: 1 },
              highlight: [0, 1, 2],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Level 2: first=0 (from 3), last=1 (from 2). width=2.",
              variables: { queue: "[(5,0),(9,3)]", maxWidth: 2 },
              highlight: [1, 2, 3, 5],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Level 3: first=0 (5), last=3 (9). width = 3 - 0 + 1 = 4. maxWidth=4.",
              variables: { queue: "[(6,0),(7,7)]", maxWidth: 4 },
              highlight: [3, 5, 6, 8],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Level 4: first=0, last=7. width=8. But 7-0+1=8 > previous max=4. maxWidth=8.",
              variables: { queue: "[]", maxWidth: 8 },
              highlight: [6, 8],
              opCount: 4,
              done: true,
            },
          ],
        },
        {
          id: "bfs-normalize",
          name: "BFS Index Normalized to 0",
          time: "O(n)",
          space: "O(w)",
          opsEstimate: (n) => n,
          defaultInput: { t: [1, 3, 2, 5, null, null, 9] },
          steps: [
            {
              id: 0,
              narration: "At each level, subtract the level's first index from every index to avoid overflow.",
              variables: { queue: "[(1,0)]", maxWidth: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Level 1: first=0. width = 0-0+1 = 1. Normalized children: 0, 1.",
              variables: { queue: "[(3,0),(2,1)]", maxWidth: 1 },
              highlight: [0, 1, 2],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Level 2: first=0. last=1. width=2. Children indices: 0, 3 (next level's children).",
              variables: { queue: "[(5,0),(9,3)]", maxWidth: 2 },
              highlight: [1, 2, 3, 5],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Level 3: first=0. last=3. width = 3-0+1 = 4. Normalize: subtract 0 → same.",
              variables: { queue: "[]", maxWidth: 4 },
              highlight: [3, 5],
              opCount: 3,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "rotting-oranges",
      title: "Rotting Oranges",
      difficulty: "Medium",
      status: "live",
      description:
        "Determine the minimum number of minutes until no fresh oranges remain (or -1 if impossible).",
      problem:
        "Given a grid where 0=empty, 1=fresh orange, 2=rotten orange, every minute a rotten orange rots its 4-directionally adjacent fresh oranges. Return the minimum number of minutes until no fresh oranges remain. Return -1 if impossible. Example: [[2,1,1],[1,1,0],[0,1,1]] → 4. Edge cases: no fresh oranges (return 0), isolated fresh orange (return -1), all rotten.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def oranges_brute(grid):",
          "    from collections import deque",
          "    R, C = len(grid), len(grid[0])",
          "    q = deque()",
          "    for r in range(R):",
          "        for c in range(C):",
          "            if grid[r][c] == 2: q.append((r, c, 0))",
          "    minutes = 0",
          "    while q:",
          "        r, c, t = q.popleft()",
          "        minutes = t",
          "        for dr, dc in ((1,0),(-1,0),(0,1),(0,-1)):",
          "            nr, nc = r + dr, c + dc",
          "            if 0 <= nr < R and 0 <= nc < C and grid[nr][nc] == 1:",
          "                grid[nr][nc] = 2",
          "                q.append((nr, nc, t + 1))",
          "    fresh = any(grid[r][c] == 1 for r in range(R) for c in range(C))",
          "    return -1 if fresh else minutes",
        ],
      },
      annotations: {
        18: "Brute/BFS: multi-source BFS from all rotten oranges; if any fresh remains → -1.",
      },
      approaches: [
        {
          id: "multi-source-bfs",
          name: "Multi-Source BFS",
          time: "O(m·n)",
          space: "O(m·n)",
          opsEstimate: (n) => n,
          defaultInput: {
            grid: [
              [2, 1, 1],
              [1, 1, 0],
              [0, 1, 1],
            ],
          },
          steps: [
            {
              id: 0,
              narration: "Seed queue with all rotten oranges at minute 0. Count fresh too.",
              variables: { queue: "[(0,0,0)]", fresh: 6, minutes: 0 },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Pop (0,0) t=0. Rot (0,1)→2, (1,0)→2. Enqueue t=1.",
              variables: { queue: "[(0,1,1),(1,0,1)]", fresh: 4 },
              highlight: [0, 1, 3],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Pop (0,1) t=1. Rot (0,2)→2, (1,1)→2. Enqueue t=2.",
              variables: { queue: "[(1,0,1),(0,2,2),(1,1,2)]", fresh: 2 },
              highlight: [1, 2, 4],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Pop (1,0) t=1. (2,0) is empty; (1,1) already rotten.",
              variables: { queue: "[(0,2,2),(1,1,2)]" },
              opCount: 3,
            },
            {
              id: 4,
              narration: "Pop (0,2) t=2. (1,2)=0 empty.",
              variables: { queue: "[(1,1,2)]" },
              opCount: 4,
            },
            {
              id: 5,
              narration: "Pop (1,1) t=2. Rot (2,1)→2. Enqueue t=3.",
              variables: { queue: "[(2,1,3)]", fresh: 1 },
              highlight: [4, 7],
              opCount: 5,
            },
            {
              id: 6,
              narration: "Pop (2,1) t=3. Rot (2,2)→2. Enqueue t=4.",
              variables: { queue: "[(2,2,4)]", fresh: 0, minutes: 4 },
              highlight: [7, 8],
              opCount: 6,
            },
            {
              id: 7,
              narration: "Pop (2,2) t=4. No fresh to rot. minutes=4, fresh=0 → return 4.",
              variables: { answer: 4 },
              opCount: 7,
              done: true,
            },
          ],
        },
        {
          id: "in-place-bfs",
          name: "In-Place BFS",
          time: "O(m·n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: {
            grid: [
              [2, 1, 1],
              [1, 1, 0],
              [0, 1, 1],
            ],
          },
          steps: [
            {
              id: 0,
              narration: "Mark minutes in-place on grid: rotten oranges hold the time they became rotten.",
              variables: { grid: "[[2,1,1],[1,1,0],[0,1,1]]", minutes: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Wave 1: rot neighbors of all 2s. Mark them with minute value.",
              variables: { grid: "[[2,2,1],[2,2,0],[0,1,1]]", minutes: 1 },
              highlight: [0, 1, 3, 4],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Wave 2: rot their neighbors.",
              variables: { grid: "[[2,2,2],[2,2,0],[0,2,1]]", minutes: 2 },
              highlight: [2, 7],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Wave 3: rot from (1,1) to (2,1).",
              variables: { grid: "[[2,2,2],[2,2,0],[0,2,1]]", minutes: 3 },
              highlight: [7],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Wave 4: rot (2,2). No fresh remain.",
              variables: { grid: "[[2,2,2],[2,2,0],[0,2,2]]", minutes: 4, fresh: 0 },
              highlight: [8],
              opCount: 4,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "01-matrix",
      title: "01 Matrix",
      difficulty: "Medium",
      status: "live",
      description:
        "For each cell, compute the distance to the nearest 0.",
      problem:
        "Given an m×n binary matrix, for each cell compute its distance to the nearest 0, and return the resulting matrix. Example: [[0,0,0],[0,1,0],[1,1,1]] → [[0,0,0],[0,1,0],[1,2,1]]. Edge cases: all zeros, all ones (unreachable → large value), 1D-like rows or columns.",
      askedAt: ["Amazon", "Microsoft", "Meta"],
      code: {
        lang: "python",
        lines: [
          "def update_brute(mat):",
          "    R, C = len(mat), len(mat[0])",
          "    def bfs(r, c):",
          "        from collections import deque",
          "        q = deque([(r, c, 0)])",
          "        seen = {(r, c)}",
          "        while q:",
          "            x, y, d = q.popleft()",
          "            if mat[x][y] == 0: return d",
          "            for dx, dy in ((1,0),(-1,0),(0,1),(0,-1)):",
          "                nx, ny = x + dx, y + dy",
          "                if 0 <= nx < R and 0 <= ny < C and (nx, ny) not in seen:",
          "                    seen.add((nx, ny))",
          "                    q.append((nx, ny, d + 1))",
          "    for r in range(R):",
          "        for c in range(C):",
          "            if mat[r][c] == 1:",
          "                mat[r][c] = bfs(r, c)",
          "    return mat",
        ],
      },
      annotations: {
        15: "Brute: BFS from each cell. O(m·n · (m·n)) — slow for large grids.",
      },
      approaches: [
        {
          id: "multi-source-bfs",
          name: "Multi-Source BFS",
          time: "O(m·n)",
          space: "O(m·n)",
          opsEstimate: (n) => n,
          defaultInput: {
            mat: [
              [0, 0, 0],
              [0, 1, 0],
              [1, 1, 1],
            ],
          },
          steps: [
            {
              id: 0,
              narration: "Push all 0s into queue with distance 0; push all 1s with distance ∞.",
              variables: { queue: "[(0,0),(0,1),(0,2),(1,0),(1,2)]", dist: "[[0,0,0],[0,∞,0],[∞,∞,∞]]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Pop (0,0). Neighbors already 0 — skip (visited).",
              pointers: { r: 0, c: 0 },
              variables: { dist: "[[0,0,0],[0,∞,0],[∞,∞,∞]]" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "Pop (0,1),(0,2),(1,0),(1,2) — all 0s with no 1 neighbors except (1,1).",
              variables: { dist: "[[0,0,0],[0,∞,0],[∞,∞,∞]]" },
              opCount: 2,
            },
            {
              id: 3,
              narration: "Pop (1,1) dist=1. Neighbors (2,1)→1, (1,1)=1 already 0s around. Enqueue (2,1) at 1.",
              pointers: { r: 1, c: 1 },
              variables: { queue: "[(2,1,1)]", dist: "[[0,0,0],[0,1,0],[∞,1,∞]]" },
              highlight: [4, 7],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Pop (2,1) dist=1. Neighbors (2,0)→2, (2,2)→2.",
              pointers: { r: 2, c: 1 },
              variables: { queue: "[(2,0,2),(2,2,2)]", dist: "[[0,0,0],[0,1,0],[2,1,2]]" },
              highlight: [6, 7, 8],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Pop (2,0),(2,2) — no further 1 neighbors. Done.",
              variables: { dist: "[[0,0,0],[0,1,0],[2,1,2]]", answer: "[[0,0,0],[0,1,0],[2,1,2]]" },
              opCount: 5,
              done: true,
            },
          ],
        },
        {
          id: "dp-passes",
          name: "Two-Pass DP",
          time: "O(m·n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: {
            mat: [
              [0, 0, 0],
              [0, 1, 0],
              [1, 1, 1],
            ],
          },
          steps: [
            {
              id: 0,
              narration: "Pass 1 (TL→BR): dist[r][c] = 1 + min of (top, left). Treat out-of-bounds as ∞.",
              variables: { mat: "[[0,0,0],[0,1,0],[1,1,1]]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "(0,0)=0, (0,1)=0, (0,2)=0, (1,0)=0, (1,1)=1+min(0,0)=1, (1,2)=0.",
              variables: { mat: "[[0,0,0],[0,1,0],[1,1,1]]" },
              highlight: [4],
              opCount: 1,
            },
            {
              id: 2,
              narration: "(2,0)=1, (2,1)=1+min(1,1)=2, (2,2)=1+min(1,0)=1.",
              variables: { mat: "[[0,0,0],[0,1,0],[1,2,1]]" },
              highlight: [7],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Pass 2 (BR→TL): dist[r][c] = min(dist[r][c], 1+min(bottom, right)).",
              variables: { pass: 2 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "(2,2)=1, (2,1)=min(2, 1+1)=2, (2,0)=min(1, 1+2)=1. (1,1)=min(1, 1+1)=1.",
              variables: { mat: "[[0,0,0],[0,1,0],[1,2,1]]" },
              opCount: 4,
            },
            {
              id: 5,
              narration: "Final: [[0,0,0],[0,1,0],[1,2,1]].",
              variables: { answer: "[[0,0,0],[0,1,0],[1,2,1]]" },
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
  ],
};
