import type { Pattern } from "@/types/content";

export const dp1d: Pattern = {
  slug: "dp-1d",
  title: "1-D Dynamic Programming",
  tagline: "Linear DP: Fibonacci-style recurrence.",
  status: "live",
  icon: "TrendingUp",
  topics: [
    {
      slug: "climbing-stairs",
      title: "Climbing Stairs",
      difficulty: "Easy",
      status: "live",
      description: "Count the number of distinct ways to climb n stairs, taking 1 or 2 steps at a time.",
      problem:
        "You are climbing a staircase. It takes `n` steps to reach the top. Each move you can either climb 1 or 2 steps. In how many distinct ways can you reach the top? Example: n=2 → 2 (1+1, 2); n=3 → 3. Edge cases: n=0 (1 way — already at the top), n=1 (1 way), and n up to 45.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def climb_brute(n):",
          "    if n <= 1: return 1",
          "    return climb_brute(n - 1) + climb_brute(n - 2)",
        ],
      },
      annotations: {
        2: "Brute: recursive solution without memoization — exponential complexity.",
      },
      approaches: [
        {
          id: "memo",
          name: "Recursive + Memoization",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { n: 5 },
          steps: [
            {
              id: 0,
              narration: "fib(5): check memo[5] — miss. Recurse.",
              variables: { memo: "{}" },
              pointers: { n: 5 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "fib(5) → fib(4) + fib(3).",
              variables: { memo: "{}" },
              pointers: { n: 4 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "fib(4) → fib(3) + fib(2).",
              variables: { memo: "{}" },
              pointers: { n: 3 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "fib(3) → fib(2) + fib(1).",
              variables: { memo: "{}" },
              pointers: { n: 2 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "fib(2) → fib(1) + fib(0) = 1 + 1 = 2. memo[2]=2.",
              variables: { memo: "{2:2}" },
              pointers: { n: 1 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "fib(1) = 1 (base case). memo[1]=1.",
              variables: { memo: "{2:2, 1:1}" },
              pointers: { n: 1 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "fib(3) = 2 + 1 = 3. memo[3]=3.",
              variables: { memo: "{2:2, 1:1, 3:3}" },
              pointers: { n: 3 },
              opCount: 6,
            },
            {
              id: 7,
              narration: "fib(5) = fib(4) + fib(3) = 5 + 3 = 8.",
              variables: { memo: "{1:1, 2:2, 3:3, 4:5, 5:8}" },
              pointers: { n: 5 },
              opCount: 7,
              done: true,
            },
          ],
        },
        {
          id: "dp-table",
          name: "Iterative DP",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { n: 5 },
          steps: [
            {
              id: 0,
              narration: "dp[0]=1, dp[1]=1 (base cases).",
              variables: { dp: "[1,1]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "dp[2] = dp[1] + dp[0] = 1 + 1 = 2.",
              variables: { dp: "[1,1,2]" },
              pointers: { i: 2 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "dp[3] = dp[2] + dp[1] = 2 + 1 = 3.",
              variables: { dp: "[1,1,2,3]" },
              pointers: { i: 3 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "dp[4] = dp[3] + dp[2] = 3 + 2 = 5.",
              variables: { dp: "[1,1,2,3,5]" },
              pointers: { i: 4 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "dp[5] = dp[4] + dp[3] = 5 + 3 = 8.",
              variables: { dp: "[1,1,2,3,5,8]" },
              pointers: { i: 5 },
              opCount: 4,
              done: true,
            },
          ],
        },
        {
          id: "space-opt",
          name: "Space-Optimized (2 vars)",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { n: 5 },
          steps: [
            {
              id: 0,
              narration: "a=1 (dp[0]), b=1 (dp[1]).",
              variables: { a: 1, b: 1 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "c = a + b = 1 + 1 = 2. Shift: a=b=1, b=c=2.",
              variables: { a: 1, b: 2 },
              pointers: { i: 2 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "c = a + b = 1 + 2 = 3. Shift: a=2, b=3.",
              variables: { a: 2, b: 3 },
              pointers: { i: 3 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "c = a + b = 2 + 3 = 5. Shift: a=3, b=5.",
              variables: { a: 3, b: 5 },
              pointers: { i: 4 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "c = a + b = 3 + 5 = 8. Shift: a=5, b=8.",
              variables: { a: 5, b: 8 },
              pointers: { i: 5 },
              opCount: 4,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "house-robber",
      title: "House Robber",
      difficulty: "Medium",
      status: "live",
      description: "Rob houses on a street to maximize loot. No two adjacent houses can be robbed.",
      problem:
        "You are a robber planning to rob houses on a street. Each house has a non-negative integer amount. Adjacent houses have connected security systems, so you cannot rob two adjacent houses. Maximize the loot. Example: `nums=[2,7,9,3,1]` → 12 (rob houses 0,2,4). Edge cases: array of length 1 (take it), single 0 (return 0), and arrays where rob-skip-rob is best.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def rob_brute(nums):",
          "    n = len(nums)",
          "    def rec(i, taken_last):",
          "        if i >= n: return 0",
          "        if taken_last:",
          "            return rec(i + 1, False)",
          "        return max(rec(i + 1, False), nums[i] + rec(i + 1, True))",
          "    return rec(0, False)",
        ],
      },
      annotations: {
        1: "Brute: try every (rob, skip) combination without memoization — exponential.",
      },
      approaches: [
        {
          id: "dp-table",
          name: "DP Table",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { nums: [2, 7, 9, 3, 1] },
          steps: [
            {
              id: 0,
              narration: "dp[0] = 2 (rob house 0 alone).",
              variables: { dp: "[2]" },
              pointers: { i: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "dp[1] = max(dp[0], nums[1]) = max(2, 7) = 7.",
              variables: { dp: "[2,7]" },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 1,
            },
            {
              id: 2,
              narration: "dp[2] = max(dp[1], dp[0]+nums[2]) = max(7, 2+9) = 11.",
              variables: { dp: "[2,7,11]" },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "dp[3] = max(dp[2], dp[1]+nums[3]) = max(11, 7+3) = 11.",
              variables: { dp: "[2,7,11,11]" },
              pointers: { i: 3 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "dp[4] = max(dp[3], dp[2]+nums[4]) = max(11, 11+1) = 12.",
              variables: { dp: "[2,7,11,11,12]" },
              pointers: { i: 4 },
              highlight: [4],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Rob houses 0,2,4 → 2+9+1 = 12. Done.",
              variables: { dp: "[2,7,11,11,12]" },
              opCount: 5,
              done: true,
            },
          ],
        },
        {
          id: "space-opt",
          name: "Space-Optimized (2 vars)",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { nums: [2, 7, 9, 3, 1] },
          steps: [
            {
              id: 0,
              narration: "prev = 0, curr = 0.",
              variables: { prev: 0, curr: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=0: new = max(curr, prev+nums[0]) = max(0, 0+2) = 2.",
              variables: { prev: 0, curr: 2 },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=1: new = max(2, 0+7) = 7. Shift: prev=2, curr=7.",
              variables: { prev: 2, curr: 7 },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=2: new = max(7, 2+9) = 11. Shift: prev=7, curr=11.",
              variables: { prev: 7, curr: 11 },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=3: new = max(11, 7+3) = 11. Shift: prev=11, curr=11.",
              variables: { prev: 11, curr: 11 },
              pointers: { i: 3 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=4: new = max(11, 11+1) = 12. Answer = 12.",
              variables: { prev: 11, curr: 12 },
              pointers: { i: 4 },
              highlight: [4],
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "coin-change",
      title: "Coin Change",
      difficulty: "Medium",
      status: "live",
      description: "Find the minimum number of coins that sum to amount. Each coin can be used unlimited times.",
      problem:
        "Given an integer array `coins` (each representing a coin denomination) and an integer `amount`, return the fewest number of coins needed to make up that amount. If it's impossible, return -1. Each coin can be used an unlimited number of times. Example: `coins=[1,5,6,9], amount=11` → 2 (5+6). Edge cases: amount=0 (no coins needed), no valid coin combination (return -1), coin denominations include 1 (always solvable when amount>0).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def coin_brute(coins, amount):",
          "    def rec(amt, used):",
          "        if amt == 0: return used",
          "        if amt < 0: return float('inf')",
          "        return min(rec(amt - c, used + 1) for c in coins)",
          "    ans = rec(amount, 0)",
          "    return -1 if ans == float('inf') else ans",
        ],
      },
      annotations: {
        1: "Brute: recursive search over coin picks without memoization — exponential.",
      },
      approaches: [
        {
          id: "dp-table",
          name: "DP Table",
          time: "O(n * amount)",
          space: "O(amount)",
          opsEstimate: (n) => n * 11,
          defaultInput: { coins: [1, 5, 6, 9], amount: 11 },
          steps: [
            {
              id: 0,
              narration: "dp[0]=0; rest = ∞ (impossible).",
              variables: { dp: "[0,∞,∞,∞,∞,∞,∞,∞,∞,∞,∞,∞]" },
              pointers: { amt: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "dp[1] = dp[0]+1 = 1 (one 1-coin).",
              variables: { dp: "[0,1,∞,∞,∞,∞,∞,∞,∞,∞,∞,∞]" },
              pointers: { amt: 1 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "dp[2] = dp[1]+1 = 2.",
              variables: { dp: "[0,1,2,∞,∞,∞,∞,∞,∞,∞,∞,∞]" },
              pointers: { amt: 2 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "dp[3] = dp[2]+1 = 3.",
              variables: { dp: "[0,1,2,3,∞,∞,∞,∞,∞,∞,∞,∞]" },
              pointers: { amt: 3 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "dp[4] = dp[3]+1 = 4.",
              variables: { dp: "[0,1,2,3,4,∞,∞,∞,∞,∞,∞,∞]" },
              pointers: { amt: 4 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "dp[5] = min(dp[4]+1, dp[0]+1) = min(5,1) = 1 (one 5-coin).",
              variables: { dp: "[0,1,2,3,4,1,∞,∞,∞,∞,∞,∞]" },
              pointers: { amt: 5 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "dp[6] = min(dp[5]+1, dp[1]+1, dp[0]+1) = min(2,2,1) = 1 (one 6-coin).",
              variables: { dp: "[0,1,2,3,4,1,1,∞,∞,∞,∞,∞]" },
              pointers: { amt: 6 },
              opCount: 6,
            },
            {
              id: 7,
              narration: "dp[7] = min(dp[6]+1, dp[2]+1, dp[1]+1) = min(2,3,2) = 2 (6+1).",
              variables: { dp: "[0,1,2,3,4,1,1,2,∞,∞,∞,∞]" },
              pointers: { amt: 7 },
              opCount: 7,
            },
            {
              id: 8,
              narration: "dp[8] = min(dp[7]+1, dp[3]+1, dp[2]+1) = min(3,4,3) = 3 (6+1+1).",
              variables: { dp: "[0,1,2,3,4,1,1,2,3,∞,∞,∞]" },
              pointers: { amt: 8 },
              opCount: 8,
            },
            {
              id: 9,
              narration: "dp[9] = min(dp[8]+1, dp[4]+1, dp[3]+1, dp[0]+1) = min(4,5,4,1) = 1 (one 9-coin).",
              variables: { dp: "[0,1,2,3,4,1,1,2,3,1,∞,∞]" },
              pointers: { amt: 9 },
              opCount: 9,
            },
            {
              id: 10,
              narration: "dp[10] = min(dp[9]+1, dp[5]+1, dp[4]+1, dp[1]+1) = min(2,2,5,2) = 2 (9+1).",
              variables: { dp: "[0,1,2,3,4,1,1,2,3,1,2,∞]" },
              pointers: { amt: 10 },
              opCount: 10,
            },
            {
              id: 11,
              narration: "dp[11] = min(dp[10]+1, dp[6]+1, dp[5]+1, dp[2]+1) = min(3,2,2,3) = 2 (5+6).",
              variables: { dp: "[0,1,2,3,4,1,1,2,3,1,2,2]" },
              pointers: { amt: 11 },
              opCount: 11,
              done: true,
            },
          ],
        },
        {
          id: "bfs",
          name: "BFS-style",
          time: "O(n * amount)",
          space: "O(amount)",
          opsEstimate: (n) => n * 11,
          defaultInput: { coins: [1, 5, 6, 9], amount: 11 },
          steps: [
            {
              id: 0,
              narration: "Queue starts at {0}. dist[0]=0.",
              variables: { queue: "{0}", dist: "{0:0}" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Pop 0. For each coin c: enqueue 0+c if unseen.",
              variables: { queue: "{1,5,6,9}", dist: "{0:0,1:1,5:1,6:1,9:1}" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "Pop 1. Enqueue 2,6,7,10.",
              variables: { queue: "{5,6,9,2,6,7,10}", dist: "{…,2:2,6:1,7:2,10:2}" },
              opCount: 2,
            },
            {
              id: 3,
              narration: "Pop 5. Enqueue 6(skip),10(skip),11(new),14(skip).",
              variables: { queue: "{6,9,2,6,7,10,11}", dist: "{…,11:2}" },
              opCount: 3,
            },
            {
              id: 4,
              narration: "Pop 6. Enqueue 7(skip),11(skip),12,15.",
              variables: { queue: "{9,2,6,7,10,11,12,15}", dist: "{…,12:3}" },
              opCount: 4,
            },
            {
              id: 5,
              narration: "Continue BFS. First time we visit 11 is at distance 2.",
              variables: { queue: "{2,7,10,11,…}", dist: "{…,11:2}" },
              opCount: 5,
            },
            {
              id: 6,
              narration: "Found 11! dist[11] = 2. Done (5+6 or 1+1+9).",
              variables: { answer: 2 },
              opCount: 6,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "maximum-subarray",
      title: "Maximum Subarray",
      difficulty: "Medium",
      status: "live",
      description: "Find the contiguous subarray with the largest sum.",
      problem:
        "Given an integer array `nums`, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum. A subarray is a contiguous part of the array. Example: `nums=[-2,1,-3,4,-1,2,1,-5,4]` → 6 (subarray [4,-1,2,1]). Edge cases: all-positive arrays (sum is whole array), all-negative arrays (max single element), single element, and the array containing zeros.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Apple", "LinkedIn"],
      code: {
        lang: "python",
        lines: [
          "def max_sub_brute(nums):",
          "    best = float('-inf')",
          "    n = len(nums)",
          "    for i in range(n):",
          "        for j in range(i, n):",
          "            s = sum(nums[i:j+1])",
          "            best = max(best, s)",
          "    return best",
        ],
      },
      annotations: {
        4: "Try every subarray pair (i, j) — O(n³).",
      },
      approaches: [
        {
          id: "kadane",
          name: "Kadane",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [-2, 1, -3, 4, -1, 2, 1, -5, 4] },
          steps: [
            { id: 0, narration: "curr = best = nums[0] = -2.", variables: { curr: -2, best: -2 }, pointers: { i: 0 }, opCount: 0 },
            { id: 1, narration: "i=1, x=1. curr = max(1, -2+1) = 1. best=1.", variables: { curr: 1, best: 1 }, pointers: { i: 1 }, highlight: [1], opCount: 1 },
            { id: 2, narration: "i=2, x=-3. curr = max(-3, 1-3) = -2. best=1.", variables: { curr: -2, best: 1 }, pointers: { i: 2 }, highlight: [2], opCount: 2 },
            { id: 3, narration: "i=3, x=4. curr = max(4, -2+4) = 4. best=4.", variables: { curr: 4, best: 4 }, pointers: { i: 3 }, highlight: [3], opCount: 3 },
            { id: 4, narration: "i=4, x=-1. curr = max(-1, 4-1) = 3. best=4.", variables: { curr: 3, best: 4 }, pointers: { i: 4 }, highlight: [4], opCount: 4 },
            { id: 5, narration: "i=5, x=2. curr = 3+2 = 5. best=5.", variables: { curr: 5, best: 5 }, pointers: { i: 5 }, highlight: [5], opCount: 5 },
            { id: 6, narration: "i=6, x=1. curr = 5+1 = 6. best=6.", variables: { curr: 6, best: 6 }, pointers: { i: 6 }, highlight: [6], opCount: 6 },
            { id: 7, narration: "i=7, x=-5. curr = 1. best=6.", variables: { curr: 1, best: 6 }, pointers: { i: 7 }, highlight: [7], opCount: 7 },
            { id: 8, narration: "i=8, x=4. curr = 5. best=6. Final answer = 6.", variables: { best: 6, answer: 6 }, pointers: { i: 8 }, highlight: [8], opCount: 8, done: true },
          ],
        },
        {
          id: "divide-and-conquer",
          name: "Divide & Conquer",
          time: "O(n log n)",
          space: "O(log n)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { array: [-2, 1, -3, 4, -1, 2, 1, -5, 4] },
          steps: [
            { id: 0, narration: "Recursively find best in left, right, and crossing mid.", variables: { array: "[-2,1,-3,4,-1,2,1,-5,4]" }, opCount: 0 },
            { id: 1, narration: "Best crosses mid when it's the max-suffix of left + max-prefix of right.", variables: { left: "1", right: "..." }, opCount: 1 },
            { id: 2, narration: "Combine: 6 wins. Done.", variables: { answer: 6 }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "decode-ways",
      title: "Decode Ways",
      difficulty: "Medium",
      status: "live",
      description: "Count the number of ways to decode a string of digits into letters.",
      problem:
        "A message containing letters A-Z is encoded as numbers: 'A'→1, 'B'→2, ..., 'Z'→26. Given a non-empty string `s` containing only digits, return the number of ways to decode it. Example: `'12'` → 2 ('AB' or 'L'); `'226'` → 3. Edge cases: leading zero (no valid decode, return 0), single digit, '0' alone (return 0), and inputs like '10' (only 'J').",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def decode_brute(s):",
          "    if not s: return 1",
          "    if s[0] == '0': return 0",
          "    count = decode_brute(s[1:])",
          "    if len(s) >= 2 and 10 <= int(s[:2]) <= 26:",
          "        count += decode_brute(s[2:])",
          "    return count",
        ],
      },
      annotations: {
        3: "Either decode the first char alone, or combined if it forms a valid 2-digit code.",
      },
      approaches: [
        {
          id: "dp-table",
          name: "DP Table",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { s: "226" },
          steps: [
            { id: 0, narration: "dp[i] = number of ways to decode s[i:]. dp[n]=1.", variables: { dp: "[3,2,1,1]" }, opCount: 0 },
            { id: 1, narration: "i=2, s[2]='6'. dp[2]=1 ('F').", variables: { dp: "[3,2,1,1]" }, pointers: { i: 2 }, opCount: 1 },
            { id: 2, narration: "i=1, s[1]='2'. Pair '26' valid → dp[1] = dp[2] + dp[3] = 2.", variables: { dp: "[3,2,1,1]" }, pointers: { i: 1 }, highlight: [1], opCount: 2 },
            { id: 3, narration: "i=0, s[0]='2'. Pair '22' valid → dp[0] = dp[1] + dp[2] = 3.", variables: { dp: "[3,2,1,1]" }, pointers: { i: 0 }, highlight: [0], opCount: 3 },
            { id: 4, narration: "dp[0] = 3. Three decodings: BBF, BZ, VF.", variables: { answer: 3 }, pointers: { i: 0 }, opCount: 4, done: true },
          ],
        },
        {
          id: "rolling",
          name: "Rolling 2 vars",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { s: "226" },
          steps: [
            { id: 0, narration: "Keep (pp, p) where p=dp[i+1], pp=dp[i+2]. Initialize (p=1, pp=1).", variables: { pp: 1, p: 1 }, opCount: 0 },
            { id: 1, narration: "i=1 → cur = p + (dp[0:2] valid ? pp : 0). Update pp=p, p=cur.", variables: { pp: 1, p: 2 }, pointers: { i: 1 }, opCount: 1 },
            { id: 2, narration: "i=0 → same logic. cur = 3.", variables: { pp: 2, p: 3 }, pointers: { i: 0 }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "longest-increasing-subseq",
      title: "Longest Increasing Subsequence",
      difficulty: "Medium",
      status: "live",
      description: "Find the length of the longest strictly increasing subsequence.",
      problem:
        "Given an integer array `nums`, return the length of the longest strictly increasing subsequence. A subsequence is a sequence that can be derived from an array by deleting some elements without changing the order. Example: `[10,9,2,5,3,7,101,18]` → 4 (subsequence [2,3,7,18]). Edge cases: empty array (0), strictly increasing array (n), strictly decreasing array (1), and all-equal arrays (1).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def lis_brute(nums):",
          "    n = len(nums)",
          "    def rec(i, prev):",
          "        if i == n: return 0",
          "        skip = rec(i + 1, prev)",
          "        take = 0",
          "        if nums[i] > prev:",
          "            take = 1 + rec(i + 1, nums[i])",
          "        return max(skip, take)",
          "    return rec(0, float('-inf'))",
        ],
      },
      annotations: {
        4: "Brute: try every subsequence split without memoization — exponential.",
      },
      approaches: [
        {
          id: "dp",
          name: "DP O(n²)",
          time: "O(n²)",
          space: "O(n)",
          opsEstimate: (n) => n * n,
          defaultInput: { array: [10, 9, 2, 5, 3, 7, 101, 18] },
          steps: [
            { id: 0, narration: "dp[i] = length of LIS ending at i. Initialize 1s.", variables: { dp: "[1,1,1,1,1,1,1,1]" }, opCount: 0 },
            { id: 1, narration: "i=0, no earlier. dp[0]=1.", variables: { dp: "[1,...]" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "i=3 (val 5): prior values smaller than 5 → nums[2]=2. dp[3]=dp[2]+1=2.", variables: { dp: "[1,1,1,2,...]" }, pointers: { i: 3 }, highlight: [2, 3], opCount: 2 },
            { id: 3, narration: "i=5 (val 7): smaller prior at indices 2,3,4. dp[5]=max+1=3.", variables: { dp: "[1,1,1,2,2,3,...]" }, pointers: { i: 5 }, highlight: [2, 3, 4, 5], opCount: 3 },
            { id: 4, narration: "i=7 (val 18): smaller prior at 2,3,4,5,6 with dp=1,2,2,3,1 → max=3. dp[7]=4.", variables: { dp: "[1,1,1,2,2,3,1,4]" }, pointers: { i: 7 }, highlight: [2, 3, 4, 5, 7], opCount: 4 },
            { id: 5, narration: "max(dp) = 4. Answer = 4.", variables: { answer: 4 }, opCount: 5, done: true },
          ],
        },
        {
          id: "patience-sorting",
          name: "Patience Sorting (O(n log n))",
          time: "O(n log n)",
          space: "O(n)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { array: [10, 9, 2, 5, 3, 7, 101, 18] },
          steps: [
            { id: 0, narration: "Maintain a sorted 'tails' array; for each x, binary-search for lower_bound of x.", variables: { tails: "[]" }, opCount: 0 },
            { id: 1, narration: "10 → tails=[10].", variables: { tails: "[10]" }, opCount: 1 },
            { id: 2, narration: "9 → replace position 0 → tails=[9].", variables: { tails: "[9]" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "2 → replace position 0 → tails=[2].", variables: { tails: "[2]" }, pointers: { i: 2 }, opCount: 3 },
            { id: 4, narration: "5 → replace pos 1 → tails=[2,5].", variables: { tails: "[2,5]" }, pointers: { i: 3 }, opCount: 4 },
            { id: 5, narration: "3 → replace pos 1 → tails=[2,3].", variables: { tails: "[2,3]" }, pointers: { i: 4 }, opCount: 5 },
            { id: 6, narration: "7 → append → tails=[2,3,7].", variables: { tails: "[2,3,7]" }, pointers: { i: 5 }, opCount: 6 },
            { id: 7, narration: "101 → append → tails=[2,3,7,101]. 4 so far.", variables: { tails: "[2,3,7,101]" }, pointers: { i: 6 }, opCount: 7 },
            { id: 8, narration: "18 → replace pos 3 → tails=[2,3,7,18]. Length still 4.", variables: { tails: "[2,3,7,18]", answer: 4 }, opCount: 8, done: true },
          ],
        },
      ],
    },
    {
      slug: "word-break",
      title: "Word Break",
      difficulty: "Medium",
      status: "live",
      description: "Decide if a string can be segmented into dictionary words.",
      problem:
        "Given a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words. The same dictionary word may be reused. Example: `s='leetcode', wordDict=['leet','code']` → true. Edge cases: empty string (true), dictionary containing the entire string, and wordDict with duplicates.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def word_break_brute(s, wordDict):",
          "    def rec(i):",
          "        if i == len(s): return True",
          "        for w in wordDict:",
          "            if s[i:i+len(w)] == w and rec(i + len(w)):",
          "                return True",
          "        return False",
          "    return rec(0)",
        ],
      },
      annotations: {
        3: "Brute: try every dictionary word at every position without memoization.",
      },
      approaches: [
        {
          id: "dp-prefix",
          name: "DP",
          time: "O(n · L)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { s: "leetcode", dict: ["leet", "code"] },
          steps: [
            { id: 0, narration: "dp[i] = true if s[i:] can be broken. dp[n]=true.", variables: { dp: "['?','?','?','?','?','?','?','?','true']" }, opCount: 0 },
            { id: 1, narration: "i=4: 'code' is in dict. dp[4]=dp[8]=true.", variables: { dp: "['?','?','?','?','?','true','?','?','true']" }, pointers: { i: 4 }, highlight: [4], opCount: 1 },
            { id: 2, narration: "i=0: 'leet' is in dict. dp[0]=dp[4]=true.", variables: { dp: "['true','?','?','?','?','true','?','?','true']" }, pointers: { i: 0 }, highlight: [0], opCount: 2 },
            { id: 3, narration: "dp[0]=true. Return true.", variables: { answer: "true" }, opCount: 3, done: true },
          ],
        },
        {
          id: "bfs",
          name: "BFS on Indices",
          time: "O(n · L)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { s: "leetcode", dict: ["leet", "code"] },
          steps: [
            { id: 0, narration: "queue=[0]. Pop, try every word; if s[i:i+len] matches, push i+len.", variables: { queue: "[0]" }, opCount: 0 },
            { id: 1, narration: "i=0: 'leet' matches. Push 4.", variables: { queue: "[4]" }, opCount: 1 },
            { id: 2, narration: "i=4: 'code' matches. Push 8 (== len).", variables: { queue: "[8]" }, opCount: 2 },
            { id: 3, narration: "i=8: reached end. Return true.", variables: { answer: "true" }, opCount: 3, done: true },
          ],
        },
      ],
    },
    {
      slug: "max-profit-job-scheduling",
      title: "Maximum Profit Job Scheduling",
      difficulty: "Medium",
      status: "live",
      description: "Pick non-overlapping jobs to maximize profit.",
      problem:
        "You have `n` jobs each with `startTime[i]`, `endTime[i]`, and `profit[i]`. Choose a subset of the jobs such that no two chosen jobs overlap and the sum of profits is maximized. Return that maximum profit. Example: `startTime=[1,2,3,3], endTime=[3,4,5,6], profit=[50,10,40,70]` → 120. Edge cases: no jobs (0), single job, all jobs mutually exclusive.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def job_brute(jobs):",
          "    def rec(i, end):",
          "        if i == len(jobs): return 0",
          "        skip = rec(i + 1, end)",
          "        take = 0",
          "        if jobs[i][0] >= end:",
          "            take = jobs[i][2] + rec(i + 1, jobs[i][1])",
          "        return max(skip, take)",
          "    return rec(0, 0)",
        ],
      },
      annotations: {
        5: "Recurrence: skip the job, or take it (only if start ≥ current end).",
      },
      approaches: [
        {
          id: "dp-sorted",
          name: "DP + Binary Search",
          time: "O(n log n)",
          space: "O(n)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { jobs: [[1,3,50],[3,5,40],[6,8,70],[8,10,80]] },
          steps: [
            { id: 0, narration: "Sort jobs by end. For each i, find latest j with end[j] ≤ start[i].", variables: { sorted: "[(3,50),(5,40),(8,70),(10,80)]" }, opCount: 0 },
            { id: 1, narration: "dp[0]=50 (just job 1).", variables: { dp: "[50,40,70,80]" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "i=1 (job 50-40 end=5): latest j=0 (end=3) → dp[1]=max(40, 50+40-50)=40.", variables: { dp: "[50,40,70,80]" }, pointers: { i: 1 }, highlight: [0], opCount: 2 },
            { id: 3, narration: "i=2 (end=8): latest j=1 (end=5) → dp[2] = max(70, dp[1]+70) = 120.", variables: { dp: "[50,40,120,80]" }, pointers: { i: 2 }, highlight: [1, 2], opCount: 3 },
            { id: 4, narration: "i=3 (end=10): latest j=2 (end=8) → dp[3] = max(80, dp[2]+80) = 200.", variables: { dp: "[50,40,120,200]", answer: 200 }, pointers: { i: 3 }, highlight: [2, 3], opCount: 4, done: true },
          ],
        },
        {
          id: "interval-sweep",
          name: "Interval DP (sweep)",
          time: "O(n²)",
          space: "O(n)",
          opsEstimate: (n) => n * n,
          defaultInput: { jobs: [[1,3,50],[3,5,40],[6,8,70],[8,10,80]] },
          steps: [
            { id: 0, narration: "Process events in order: start, end. On each end, dp at that time = max profit.", variables: { dp: "[0]" }, opCount: 0 },
            { id: 1, narration: "Process events: end=3 → 50. end=5 → max(50, 40)=50. end=8 → 120. end=10 → 200.", variables: { dp: "200" }, opCount: 1, done: true },
          ],
        },
      ],
    },
    {
      slug: "paint-house",
      title: "Paint House",
      difficulty: "Medium",
      status: "live",
      description: "Paint n houses in 3 colors so no two adjacent share a color, with minimum cost.",
      problem:
        "There are `n` houses in a row, each to be painted with one of three colors: red, blue, or green. The cost of painting each house in each color is given as an `n × 3` matrix `costs`. Adjacent houses cannot be the same color. Find the minimum total cost to paint all houses. Example: `costs=[[17,2,17],[16,16,5],[14,3,19]]` → 10 (house 0 blue 2, house 1 green 5, house 2 blue 3; total 10). Edge cases: single house (cheapest color), n=1, and all three colors equally expensive.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def paint_brute(costs):",
          "    n = len(costs)",
          "    def rec(i, last):",
          "        if i == n: return 0",
          "        best = float('inf')",
          "        for c in range(3):",
          "            if c != last:",
          "                best = min(best, costs[i][c] + rec(i + 1, c))",
          "        return best",
          "    return rec(0, -1)",
        ],
      },
      annotations: {
        4: "Brute: try every color choice per house without memoization.",
      },
      approaches: [
        {
          id: "dp",
          name: "DP O(n)",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { costs: [[17,2,17],[16,16,5],[14,3,19]] },
          steps: [
            { id: 0, narration: "dp[i][c] = min cost to paint [0..i] with house i using color c.", variables: { dp: "[[17,2,17]]" }, pointers: { i: 0 }, opCount: 0 },
            { id: 1, narration: "i=1: dp[1][0] = 16 + min(dp[0][1], dp[0][2]) = 16 + 2 = 18.", variables: { dp: "[17,2,17 | 18,33,7]" }, pointers: { i: 1 }, highlight: [0, 3], opCount: 1 },
            { id: 2, narration: "dp[1][1] = 16 + min(17, 17) = 33. dp[1][2] = 5 + min(17,2) = 7.", variables: { dp: "[17,2,17 | 18,33,7]" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "i=2: dp[2][0] = 14 + min(33, 7) = 21. dp[2][1] = 3 + min(18, 7) = 10.", variables: { dp: "[17,2,17 | 18,33,7 | 21,10,29]" }, pointers: { i: 2 }, highlight: [1, 4], opCount: 3 },
            { id: 4, narration: "dp[2][2] = 19 + min(18, 33) = 37. Min total = min(21,10,37) = 10.", variables: { answer: 10 }, opCount: 4, done: true },
          ],
        },
        {
          id: "rolling",
          name: "Rolling 3 vars",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { costs: [[17,2,17],[16,16,5],[14,3,19]] },
          steps: [
            { id: 0, narration: "Keep last row's min-cost-per-color. roll on each step.", variables: { prev: "[17,2,17]" }, opCount: 0 },
            { id: 1, narration: "After row 1: min(17+16,2+16,17+16)[0]=18 etc.", variables: { prev: "[18,33,7]" }, opCount: 1 },
            { id: 2, narration: "After row 2: [21,10,37]. min = 10.", variables: { answer: 10 }, opCount: 2, done: true },
          ],
        },
      ],
    },
  ],
};