import type { Pattern } from "@/types/content";

export const dp2d: Pattern = {
  slug: "dp-2d",
  title: "2-D Dynamic Programming",
  tagline: "Grid DP, LCS, and edit distance.",
  status: "live",
  icon: "Grid3x3",
  topics: [
    {
      slug: "unique-paths",
      title: "Unique Paths",
      difficulty: "Medium",
      status: "live",
      description: "Count paths from top-left to bottom-right of an m x n grid moving only right or down.",
      problem:
        "A robot starts at the top-left corner of an m x n grid and can only move right or down. Count the number of distinct paths to the bottom-right. Example: m=3, n=7 → 28. Edge cases: m=1 or n=1 (exactly 1 path), m=n=1 (1), and very small/large grids.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def unique_paths_brute(m, n):",
          "    def rec(r, c):",
          "        if r == m - 1 or c == n - 1: return 1",
          "        if r >= m or c >= n: return 0",
          "        return rec(r + 1, c) + rec(r, c + 1)",
          "    return rec(0, 0)",
        ],
      },
      annotations: {
        1: "Brute: enumerate every path by recursion — exponential without memoization.",
      },
      approaches: [
        {
          id: "2d-dp",
          name: "2D DP",
          time: "O(m * n)",
          space: "O(m * n)",
          opsEstimate: (n) => n * n,
          defaultInput: { m: 3, n: 4 },
          steps: [
            {
              id: 0,
              narration: "dp[0][0]=1. Fill first row and first column with 1s.",
              table: [[1, 1, 1, 1], [1, 0, 0, 0], [1, 0, 0, 0]],
              variables: { row: 0, col: 0 },
              pointers: { i: 0, j: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "dp[1][1] = dp[0][1] + dp[1][0] = 1 + 1 = 2.",
              table: [[1, 1, 1, 1], [1, 2, 0, 0], [1, 0, 0, 0]],
              pointers: { i: 1, j: 1 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "dp[1][2] = dp[0][2] + dp[1][1] = 1 + 2 = 3.",
              table: [[1, 1, 1, 1], [1, 2, 3, 0], [1, 0, 0, 0]],
              pointers: { i: 1, j: 2 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "dp[1][3] = dp[0][3] + dp[1][2] = 1 + 3 = 4.",
              table: [[1, 1, 1, 1], [1, 2, 3, 4], [1, 0, 0, 0]],
              pointers: { i: 1, j: 3 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "dp[2][1] = dp[1][1] + dp[2][0] = 2 + 1 = 3.",
              table: [[1, 1, 1, 1], [1, 2, 3, 4], [1, 3, 0, 0]],
              pointers: { i: 2, j: 1 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "dp[2][2] = dp[1][2] + dp[2][1] = 3 + 3 = 6.",
              table: [[1, 1, 1, 1], [1, 2, 3, 4], [1, 3, 6, 0]],
              pointers: { i: 2, j: 2 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "dp[2][3] = dp[1][3] + dp[2][2] = 4 + 6 = 10.",
              table: [[1, 1, 1, 1], [1, 2, 3, 4], [1, 3, 6, 10]],
              pointers: { i: 2, j: 3 },
              opCount: 6,
              done: true,
            },
          ],
        },
        {
          id: "combinatorics",
          name: "Combinatorics (nCr)",
          time: "O(m + n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { m: 3, n: 4 },
          steps: [
            {
              id: 0,
              narration: "Total moves: (m-1) downs + (n-1) rights = 2 + 3 = 5.",
              variables: { moves: 5, downs: 2, rights: 3 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Answer = C(5, 2) — choose where the 2 downs go.",
              variables: { formula: "C(5,2)" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "C(5,2) = 5! / (2! * 3!) = 120 / (2*6) = 10.",
              variables: { ans: 10 },
              opCount: 2,
              done: true,
            },
          ],
        },
        {
          id: "space-opt",
          name: "Space-Optimized 1D",
          time: "O(m * n)",
          space: "O(n)",
          opsEstimate: (n) => n * n,
          defaultInput: { m: 3, n: 4 },
          steps: [
            {
              id: 0,
              narration: "row = [1,1,1,1]. First row all 1s.",
              variables: { row: "[1,1,1,1]" },
              pointers: { rowIdx: 1 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "row[1] += row[0] = 1 + 1 = 2.",
              variables: { row: "[1,2,1,1]" },
              pointers: { rowIdx: 1, col: 1 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "row[2] += row[1] = 1 + 2 = 3.",
              variables: { row: "[1,2,3,1]" },
              pointers: { rowIdx: 1, col: 2 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "row[3] += row[2] = 1 + 3 = 4.",
              variables: { row: "[1,2,3,4]" },
              pointers: { rowIdx: 1, col: 3 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "row[1] += row[0] = 2 + 1 = 3.",
              variables: { row: "[1,3,3,4]" },
              pointers: { rowIdx: 2, col: 1 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "row[2] += row[1] = 3 + 3 = 6.",
              variables: { row: "[1,3,6,4]" },
              pointers: { rowIdx: 2, col: 2 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "row[3] += row[2] = 4 + 6 = 10. Answer = 10.",
              variables: { row: "[1,3,6,10]" },
              pointers: { rowIdx: 2, col: 3 },
              opCount: 6,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "longest-common-subsequence",
      title: "Longest Common Subsequence",
      difficulty: "Medium",
      status: "live",
      description: "Find the length of the longest common subsequence of two strings.",
      problem:
        "Given two strings `text1` and `text2`, return the length of their longest common subsequence (LCS). A subsequence is derived by deleting some characters without changing the order. Example: `'abcde'` and `'ace'` → 3. Edge cases: either string empty (length 0), both single char match (1), no common chars (0).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def lcs_brute(a, b):",
          "    def rec(i, j):",
          "        if i == 0 or j == 0: return 0",
          "        if a[i - 1] == b[j - 1]:",
          "            return 1 + rec(i - 1, j - 1)",
          "        return max(rec(i - 1, j), rec(i, j - 1))",
          "    return rec(len(a), len(b))",
        ],
      },
      annotations: {
        3: "Brute: naive recursion without memoization — exponential blowup.",
      },
      approaches: [
        {
          id: "2d-dp",
          name: "2D DP",
          time: "O(m * n)",
          space: "O(m * n)",
          opsEstimate: (n) => n * n,
          defaultInput: { s1: "abcde", s2: "ace" },
          steps: [
            {
              id: 0,
              narration: "Build (m+1) x (n+1) table. Row 0 and Col 0 are all 0.",
              table: [
                ["", "a", "c", "e"],
                ["a", 0, 0, 0],
                ["b", 0, 0, 0],
                ["c", 0, 0, 0],
                ["d", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 0, j: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=1 ('a'), j=1 ('a'): match → dp[1][1] = dp[0][0]+1 = 1.",
              table: [
                ["", "a", "c", "e"],
                ["a", 1, 0, 0],
                ["b", 0, 0, 0],
                ["c", 0, 0, 0],
                ["d", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 1, j: 1 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=1, j=2 ('c'): no match → dp[1][2] = max(dp[0][2], dp[1][1]) = max(0,1) = 1.",
              table: [
                ["", "a", "c", "e"],
                ["a", 1, 1, 0],
                ["b", 0, 0, 0],
                ["c", 0, 0, 0],
                ["d", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 1, j: 2 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=1, j=3 ('e'): no match → dp[1][3] = max(dp[0][3], dp[1][2]) = 1.",
              table: [
                ["", "a", "c", "e"],
                ["a", 1, 1, 1],
                ["b", 0, 0, 0],
                ["c", 0, 0, 0],
                ["d", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 1, j: 3 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=2 ('b'), j=1 ('a'): no match → dp[2][1] = max(0, 1) = 1.",
              table: [
                ["", "a", "c", "e"],
                ["a", 1, 1, 1],
                ["b", 1, 0, 0],
                ["c", 0, 0, 0],
                ["d", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 2, j: 1 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=3 ('c'), j=2 ('c'): match → dp[3][2] = dp[2][1]+1 = 2.",
              table: [
                ["", "a", "c", "e"],
                ["a", 1, 1, 1],
                ["b", 1, 1, 1],
                ["c", 1, 2, 0],
                ["d", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 3, j: 2 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "i=5 ('e'), j=3 ('e'): match → dp[5][3] = dp[4][2]+1 = 3.",
              table: [
                ["", "a", "c", "e"],
                ["a", 1, 1, 1],
                ["b", 1, 1, 1],
                ["c", 1, 2, 2],
                ["d", 1, 2, 2],
                ["e", 1, 2, 3],
              ],
              pointers: { i: 5, j: 3 },
              opCount: 6,
              done: true,
            },
          ],
        },
        {
          id: "space-opt",
          name: "Space-Optimized (2 rows)",
          time: "O(m * n)",
          space: "O(n)",
          opsEstimate: (n) => n * n,
          defaultInput: { s1: "abcde", s2: "ace" },
          steps: [
            {
              id: 0,
              narration: "prev = [0,0,0] (n+1). prev[j] = dp[i-1][j].",
              variables: { prev: "[0,0,0]", curr: "[0,0,0]" },
              pointers: { i: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=1 ('a'): scan j. a==a → curr[1]=prev[0]+1=1.",
              variables: { prev: "[0,0,0]", curr: "[1,1,1]" },
              pointers: { i: 1, j: 1 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=2 ('b'): b!=a,!=c → curr[j]=max(prev[j],curr[j-1]). curr=[1,1,1].",
              variables: { prev: "[0,0,0]", curr: "[1,1,1]" },
              pointers: { i: 2, j: 3 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=3 ('c'): c==c → curr[2]=prev[1]+1=2. Roll prev←curr.",
              variables: { prev: "[1,1,1]", curr: "[1,1,2]" },
              pointers: { i: 3, j: 2 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=4 ('d'): no matches. curr=[1,2,2]. Roll.",
              variables: { prev: "[1,1,2]", curr: "[1,2,2]" },
              pointers: { i: 4, j: 3 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=5 ('e'): e==e → curr[3]=prev[2]+1=3. Answer = 3.",
              variables: { prev: "[1,2,2]", curr: "[1,2,3]" },
              pointers: { i: 5, j: 3 },
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "edit-distance",
      title: "Edit Distance",
      difficulty: "Hard",
      status: "live",
      description: "Convert word1 into word2 using insert, delete, or replace. Minimize the number of operations.",
      problem:
        "Given two strings `word1` and `word2`, return the minimum number of operations required to convert `word1` to `word2`. Allowed operations: insert, delete, or replace a character. Example: `'horse'→'ros'` → 3. Edge cases: identical strings (0), one string is empty (length of other), single-character transforms.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def edit_brute(a, b):",
          "    def rec(i, j):",
          "        if i == 0: return j",
          "        if j == 0: return i",
          "        if a[i - 1] == b[j - 1]:",
          "            return rec(i - 1, j - 1)",
          "        return 1 + min(rec(i - 1, j), rec(i, j - 1), rec(i - 1, j - 1))",
          "    return rec(len(a), len(b))",
        ],
      },
      annotations: {
        7: "Recurrence covers replace (i-1,j-1), delete (i-1,j), insert (i,j-1).",
      },
      approaches: [
        {
          id: "2d-dp",
          name: "2D DP",
          time: "O(m * n)",
          space: "O(m * n)",
          opsEstimate: (n) => n * n,
          defaultInput: { s1: "horse", s2: "ros" },
          steps: [
            {
              id: 0,
              narration: "Build table. Row i=dp[0..i], Col j=dp[0..j]. Fill base: row 0 = [0,1,2,3], col 0 = [0,1,2,3,4,5].",
              table: [
                ["", "r", "o", "s"],
                ["h", 0, 0, 0],
                ["o", 0, 0, 0],
                ["r", 0, 0, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              variables: { row0: "[0,1,2,3]", col0: "[0,1,2,3,4,5]" },
              pointers: { i: 0, j: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "dp[1][1]: h!=r. min(top,left,diag)=min(1,1,0)=0. dp=0+1=1.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 0, 0],
                ["o", 0, 0, 0],
                ["r", 0, 0, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 1, j: 1 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "dp[1][2]: h!=o. min(top=2,left=1,diag=1)=1. dp=2.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 0],
                ["o", 0, 0, 0],
                ["r", 0, 0, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 1, j: 2 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "dp[1][3]: h!=s. min(3,2,2)=2. dp=3.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 0, 0, 0],
                ["r", 0, 0, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 1, j: 3 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "dp[2][1]: o!=r. min(top=1,left=2,diag=1)=1. dp=2.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 0, 0],
                ["r", 0, 0, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 2, j: 1 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "dp[2][2]: o==o MATCH → diag+1 = 1+1 = 2.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 0],
                ["r", 0, 0, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 2, j: 2 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "dp[2][3]: o!=s. min(top=3,left=1,diag=2)=1. dp=2.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 0, 0, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 2, j: 3 },
              opCount: 6,
            },
            {
              id: 7,
              narration: "dp[3][1]: r==r MATCH → diag+1 = 2+1 = 3.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 0, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 3, j: 1 },
              opCount: 7,
            },
            {
              id: 8,
              narration: "dp[3][2]: r!=o. min(top=1,left=3,diag=3)=1. dp=2.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 2, 0],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 3, j: 2 },
              opCount: 8,
            },
            {
              id: 9,
              narration: "dp[3][3]: r!=s. min(top=2,left=2,diag=2)=2. dp=3.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 2, 3],
                ["s", 0, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 3, j: 3 },
              opCount: 9,
            },
            {
              id: 10,
              narration: "dp[4][1]: s!=r. min(top=3,left=4,diag=3)=3. dp=4.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 2, 3],
                ["s", 4, 0, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 4, j: 1 },
              opCount: 10,
            },
            {
              id: 11,
              narration: "dp[4][2]: s!=o. min(top=2,left=4,diag=4)=2. dp=3.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 2, 3],
                ["s", 4, 3, 0],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 4, j: 2 },
              opCount: 11,
            },
            {
              id: 12,
              narration: "dp[4][3]: s==s MATCH → diag+1 = 2+1 = 3.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 2, 3],
                ["s", 4, 3, 2],
                ["e", 0, 0, 0],
              ],
              pointers: { i: 4, j: 3 },
              opCount: 12,
            },
            {
              id: 13,
              narration: "dp[5][1]: e!=r. min(top=4,left=5,diag=4)=4. dp=5.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 2, 3],
                ["s", 4, 3, 2],
                ["e", 5, 0, 0],
              ],
              pointers: { i: 5, j: 1 },
              opCount: 13,
            },
            {
              id: 14,
              narration: "dp[5][2]: e!=o. min(top=3,left=5,diag=5)=3. dp=4.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 2, 3],
                ["s", 4, 3, 2],
                ["e", 5, 4, 0],
              ],
              pointers: { i: 5, j: 2 },
              opCount: 14,
            },
            {
              id: 15,
              narration: "dp[5][3]: e!=s. min(top=2,left=4,diag=4)=2. dp=3.",
              table: [
                ["", "r", "o", "s"],
                ["h", 1, 2, 3],
                ["o", 2, 1, 2],
                ["r", 3, 2, 3],
                ["s", 4, 3, 2],
                ["e", 5, 4, 3],
              ],
              pointers: { i: 5, j: 3 },
              opCount: 15,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "maximal-square",
      title: "Maximal Square",
      difficulty: "Medium",
      status: "live",
      description: "Find the largest square of 1s in a binary matrix.",
      problem:
        "Given an m x n binary matrix filled with 0s and 1s, find the largest square containing only 1s and return its area. Example: `[['1','0','1','0','0'],['1','0','1','1','1'],['1','1','1','1','1'],['1','0','0','1','0']]` → 4. Edge cases: all zeros (answer 0), single 1 cell (answer 1), and full matrix of 1s.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def maximal_square_brute(matrix):",
          "    rows, cols = len(matrix), len(matrix[0])",
          "    best = 0",
          "    for r in range(rows):",
          "        for c in range(cols):",
          "            for k in range(1, min(rows - r, cols - c) + 1):",
          "                # check if k×k square is all 1s",
          "                ok = all(matrix[r+i][c+j] == '1' for i in range(k) for j in range(k))",
          "                if ok: best = max(best, k*k)",
          "    return best",
        ],
      },
      annotations: {
        5: "Brute: try every square size at every top-left corner — O((mn)²).",
      },
      approaches: [
        {
          id: "2d-dp",
          name: "2D DP",
          time: "O(m · n)",
          space: "O(m · n)",
          opsEstimate: (n) => n * n,
          defaultInput: { matrix: [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]] },
          steps: [
            { id: 0, narration: "dp[i][j] = side length of largest square ending at (i,j).", variables: { dp: "[[0,0,0,0,0],[0,0,0,0,0],...]" }, pointers: { r: 0, c: 0 }, opCount: 0 },
            { id: 1, narration: "(0,0): '1' → dp=1. (0,2): '1' → dp=1. (1,0): '1' → dp=1.", variables: { dp: "[[1,0,1,0,0],[1,0,1,1,1],...]" }, pointers: { r: 1, c: 0 }, highlight: [0, 5], opCount: 1 },
            { id: 2, narration: "(1,3): matrix[1][3]='1' and top=1,left=1,diag=0 → dp = 0+1 = 1. (2,1): '1' with dp = 1.", variables: { dp: "[[1,0,1,0,0],[1,0,1,1,1],[1,1,1,1,1]...]" }, pointers: { r: 2, c: 1 }, highlight: [7, 12], opCount: 2 },
            { id: 3, narration: "(2,2): 1+min(top=0,left=1,diag=1)=1. (2,4): 1.", variables: { dp: "..." }, pointers: { r: 2, c: 2 }, opCount: 3 },
            { id: 4, narration: "(3,0): '1'. (3,2): '0'. (3,3): '1' → dp = 1.", variables: { dp: "..." }, pointers: { r: 3, c: 0 }, opCount: 4 },
            { id: 5, narration: "max(dp) = 2 at (2,3). Area = 4.", variables: { maxSide: 2, answer: 4 }, opCount: 5, done: true },
          ],
        },
        {
          id: "space-opt",
          name: "Space-Optimized (1 row)",
          time: "O(m · n)",
          space: "O(n)",
          opsEstimate: (n) => n * n,
          defaultInput: { matrix: [["1","0","1","0","0"],["1","0","1","1","1"],["1","1","1","1","1"],["1","0","0","1","0"]] },
          steps: [
            { id: 0, narration: "Keep 1 row of dp; carry 'topLeft' value separately for the diagonal.", variables: { row: "[0,0,0,0,0]", topLeft: 0 }, pointers: { r: 0 }, opCount: 0 },
            { id: 1, narration: "Walk row, compute in-place. Same recurrence: min(topLeft, row[i-1], row[i]) + 1.", variables: { row: "[1,0,1,0,0]" }, opCount: 1 },
            { id: 2, narration: "After row 3: max side still 2. Area = 4.", variables: { answer: 4 }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "min-window-subsequence",
      title: "Minimum Window Subsequence",
      difficulty: "Hard",
      status: "live",
      description: "Find the shortest substring of S that contains T as a subsequence.",
      problem:
        "Given strings `S` and `T`, return the minimum-length substring of `S` such that `T` is a subsequence of it. If there is no such window in `S`, return ''. Example: `S='abcdebdde', T='bde'` → `'bcde'`. Edge cases: T not a subsequence at all (return ''), T longer than S (return ''), T is a single character.",
      askedAt: ["Amazon", "Google", "Microsoft"],
      code: {
        lang: "python",
        lines: [
          "def min_window_subseq_brute(S, T):",
          "    def is_sub(sub, t):",
          "        i = 0",
          "        for c in sub:",
          "            if i < len(t) and c == t[i]: i += 1",
          "        return i == len(t)",
          "    n = len(S)",
          "    best = ''",
          "    for i in range(n):",
          "        for j in range(i, n + 1):",
          "            if is_sub(S[i:j], T) and (best == '' or j - i < len(best)):",
          "                best = S[i:j]",
          "    return best",
        ],
      },
      annotations: {
        8: "Brute: try every substring of S — O(n³) when combined with the subsequence check.",
      },
      approaches: [
        {
          id: "dp-match",
          name: "DP Match Forward/Reverse",
          time: "O(m · n)",
          space: "O(m · n)",
          opsEstimate: (n) => n * n,
          defaultInput: { S: "abcdebdde", T: "bde" },
          steps: [
            { id: 0, narration: "Forward DP: longest prefix of T that is a subsequence of S ending at each position.", variables: { dpF: "{}" }, opCount: 0 },
            { id: 1, narration: "Reverse DP: longest suffix of T that is a subsequence of S starting at each position.", variables: { dpR: "{}" }, opCount: 1 },
            { id: 2, narration: "At each split between i and i+1, both sides must cover full T.", variables: { best: "'bcde'" }, opCount: 2 },
            { id: 3, narration: "Scan all splits to find the minimum-length window. Answer = 'bcde'.", variables: { answer: "'bcde'" }, opCount: 3, done: true },
          ],
        },
        {
          id: "two-pointer",
          name: "Two-Pointer Sweep",
          time: "O(m · n)",
          space: "O(1)",
          opsEstimate: (n) => n * n,
          defaultInput: { S: "abcdebdde", T: "bde" },
          steps: [
            { id: 0, narration: "Sweep S with pointers i (in S) and j (in T). Each time we match j, advance j.", variables: { i: 0, j: 0 }, pointers: { i: 0 }, opCount: 0 },
            { id: 1, narration: "When j == len(T): walk S backwards from i to find the start of the window.", variables: { i: 4, j: 3 }, opCount: 1 },
            { id: 2, narration: "Found window S[1:5] = 'bcde'. Update best.", variables: { best: "'bcde'" }, opCount: 2 },
            { id: 3, narration: "Resume sweep from 1 and look for shorter windows.", variables: { answer: "'bcde'" }, opCount: 3, done: true },
          ],
        },
      ],
    },
  ],
};