import type { Pattern } from "@/types/content";

export const graphs: Pattern = {
  slug: "graphs",
  title: "Graphs",
  tagline: "BFS, DFS, Dijkstra, Union-Find.",
  status: "live",
  icon: "Share2",
  topics: [
    {
      slug: "num-islands",
      title: "Number of Islands",
      difficulty: "Medium",
      status: "live",
      description:
        "Given a 2-D grid of '1's (land) and '0's (water), count the number of distinct islands.",
      problem:
        "Given an m x n 2D grid of '1's (land) and '0's (water), return the number of islands. An island is surrounded by water and is formed by connecting adjacent lands horizontally or vertically. You may assume all four edges of the grid are surrounded by water. Example: `[['1','1','0','0','0'],['1','1','0','0','0'],['0','0','1','0','0'],['0','0','0','1','1']]` → 3. Edge cases: empty grid (0), all land (1), all water (0), and diagonal-only land masses.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def num_islands_brute(grid):",
          "    if not grid: return 0",
          "    count = 0",
          "    visited = [[False] * len(grid[0]) for _ in range(len(grid))]",
          "    for i in range(len(grid)):",
          "        for j in range(len(grid[0])):",
          "            if grid[i][j] == '1' and not visited[i][j]:",
          "                count += 1",
          "                bfs_mark(grid, visited, i, j)",
          "    return count",
        ],
      },
      annotations: {
        6: "Same BFS/DFS flood fill — calling out as the 'brute' baseline without bit-packing tricks.",
      },
      approaches: [
        {
          id: "dfs",
          name: "DFS Flood Fill",
          time: "O(n*m)",
          space: "O(n*m) call stack",
          opsEstimate: (n) => n * n,
          defaultInput: { grid: [[1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 1]] },
          steps: [
            {
              id: 0,
              narration: "Scan cell-by-cell. On first '1', start a DFS that flips every reachable '1' to '0'. Count +1.",
              variables: { grid: "1 1 0 0 0 | 1 1 0 0 0 | 0 0 1 0 0 | 0 0 0 1 1", islands: 0 },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "(0,0) is land. DFS sink: mark (0,0),(0,1),(1,0),(1,1). All four neighbors are connected.",
              variables: { visited: "{(0,0),(0,1),(1,0),(1,1)}", islands: 1 },
              highlight: [0, 1, 5, 6],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Keep scanning. (2,2) is a fresh '1'. DFS from (2,2) — single cell, no land neighbors.",
              variables: { visited: "{(0,0),(0,1),(1,0),(1,1),(2,2)}", islands: 2 },
              highlight: [12],
              opCount: 2,
            },
            {
              id: 3,
              narration: "(3,3) is a fresh '1'. DFS expands to (3,3),(3,4). Two connected cells.",
              variables: { visited: "{…,(3,3),(3,4)}", islands: 3 },
              highlight: [18, 19],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Scan ends. 3 islands found.",
              variables: { answer: "3", islands: 3 },
              opCount: 4,
              done: true,
            },
          ],
        },
        {
          id: "bfs",
          name: "BFS Flood Fill",
          time: "O(n*m)",
          space: "O(min(n,m)) queue",
          opsEstimate: (n) => n * n,
          defaultInput: { grid: [[1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 1]] },
          steps: [
            {
              id: 0,
              narration: "Scan. On each fresh '1', enqueue and pop until empty, marking visited. Count +1.",
              variables: { grid: "1 1 0 0 0 | 1 1 0 0 0 | 0 0 1 0 0 | 0 0 0 1 1", islands: 0 },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Start BFS at (0,0). Queue=[(0,0)]. Pop, mark visited, push 4-connected land neighbors.",
              variables: { queue: "[]", visited: "{(0,0),(0,1),(1,0),(1,1)}", islands: 1 },
              highlight: [0, 1, 5, 6],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Continue scanning. Hit (2,2). BFS: only (2,2) itself is land. islands=2.",
              variables: { visited: "{…,(2,2)}", islands: 2 },
              highlight: [12],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Hit (3,3). BFS: (3,3),(3,4) connect. islands=3.",
              variables: { visited: "{…,(3,3),(3,4)}", islands: 3 },
              highlight: [18, 19],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Scan done. Answer = 3.",
              variables: { answer: "3", islands: 3 },
              opCount: 4,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "clone-graph",
      title: "Clone Graph",
      difficulty: "Medium",
      status: "live",
      description:
        "Deep-copy an undirected connected graph. Each node has an int value and a list of neighbors.",
      problem:
        "Given a reference to a node in a connected undirected graph, return a deep copy (clone) of the graph. Each node has an int value and a list of `Node` neighbors. The test will compare the returned graph's structure and values against the original. Example: a graph 1↔2↔3↔4 (cycle) cloned back to itself with the same shape. Edge cases: single-node graph (return one cloned node), disconnected components (cover all), and self-loops (a node points to itself).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def clone_graph_brute(node):",
          "    if not node: return None",
          "    nodes_old = []",
          "    def visit(n):",
          "        if n in nodes_old: return",
          "        nodes_old.append(n)",
          "        for nb in n.neighbors: visit(nb)",
          "    visit(node)",
          "    nodes_new = [Node(n.val) for n in nodes_old]",
          "    for old, new in zip(nodes_old, nodes_new):",
          "        for nb in old.neighbors:",
          "            new.neighbors.append(nodes_new[nodes_old.index(nb)])",
          "    return nodes_new[0]",
        ],
      },
      annotations: {
        1: "Brute approach: index lookup by list.index is O(n) per neighbor — works but slow.",
      },
      approaches: [
        {
          id: "dfs-hash",
          name: "DFS with Hash Map",
          time: "O(V+E)",
          space: "O(V)",
          opsEstimate: (n) => n,
          defaultInput: { nodes: 4, adj: "1↔2,1↔4,2↔3,3↔4" },
          steps: [
            {
              id: 0,
              narration: "Map original node → cloned node. If a clone exists, reuse it; otherwise create and recurse on neighbors.",
              variables: { map: "{}", stack: "[1]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Visit 1. Create clone 1'. Recurse on neighbors 2 and 4.",
              variables: { map: "{1→1'}", stack: "[1',2,4]" },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Visit 2. Create clone 2'. Recurse on neighbors 1 and 3.",
              variables: { map: "{1→1', 2→2'}", stack: "[2',1,3]" },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Visit 1 (original). Clone 1' exists in map → wire 2'.neighbors += [1']. Pop.",
              variables: { map: "{1→1', 2→2', 1→1' (reused)}", stack: "[3]" },
              highlight: [1],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Visit 3. Create clone 3'. Recurse on neighbors 2 and 4.",
              variables: { map: "{1→1', 2→2', 3→3'}", stack: "[3',2,4]" },
              highlight: [2],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Visit 2 — clone exists, reuse → 3'.neighbors += [2']. Visit 4 — clone exists, reuse. Wire 4'.neighbors, 1'.neighbors.",
              variables: { map: "{1→1', 2→2', 3→3', 4→4'}", answer: "1'…" },
              highlight: [0, 1, 2, 3],
              opCount: 5,
              done: true,
            },
          ],
        },
        {
          id: "bfs-hash",
          name: "BFS with Hash Map",
          time: "O(V+E)",
          space: "O(V)",
          opsEstimate: (n) => n,
          defaultInput: { nodes: 4, adj: "1↔2,1↔4,2↔3,3↔4" },
          steps: [
            {
              id: 0,
              narration: "Map original → clone. Enqueue start node 1 with its clone 1'.",
              variables: { map: "{1→1'}", queue: "[1]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Pop 1. For each neighbor (2, 4), create clones if missing and wire 1'.neighbors.",
              variables: { map: "{1→1', 2→2', 4→4'}", queue: "[2,4]" },
              highlight: [0, 1, 3],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Pop 2. Neighbors 1 (clone exists, reuse) and 3 (new, create 3').",
              variables: { map: "{1→1', 2→2', 3→3', 4→4'}", queue: "[4,3]" },
              highlight: [1, 2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Pop 4. Neighbors 1 (exists) and 3 (exists) → reuse both.",
              variables: { map: "{1→1', 2→2', 3→3', 4→4'}", queue: "[3]" },
              highlight: [3],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Pop 3. Neighbors 2 (exists) and 4 (exists) → wire and done.",
              variables: { map: "{1→1', 2→2', 3→3', 4→4'}", answer: "1'…" },
              highlight: [0, 1, 2, 3],
              opCount: 4,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "course-schedule",
      title: "Course Schedule",
      difficulty: "Medium",
      status: "live",
      description:
        "Given n courses and prerequisites, decide if all courses can be finished (i.e., the directed graph has no cycle).",
      problem:
        "There are n courses labeled 0 to n-1. Some courses may have prerequisites (a list of pairs (a, b) means you must take course a before course b). Return `true` if it is possible to finish all courses, else `false` (a cycle exists). Example: `n=2, prereqs=[[1,0]]` → true; `n=2, prereqs=[[1,0],[0,1]]` → false. Edge cases: no prerequisites (always true), self-loop, and many prerequisites.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def can_finish_brute(n, edges):",
          "    from collections import defaultdict",
          "    g = defaultdict(list)",
          "    for a, b in edges: g[b].append(a)",
          "    color = [0] * n",
          "    def dfs(u):",
          "        if color[u] == 1: return False",
          "        if color[u] == 2: return True",
          "        color[u] = 1",
          "        for v in g[u]:",
          "            if not dfs(v): return False",
          "        color[u] = 2",
          "        return True",
          "    return all(dfs(i) for i in range(n))",
        ],
      },
      annotations: {
        9: "3-color DFS — same as 'smart' version. Listed as 'brute' because it doesn't use Kahn's algorithm.",
      },
      approaches: [
        {
          id: "dfs-3color",
          name: "DFS with cycle detection (3-color)",
          time: "O(V+E)",
          space: "O(V)",
          opsEstimate: (n) => n,
          defaultInput: { n: 4, edges: [[1, 0], [2, 1], [3, 2], [1, 3]] },
          steps: [
            {
              id: 0,
              narration: "Color nodes: 0=white(unvisited), 1=gray(in stack), 2=black(done). A cycle exists if we hit a gray neighbor.",
              variables: { color: "{0:W,1:W,2:W,3:W}", cycle: "false" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "DFS(0): mark 0 gray, visit its only prereq — none. Mark 0 black.",
              variables: { color: "{0:B,1:W,2:W,3:W}", stack: "[0]" },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "DFS(1): gray. Visit prereq 0 — black, skip. Mark 1 black.",
              variables: { color: "{0:B,1:B,2:W,3:W}", stack: "[1]" },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "DFS(2): gray. Visit prereq 1 — black, skip. Mark 2 black.",
              variables: { color: "{0:B,1:B,2:B,3:W}", stack: "[2]" },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "DFS(3): gray. Visit prereq 2 — black. But 3 also has prereq 1. 1 is BLACK (visited earlier in this DFS path? No, current stack is just [3]). Wait — 1 was already blackened when path was 0→1. Now 3→1: 1 is black, skip. Mark 3 black. No cycle.",
              variables: { color: "{0:B,1:B,2:B,3:B}", stack: "[3]" },
              highlight: [3],
              opCount: 4,
              done: true,
            },
          ],
        },
        {
          id: "kahn",
          name: "BFS (Kahn's algorithm)",
          time: "O(V+E)",
          space: "O(V)",
          opsEstimate: (n) => n,
          defaultInput: { n: 4, edges: [[1, 0], [2, 1], [3, 2], [1, 3]] },
          steps: [
            {
              id: 0,
              narration: "Compute in-degrees. Course i needs prereqs[i] courses. Start with in-degree 0.",
              variables: { indeg: "{0:0, 1:2, 2:1, 3:1}", queue: "[0]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Pop 0. It's a prereq of 1 → indeg[1]=1. Decrement; not zero yet.",
              variables: { indeg: "{0:0, 1:1, 2:1, 3:1}", queue: "[]", visited: 1 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Queue empty but unvisited remain. This means the remaining nodes are in a cycle (1↔3). Cannot finish all courses.",
              variables: { indeg: "{0:0, 1:1, 2:1, 3:1}", visited: 1, answer: "false" },
              highlight: [1, 3],
              opCount: 2,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "course-schedule-ii",
      title: "Course Schedule II",
      difficulty: "Medium",
      status: "live",
      description: "Return a valid course order to take all courses, or [] if impossible.",
      problem:
        "There are n courses labeled 0 to n-1, and a list of prerequisite pairs. Return any valid order to take all courses. If no such order exists (cycle), return an empty array. Example: n=4, prereqs=[[1,0],[2,0],[3,1],[3,2]] → [0,1,2,3] or [0,2,1,3]. Edge cases: no prerequisites (return any order), self-loop (return []), and disconnected subgraphs.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def find_order_brute(n, edges):",
          "    from itertools import permutations",
          "    for perm in permutations(range(n)):",
          "        idx = {c: i for i, c in enumerate(perm)}",
          "        if all(idx[a] < idx[b] for a, b in edges):",
          "            return list(perm)",
          "    return []",
        ],
      },
      annotations: {
        2: "Brute: try every permutation — infeasible for n≥9.",
      },
      approaches: [
        {
          id: "kahn-order",
          name: "Kahn + Order",
          time: "O(V + E)",
          space: "O(V)",
          opsEstimate: (n) => n,
          defaultInput: { n: 4, edges: [[1,0],[2,0],[3,1],[3,2]] },
          steps: [
            { id: 0, narration: "indeg = {0:0, 1:1, 2:1, 3:2}. queue=[0]. order=[].", variables: { indeg: "{0:0,1:1,2:1,3:2}", queue: "[0]", order: "[]" }, pointers: { i: 0 }, opCount: 0 },
            { id: 1, narration: "Pop 0. order=[0]. neighbors: 1,2. indeg[1]=0, indeg[2]=0. Enqueue.", variables: { indeg: "{0:0,1:0,2:0,3:2}", queue: "[1,2]", order: "[0]" }, pointers: { i: 0 }, highlight: [0], opCount: 1 },
            { id: 2, narration: "Pop 1. order=[0,1]. indeg[3]=1.", variables: { indeg: "{...,3:1}", queue: "[2]", order: "[0,1]" }, pointers: { i: 1 }, highlight: [1], opCount: 2 },
            { id: 3, narration: "Pop 2. order=[0,1,2]. indeg[3]=0. Enqueue 3.", variables: { indeg: "{3:0}", queue: "[3]", order: "[0,1,2]" }, pointers: { i: 2 }, highlight: [2], opCount: 3 },
            { id: 4, narration: "Pop 3. order=[0,1,2,3]. Queue empty. Done.", variables: { order: "[0,1,2,3]", answer: "[0,1,2,3]" }, pointers: { i: 3 }, highlight: [3], opCount: 4, done: true },
          ],
        },
        {
          id: "dfs-postorder",
          name: "DFS Postorder",
          time: "O(V + E)",
          space: "O(V)",
          opsEstimate: (n) => n,
          defaultInput: { n: 4, edges: [[1,0],[2,0],[3,1],[3,2]] },
          steps: [
            { id: 0, narration: "DFS from each node; push to stack on completion. Reverse stack = topological order.", variables: { stack: "[]" }, opCount: 0 },
            { id: 1, narration: "DFS(0): visit 0 → DFS(1) → DFS(3) (base). Push 3,2,1,0.", variables: { stack: "[3,2,1,0]" }, opCount: 1 },
            { id: 2, narration: "Reverse: [0,1,2,3].", variables: { order: "[0,1,2,3]" }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "network-delay-time",
      title: "Network Delay Time",
      difficulty: "Medium",
      status: "live",
      description: "Find the time for a signal sent from k to reach all nodes in a weighted graph.",
      problem:
        "You are given a network of n nodes, labeled 1 to n. You are also given times, a list of travel times as directed edges `times[i] = [u, v, w]` where u→v takes w time. Send a signal from node k. Return the minimum time it takes for all n nodes to receive the signal. If impossible, return -1. Example: `times=[[2,1,1],[2,3,1],[3,4,1]], n=4, k=2` → 2. Edge cases: unreachable node (return -1), isolated nodes, and single-node graph.",
      askedAt: ["Amazon", "Google", "Microsoft", "Meta"],
      code: {
        lang: "python",
        lines: [
          "def network_delay_brute(times, n, k):",
          "    INF = float('inf')",
          "    dist = [INF] * (n + 1)",
          "    dist[k] = 0",
          "    for _ in range(n - 1):",
          "        updated = False",
          "        for u, v, w in times:",
          "            if dist[u] + w < dist[v]:",
          "                dist[v] = dist[u] + w",
          "                updated = True",
          "        if not updated: break",
          "    mx = max(dist[i] for i in range(1, n + 1))",
          "    return mx if mx != INF else -1",
        ],
      },
      annotations: {
        3: "Bellman-Ford without priority queue — O(V·E), fine for small graphs.",
      },
      approaches: [
        {
          id: "dijkstra",
          name: "Dijkstra (min-heap)",
          time: "O((V + E) log V)",
          space: "O(V + E)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { n: 4, k: 2, times: [[2,1,1],[2,3,1],[3,4,1]] },
          steps: [
            { id: 0, narration: "dist = [∞,∞,0,∞,∞]. Push (0, k=2).", variables: { dist: "[∞,∞,0,∞,∞]", heap: "[(0,2)]" }, pointers: { u: 2 }, opCount: 0 },
            { id: 1, narration: "Pop (0,2). For each edge 2→1 (w=1) and 2→3 (w=1): relax.", variables: { dist: "[∞,1,0,1,∞]", heap: "[(1,1),(1,3)]" }, highlight: [0, 1], opCount: 1 },
            { id: 2, narration: "Pop (1,1). No outgoing edges. dist[1]=1.", variables: { dist: "[∞,1,0,1,∞]", heap: "[(1,3)]" }, pointers: { u: 1 }, highlight: [1], opCount: 2 },
            { id: 3, narration: "Pop (1,3). Relax 3→4 (w=1). dist[4]=2. Push (2,4).", variables: { dist: "[∞,1,0,1,2]", heap: "[(2,4)]" }, highlight: [2], opCount: 3 },
            { id: 4, narration: "Pop (2,4). Done.", variables: { dist: "[∞,1,0,1,2]", answer: 2 }, highlight: [3], opCount: 4, done: true },
          ],
        },
        {
          id: "floyd-warshall",
          name: "Floyd–Warshall",
          time: "O(V³)",
          space: "O(V²)",
          opsEstimate: (n) => n * n * n,
          defaultInput: { n: 4, k: 2, times: [[2,1,1],[2,3,1],[3,4,1]] },
          steps: [
            { id: 0, narration: "Initialize dist matrix with direct edge weights, INF elsewhere.", variables: { dist: "INF except edges=1" }, opCount: 0 },
            { id: 1, narration: "Try each intermediate k: dist[i][j] = min(dist[i][j], dist[i][k]+dist[k][j]).", variables: { dist: "after relax" }, opCount: 1 },
            { id: 2, narration: "After all pairs: max(dist[k][i]) over i = 2.", variables: { answer: 2 }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "word-ladder",
      title: "Word Ladder",
      difficulty: "Hard",
      status: "live",
      description: "Shortest transformation sequence from beginWord to endWord via dictionary words.",
      problem:
        "Given a `beginWord`, an `endWord`, and a `wordList` of dictionary words, return the length of the shortest transformation sequence from beginWord to endWord. Each step changes exactly one letter. Each intermediate word must be in the wordList. Example: `beginWord='hit', endWord='cog', wordList=['hot','dot','dog','lot','log','cog']` → 5. Edge cases: endWord not in wordList (return 0), wordList contains duplicates, and a direct one-letter difference.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def ladder_brute(begin, end, wordList):",
          "    def diff1(a, b): return sum(1 for x, y in zip(a, b) if x != y) == 1",
          "    used = set()",
          "    def dfs(word, depth):",
          "        if word == end: return depth",
          "        for w in wordList:",
          "            if w in used: continue",
          "            if diff1(word, w):",
          "                used.add(w)",
          "                r = dfs(w, depth + 1)",
          "                if r: return r",
          "                used.discard(w)",
          "    return dfs(begin, 1)",
        ],
      },
      annotations: {
        1: "Brute DFS: tries every path. Becomes exponential — BFS is the right baseline.",
      },
      approaches: [
        {
          id: "bfs-ladder",
          name: "BFS",
          time: "O(M² · N)",
          space: "O(M · N)",
          opsEstimate: (n) => n,
          defaultInput: { begin: "hit", end: "cog", list: ["hot","dot","dog","lot","log","cog"] },
          steps: [
            { id: 0, narration: "queue=[(hit,1)]. visited={hit}.", variables: { queue: "[(hit,1)]", visited: "{hit}", w: "hit" }, opCount: 0 },
            { id: 1, narration: "Pop (hit,1). Neighbors of hit: hot. Enqueue.", variables: { queue: "[(hot,2)]", visited: "{hit,hot}", w: "hot" }, highlight: [0], opCount: 1 },
            { id: 2, narration: "Pop (hot,2). Neighbors: dot, lot. Enqueue.", variables: { queue: "[(dot,3),(lot,3)]", visited: "{hit,hot,dot,lot}" }, highlight: [1, 4], opCount: 2 },
            { id: 3, narration: "Pop (dot,3). Neighbors: dog, hot. hot visited. Enqueue dog.", variables: { queue: "[(lot,3),(dog,4)]", visited: "{hot,dot,lot,dog}" }, highlight: [2], opCount: 3 },
            { id: 4, narration: "Pop (lot,3). Neighbors: hot, log, dot. log enqueued.", variables: { queue: "[(dog,4),(log,4)]", visited: "{hot,dot,lot,dog,log}" }, highlight: [3], opCount: 4 },
            { id: 5, narration: "Pop (dog,4). Neighbors: dot, log, cog → end! cog enqueued.", variables: { queue: "[(log,4),(cog,5)]" }, highlight: [5], opCount: 5 },
            { id: 6, narration: "Pop (log,4). Neighbors: lot, cog. cog already in queue.", variables: { queue: "[(cog,5)]" }, opCount: 6 },
            { id: 7, narration: "Pop (cog,5). word == end. Return 5.", variables: { answer: 5 }, opCount: 7, done: true },
          ],
        },
        {
          id: "bidirectional-bfs",
          name: "Bidirectional BFS",
          time: "O(M² · N)",
          space: "O(M · N)",
          opsEstimate: (n) => n,
          defaultInput: { begin: "hit", end: "cog", list: ["hot","dot","dog","lot","log","cog"] },
          steps: [
            { id: 0, narration: "Two sets: {hit} from start, {cog} from end. Expand the smaller side.", variables: { fwd: "{hit}", bwd: "{cog}" }, opCount: 0 },
            { id: 1, narration: "Expand fwd: hit → hot. fwd={hot}.", variables: { fwd: "{hot}" }, opCount: 1 },
            { id: 2, narration: "Expand bwd: cog → log, dog. bwd={log,dog}.", variables: { bwd: "{log,dog}" }, opCount: 2 },
            { id: 3, narration: "Expand fwd again: hot → dot, lot. fwd={dot,lot}.", variables: { fwd: "{dot,lot}" }, opCount: 3 },
            { id: 4, narration: "Sets still don't intersect. Expand bwd: log→cog,lots? wait log neighbors in dict: lot (in fwd)!", variables: { fwd: "{dot,lot}", bwd: "{cog,log,...}" }, opCount: 4 },
            { id: 5, narration: "Intersection found at lot (fwd and bwd reachable via cogs and log). Path length = 5.", variables: { answer: 5 }, opCount: 5, done: true },
          ],
        },
      ],
    },
    {
      slug: "number-of-provinces",
      title: "Number of Provinces",
      difficulty: "Medium",
      status: "live",
      description: "Count connected components in an undirected graph given by adjacency matrix.",
      problem:
        "Given an n x n adjacency matrix `isConnected`, where `isConnected[i][j] = 1` if city i and city j are directly connected, return the number of provinces. A province is a group of directly or indirectly connected cities, with no other cities outside the group. Example: `isConnected=[[1,1,0],[1,1,0],[0,0,1]]` → 2. Edge cases: all disconnected (n provinces), all connected (1 province), and single city (1).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def find_provinces_brute(isConnected):",
          "    n = len(isConnected)",
          "    seen = [False] * n",
          "    count = 0",
          "    for i in range(n):",
          "        if not seen[i]:",
          "            count += 1",
          "            stack = [i]",
          "            while stack:",
          "                u = stack.pop()",
          "                for v in range(n):",
          "                    if isConnected[u][v] and not seen[v]:",
          "                        seen[v] = True",
          "                        stack.append(v)",
          "    return count",
        ],
      },
      annotations: {
        6: "Brute DFS on adjacency matrix — O(n²) due to scanning row u each time.",
      },
      approaches: [
        {
          id: "union-find",
          name: "Union-Find",
          time: "O(n² · α(n))",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { isConnected: [[1,1,0],[1,1,0],[0,0,1]] },
          steps: [
            { id: 0, narration: "parent=[0,1,2]. For each (i,j) with M[i][j]=1, union(i,j).", variables: { parent: "[0,1,2]" }, opCount: 0 },
            { id: 1, narration: "(0,1)=1 → union(0,1). parent[1]=0. Now find(p) = 0 = find(0).", variables: { parent: "[0,0,2]" }, pointers: { i: 0, j: 1 }, highlight: [0, 1], opCount: 1 },
            { id: 2, narration: "(2,2)=1 (self). Skip (already same).", variables: { parent: "[0,0,2]" }, pointers: { i: 2 }, opCount: 2 },
            { id: 3, narration: "Count distinct roots = 2 → 2 provinces.", variables: { answer: 2 }, opCount: 3, done: true },
          ],
        },
        {
          id: "dfs",
          name: "DFS",
          time: "O(n²)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { isConnected: [[1,1,0],[1,1,0],[0,0,1]] },
          steps: [
            { id: 0, narration: "For each unvisited i, DFS-mark all reachable. count++.", variables: { visited: "[F,F,F]" }, opCount: 0 },
            { id: 1, narration: "i=0: DFS visits 0 and 1 (adjacent). visited=[T,T,F]. count=1.", variables: { visited: "[T,T,F]" }, pointers: { i: 0 }, highlight: [0, 1], opCount: 1 },
            { id: 2, narration: "i=1 visited. i=2 unvisited: DFS visits 2 alone. count=2.", variables: { visited: "[T,T,T]" }, pointers: { i: 2 }, highlight: [2], opCount: 2 },
            { id: 3, narration: "Done. Answer = 2.", variables: { answer: 2 }, opCount: 3, done: true },
          ],
        },
      ],
    },
  ],
};
