import type { Pattern } from "@/types/content";

export const greedy: Pattern = {
  slug: "greedy",
  title: "Greedy",
  tagline: "Local optimum leads to global optimum.",
  status: "live",
  icon: "Zap",
  topics: [
    {
      slug: "jump-game",
      title: "Jump Game",
      difficulty: "Medium",
      status: "live",
      description: "Given an array where nums[i] is the max jump length from i, determine if you can reach the last index.",
      problem:
        "Given an integer array `nums` where `nums[i]` is the maximum jump length from position i, determine if you can reach the last index starting from index 0. Example: `[2,3,1,1,4]` → true; `[3,2,1,0,4]` → false. Edge cases: array of length 1 (always true), array with all zeros (false except length 1), and an array where every element is large enough.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def can_jump_brute(nums):",
          "    from functools import lru_cache",
          "    @lru_cache(None)",
          "    def f(i):",
          "        if i >= len(nums) - 1: return True",
          "        if nums[i] == 0: return False",
          "        return any(f(i + k) for k in range(1, nums[i] + 1))",
          "    return f(0)",
        ],
      },
      annotations: {
        5: "Brute: try every reachable position recursively — exponential without memoization.",
      },
      approaches: [
        {
          id: "greedy",
          name: "Greedy (farthest reach)",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { nums: [2, 3, 1, 1, 4] },
          steps: [
            {
              id: 0,
              narration: "farthest = 0. Start at index 0.",
              variables: { farthest: 0 },
              pointers: { i: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=0, nums[0]=2. farthest = max(0, 0+2) = 2.",
              variables: { farthest: 2 },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=1: i ≤ farthest. nums[1]=3. farthest = max(2, 1+3) = 4.",
              variables: { farthest: 4 },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=2: i ≤ farthest. nums[2]=1. farthest = max(4, 2+1) = 4.",
              variables: { farthest: 4 },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=3: i ≤ farthest. nums[3]=1. farthest = max(4, 3+1) = 4.",
              variables: { farthest: 4 },
              pointers: { i: 3 },
              highlight: [3],
              opCount: 4,
            },
            {
              id: 5,
              narration: "farthest (4) ≥ last index (4). Can reach end!",
              variables: { farthest: 4, reachable: "true" },
              opCount: 5,
              done: true,
            },
          ],
        },
        {
          id: "dp",
          name: "DP",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { nums: [2, 3, 1, 1, 4] },
          steps: [
            {
              id: 0,
              narration: "dp[i] = max reachable index from start after considering up to i.",
              variables: { dp: "[2,0,0,0,0]" },
              pointers: { i: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=1: i=1 ≤ dp[0]=2 (reachable). dp[1] = max(dp[0], 1+nums[1]) = max(2,4) = 4.",
              variables: { dp: "[2,4,0,0,0]" },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=2: reachable. dp[2] = max(4, 2+1) = 4.",
              variables: { dp: "[2,4,4,0,0]" },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=3: reachable. dp[3] = max(4, 3+1) = 4.",
              variables: { dp: "[2,4,4,4,0]" },
              pointers: { i: 3 },
              highlight: [3],
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=4: reachable. dp[4] = max(4, 4+4) = 8.",
              variables: { dp: "[2,4,4,4,8]" },
              pointers: { i: 4 },
              highlight: [4],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Last index 4 is reachable. Return true.",
              variables: { reachable: "true" },
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "gas-station",
      title: "Gas Station",
      difficulty: "Medium",
      status: "live",
      description: "Find the starting gas station index to complete a circuit, given gas[i] and cost[i] at each station.",
      problem:
        "There are `n` gas stations along a circular route. You have a car with an unlimited gas tank. `gas[i]` is the amount of gas at station i and `cost[i]` is the cost to travel from station i to i+1 (circular). Return the starting station's index so that you can complete the circuit, or -1 if none exists. Example: `gas=[1,2,3,4,5], cost=[3,4,5,1,2]` → 3. Edge cases: total gas < total cost (-1), single station (gas 0, cost 0 → 0), gas equal to cost.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def gas_brute(gas, cost):",
          "    n = len(gas)",
          "    for start in range(n):",
          "        tank = 0",
          "        ok = True",
          "        for k in range(n):",
          "            i = (start + k) % n",
          "            tank += gas[i] - cost[i]",
          "            if tank < 0: ok = False; break",
          "        if ok: return start",
          "    return -1",
        ],
      },
      annotations: {
        3: "Brute: try every starting station — O(n²). The smart greedy is linear.",
      },
      approaches: [
        {
          id: "greedy",
          name: "Greedy (single pass)",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { gas: [1, 2, 3, 4, 5], cost: [3, 4, 5, 1, 2] },
          steps: [
            {
              id: 0,
              narration: "Total gas = 15, total cost = 15. A solution exists. Try start=0.",
              variables: { total: 0, tank: 0, start: 0 },
              pointers: { i: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=0: tank += 1 − 3 = −2. Can't make it to next.",
              variables: { total: -2, tank: -2, start: 0 },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Reset: start=1. i=1: tank += 2 − 4 = −2.",
              variables: { total: -4, tank: -2, start: 1 },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Reset: start=2. i=2: tank += 3 − 5 = −2.",
              variables: { total: -6, tank: -2, start: 2 },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Reset: start=3. i=3: tank += 4 − 1 = 3. Continue.",
              variables: { total: -3, tank: 3, start: 3 },
              pointers: { i: 3 },
              highlight: [3],
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=4: tank += 5 − 2 = 6. Continue.",
              variables: { total: 3, tank: 6, start: 3 },
              pointers: { i: 4 },
              highlight: [4],
              opCount: 5,
            },
            {
              id: 6,
              narration: "i=0: tank += 1 − 3 = 4. ≥ 0.",
              variables: { total: 3, tank: 4, start: 3 },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 6,
            },
            {
              id: 7,
              narration: "i=1: tank += 2 − 4 = 2. ≥ 0.",
              variables: { total: 3, tank: 2, start: 3 },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 7,
            },
            {
              id: 8,
              narration: "i=2: tank += 3 − 5 = 0. ≥ 0. Completed circuit from start=3.",
              variables: { total: 3, tank: 0, start: 3, ans: 3 },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 8,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "partition-labels",
      title: "Partition Labels",
      difficulty: "Medium",
      status: "live",
      description: "Partition a string into as many parts as possible so each letter appears in at most one part.",
      problem:
        "Given a string `s`, partition it into as many parts as possible so that each letter appears in at most one part. Return the sizes of these parts. Example: `'ababcbacadefegdehijhklij'` → [9, 7, 8]. Edge cases: string with all distinct letters (each letter is its own part), single character (single part), and inputs with repeating patterns.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def partition_brute(s):",
          "    n = len(s)",
          "    out = []",
          "    for i in range(n):",
          "        for j in range(i, n):",
          "            sub = s[i:j + 1]",
          "            rest = s[:i] + s[j + 1:]",
          "            if all(c not in rest for c in sub):",
          "                out.append(len(sub))",
          "                break",
          "    return out",
        ],
      },
      annotations: {
        5: "Brute: try cut points and verify no character is shared.",
      },
      approaches: [
        {
          id: "greedy",
          name: "Greedy (last occurrence)",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { s: "ababcbacadefegdehijhklij" },
          steps: [
            {
              id: 0,
              narration: "Record last occurrence of each letter: a=8, b=5, c=7, d=14, e=15, f=11, g=13, h=19, i=22, j=23, k=20, l=21.",
              variables: { last: "{a:8,b:5,c:7,d:14,e:15,f:11,g:13,h:19,i:22,j:23,k:20,l:21}" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=0 ('a'): end = max(end, last[a]) = max(0,8) = 8.",
              variables: { start: 0, end: 8 },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=1 ('b'): end = max(8, last[b]=5) = 8.",
              variables: { start: 0, end: 8 },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=2 ('a'): end = max(8,8) = 8.",
              variables: { start: 0, end: 8 },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=3 ('b'): end stays 8.",
              variables: { start: 0, end: 8 },
              pointers: { i: 3 },
              highlight: [3],
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=4 ('c'): end stays 8.",
              variables: { start: 0, end: 8 },
              pointers: { i: 4 },
              highlight: [4],
              opCount: 5,
            },
            {
              id: 6,
              narration: "i=5 ('b'): end stays 8.",
              variables: { start: 0, end: 8 },
              pointers: { i: 5 },
              highlight: [5],
              opCount: 6,
            },
            {
              id: 7,
              narration: "i=6 ('a'): end stays 8.",
              variables: { start: 0, end: 8 },
              pointers: { i: 6 },
              highlight: [6],
              opCount: 7,
            },
            {
              id: 8,
              narration: "i=7 ('c'): end stays 8.",
              variables: { start: 0, end: 8 },
              pointers: { i: 7 },
              highlight: [7],
              opCount: 8,
            },
            {
              id: 9,
              narration: "i=8 ('a'): i==end. CUT! Part = [0..8] = 'ababcbac'. start=9.",
              variables: { start: 9, end: 0, parts: "[9]" },
              pointers: { i: 8 },
              highlight: [8],
              opCount: 9,
            },
            {
              id: 10,
              narration: "i=9 ('d'): end = max(0, last[d]=14) = 14.",
              variables: { start: 9, end: 14 },
              pointers: { i: 9 },
              highlight: [9],
              opCount: 10,
            },
            {
              id: 11,
              narration: "i=14 ('e'): end = max(14, last[e]=15) = 15.",
              variables: { start: 9, end: 15 },
              pointers: { i: 14 },
              highlight: [14],
              opCount: 11,
            },
            {
              id: 12,
              narration: "i=15 ('f'): end stays 15.",
              variables: { start: 9, end: 15 },
              pointers: { i: 15 },
              highlight: [15],
              opCount: 12,
            },
            {
              id: 13,
              narration: "i=15 reached end. CUT! Part [9..15] = 'defegde'. start=16.",
              variables: { start: 16, end: 0, parts: "[9,7]" },
              pointers: { i: 15 },
              highlight: [15],
              opCount: 13,
            },
            {
              id: 14,
              narration: "i=16 ('h'): end = max(0, last[h]=19) = 19.",
              variables: { start: 16, end: 19 },
              pointers: { i: 16 },
              highlight: [16],
              opCount: 14,
            },
            {
              id: 15,
              narration: "Walk to i=19. At i=19 ('h'): i==end. CUT! Part [16..19] = 'hijh'. start=20.",
              variables: { start: 20, end: 0, parts: "[9,7,4]" },
              pointers: { i: 19 },
              highlight: [19],
              opCount: 15,
            },
            {
              id: 16,
              narration: "i=20 ('k'): end = max(0, last[k]=20)=20. i==end. CUT! Part='k'. start=21.",
              variables: { start: 21, end: 0, parts: "[9,7,4,1]" },
              pointers: { i: 20 },
              highlight: [20],
              opCount: 16,
            },
            {
              id: 17,
              narration: "i=21 ('l'): end = max(0,21)=21. i==end. CUT! Part='l'. Done.",
              variables: { start: 22, parts: "[9,7,4,1,1]" },
              pointers: { i: 21 },
              highlight: [21],
              opCount: 17,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "best-time-buy-sell-stock",
      title: "Best Time to Buy and Sell Stock",
      difficulty: "Easy",
      status: "live",
      description: "Maximise profit from a single buy-sell of one stock.",
      problem:
        "Given an array `prices` where `prices[i]` is the price on day i, maximize your profit by choosing one day to buy and a later day to sell. Return 0 if no profit is possible. Example: `[7,1,5,3,6,4]` → 5 (buy day 1, sell day 4). Edge cases: descending prices (0 profit), single day (0), and prices where minimum comes after maximum (0).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def max_profit_brute(prices):",
          "    n = len(prices)",
          "    best = 0",
          "    for i in range(n):",
          "        for j in range(i + 1, n):",
          "            best = max(best, prices[j] - prices[i])",
          "    return best",
        ],
      },
      annotations: {
        4: "Brute: try every pair — O(n²).",
      },
      approaches: [
        {
          id: "greedy-min",
          name: "Greedy min-so-far",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { prices: [7, 1, 5, 3, 6, 4] },
          steps: [
            { id: 0, narration: "min = 7, best = 0.", variables: { min: 7, best: 0 }, pointers: { i: 0 }, highlight: [0], opCount: 0 },
            { id: 1, narration: "i=1, price=1. min=1. profit if sell today: 1-7 (we want negative?) best = max(0, 1-7)=0.", variables: { min: 1, best: 0 }, pointers: { i: 1 }, highlight: [1], opCount: 1 },
            { id: 2, narration: "i=2, price=5. profit = 5-1=4. best=4.", variables: { min: 1, best: 4 }, pointers: { i: 2 }, highlight: [1, 2], opCount: 2 },
            { id: 3, narration: "i=3, price=3. profit = 2. best stays 4.", variables: { min: 1, best: 4 }, pointers: { i: 3 }, highlight: [1, 3], opCount: 3 },
            { id: 4, narration: "i=4, price=6. profit = 5. best=5.", variables: { min: 1, best: 5 }, pointers: { i: 4 }, highlight: [1, 4], opCount: 4 },
            { id: 5, narration: "i=5, price=4. profit=3. best stays 5.", variables: { min: 1, best: 5 }, pointers: { i: 5 }, highlight: [1, 5], opCount: 5 },
            { id: 6, narration: "Done. best = 5. Buy day 1, sell day 4.", variables: { answer: 5 }, pointers: { i: 5 }, opCount: 6, done: true },
          ],
        },
        {
          id: "kadane-diff",
          name: "Kadane on Differences",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { prices: [7, 1, 5, 3, 6, 4] },
          steps: [
            { id: 0, narration: "Compute diff[i] = prices[i] - prices[i-1] = [-6, 4, -2, 3, -2].", variables: { diff: "[-6, 4, -2, 3, -2]" }, opCount: 0 },
            { id: 1, narration: "Run Kadane on diffs to find max subarray sum. Result = 5.", variables: { maxSub: 5, answer: 5 }, opCount: 1, done: true },
          ],
        },
      ],
    },
    {
      slug: "jump-game-ii",
      title: "Jump Game II",
      difficulty: "Medium",
      status: "live",
      description: "Minimize the number of jumps to reach the last index.",
      problem:
        "Given a non-negative integer array `nums` where each element is the max jump length from that position, return the minimum number of jumps to reach the last index. The answer is guaranteed to be reachable. Example: `[2,3,1,1,4]` → 2 (jump 1→3, then 3→4). Edge cases: array of length 1 (0 jumps), array with single zero, and large inputs where multiple jumps are needed.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def jump_brute(nums):",
          "    from functools import lru_cache",
          "    n = len(nums)",
          "    @lru_cache(None)",
          "    def f(i):",
          "        if i >= n - 1: return 0",
          "        if nums[i] == 0: return float('inf')",
          "        return 1 + min(f(i + k) for k in range(1, nums[i] + 1))",
          "    return f(0)",
        ],
      },
      annotations: {
        4: "Brute recursion with memo — O(n²) due to the inner min loop.",
      },
      approaches: [
        {
          id: "greedy-bfs",
          name: "Greedy BFS",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { nums: [2, 3, 1, 1, 4] },
          steps: [
            { id: 0, narration: "Track currentEnd (end of current jump range) and farthest (max reach).", variables: { jumps: 0, curEnd: 0, farthest: 0 }, pointers: { i: 0 }, opCount: 0 },
            { id: 1, narration: "i=0, nums[0]=2. farthest = max(0, 2) = 2.", variables: { farthest: 2, curEnd: 0, jumps: 0 }, pointers: { i: 0 }, highlight: [0], opCount: 1 },
            { id: 2, narration: "i=1, nums[1]=3. farthest = max(2, 1+3)=4.", variables: { farthest: 4, curEnd: 0, jumps: 0 }, pointers: { i: 1 }, highlight: [1], opCount: 2 },
            { id: 3, narration: "i=1 == curEnd → increment jumps, curEnd = farthest=4.", variables: { farthest: 4, curEnd: 4, jumps: 1 }, pointers: { i: 1 }, opCount: 3 },
            { id: 4, narration: "i=2, nums[2]=1. farthest = max(4, 2+1)=4.", variables: { farthest: 4, curEnd: 4, jumps: 1 }, pointers: { i: 2 }, highlight: [2], opCount: 4 },
            { id: 5, narration: "i=3, nums[3]=1. farthest = max(4, 4)=4.", variables: { farthest: 4, curEnd: 4, jumps: 1 }, pointers: { i: 3 }, highlight: [3], opCount: 5 },
            { id: 6, narration: "i=3 == curEnd → jumps=2, curEnd=4 (already at end of array).", variables: { curEnd: 4, jumps: 2 }, pointers: { i: 3 }, opCount: 6 },
            { id: 7, narration: "Loop ends (i=4 == n). Return jumps=2.", variables: { jumps: 2, answer: 2 }, pointers: { i: 4 }, opCount: 7, done: true },
          ],
        },
        {
          id: "dp",
          name: "Forward DP",
          time: "O(n²)",
          space: "O(n)",
          opsEstimate: (n) => n * n,
          defaultInput: { nums: [2, 3, 1, 1, 4] },
          steps: [
            { id: 0, narration: "dp[i] = min jumps to reach i. dp[0]=0.", variables: { dp: "[0,∞,∞,∞,∞]" }, opCount: 0 },
            { id: 1, narration: "i=0, nums[0]=2: relax dp[1]=1, dp[2]=1.", variables: { dp: "[0,1,1,∞,∞]" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "i=1, nums[1]=3: relax dp[2..4] via dp[1]+1=2. dp[4]=2.", variables: { dp: "[0,1,1,2,2]" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "dp[4]=2. Done.", variables: { answer: 2 }, opCount: 3, done: true },
          ],
        },
      ],
    },
  ],
};