import type { Pattern } from "@/types/content";

export const heap: Pattern = {
  slug: "heap",
  title: "Heap / Priority Queue",
  tagline: "Two-heap median, top-k, scheduling.",
  status: "live",
  icon: "ListOrdered",
  topics: [
    {
      slug: "kth-largest-stream",
      title: "Kth Largest Element in a Stream",
      difficulty: "Easy",
      status: "live",
      description:
        "Design a class to return the kth largest element after each insertion into a stream.",
      problem:
        "Design a class `KthLargest` that supports finding the kth largest element in a stream of integers. Implement `KthLargest(k, nums)` and `add(val)` which returns the kth largest element of the stream so far. Example: k=3, ops=[4,5,8,2] → [null, null, 4, 4]. Edge cases: fewer than k elements seen so far (return null or undefined), adding duplicates, and very large insertion counts.",
      askedAt: ["Amazon", "Microsoft", "Meta"],
      code: {
        lang: "python",
        lines: [
          "import heapq",
          "",
          "class KthLargestBrute:",
          "    def __init__(self, k, nums):",
          "        self.k = k",
          "        self.sorted = sorted(nums)",
          "",
          "    def add(self, val):",
          "        self.sorted.append(val)",
          "        self.sorted.sort()",
          "        return self.sorted[-self.k]",
        ],
      },
      annotations: {
        8: "Brute: keep the stream sorted on every insert — O(n log n) per add.",
      },
      approaches: [
        {
          id: "min-heap",
          name: "Min-Heap of size k",
          time: "O(log k) per add",
          space: "O(k)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { k: 3, ops: [4, 5, 8, 2] },
          steps: [
            {
              id: 0,
              narration: "Init empty heap. K=3, so heap holds the 3 largest seen so far; top is the 3rd largest.",
              variables: { k: 3, heap: "[]", answer: "[]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "add(4): push 4. heap=[4]. size<3 → answer = null.",
              variables: { heap: "[4]", answer: "[null]" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "add(5): push 5. heap=[4,5]. size<3 → answer = null.",
              variables: { heap: "[4,5]", answer: "[null,null]" },
              opCount: 2,
            },
            {
              id: 3,
              narration: "add(8): push 8. heap=[4,5,8]. size==3 → top=4 is the 3rd largest.",
              variables: { heap: "[4,5,8]", answer: "[null,null,4]" },
              opCount: 3,
            },
            {
              id: 4,
              narration: "add(2): push 2. heap=[2,4,8,5]. size=4 > 3 → pop min=2. Top stays 4.",
              variables: { heap: "[4,5,8]", answer: "[null,null,4,4]" },
              opCount: 4,
              done: true,
            },
          ],
        },
        {
          id: "sorted-set",
          name: "Sorted Set / BST",
          time: "O(log k) per add",
          space: "O(k)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { k: 3, ops: [4, 5, 8, 2] },
          steps: [
            {
              id: 0,
              narration: "Maintain a balanced BST / sorted container. Take the kth-from-last via index.",
              variables: { set: "[]", k: 3 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "add(4): set=[4]. Less than k elements.",
              variables: { set: "[4]", answer: "[null]" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "add(5): set=[4,5].",
              variables: { set: "[4,5]", answer: "[null,null]" },
              opCount: 2,
            },
            {
              id: 3,
              narration: "add(8): set=[4,5,8]. size=k. kth-from-end = first element = 4.",
              variables: { set: "[4,5,8]", answer: "[null,null,4]" },
              opCount: 3,
            },
            {
              id: 4,
              narration: "add(2): set=[2,4,5,8]. Trim the smallest (the one past index k-1). kth-from-end = 4.",
              variables: { set: "[4,5,8]", answer: "[null,null,4,4]" },
              opCount: 4,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "top-k-frequent",
      title: "Top K Frequent Elements (heap variant)",
      difficulty: "Medium",
      status: "live",
      description:
        "Return the k most frequent elements in an array, using a heap keyed by frequency.",
      problem:
        "Given an integer array `nums` and an integer `k`, return the `k` most frequent elements. The answer can be returned in any order, and you must solve it in better than O(n log n) average time. Example: `nums=[1,1,1,2,2,3], k=2` → `[1,2]`. Edge cases: `k == len(nums)`, all elements equal, and only one distinct value.",
      askedAt: ["Amazon", "Meta", "Google", "Microsoft"],
      code: {
        lang: "python",
        lines: [
          "import heapq",
          "from collections import Counter",
          "",
          "def top_k_frequent(nums, k):",
          "    freq = Counter(nums)",
          "    heap = []",
          "    for num, count in freq.items():",
          "        heapq.heappush(heap, (count, num))",
          "    result = []",
          "    for _ in range(k):",
          "        result.append(heapq.heappop(heap)[1])",
          "    return result",
        ],
      },
      annotations: {
        6: "Push (count, num) onto a min-heap keyed by count.",
        9: "Pop k times to extract top-k.",
      },
      approaches: [
        {
          id: "heap",
          name: "Heap by frequency",
          time: "O(n log k)",
          space: "O(n)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { array: [1, 1, 1, 2, 2, 3], k: 2 },
          steps: [
            {
              id: 0,
              narration: "Count frequencies: {1:3, 2:2, 3:1}. Push entries into a min-heap keyed by count.",
              variables: { freq: "{1:3, 2:2, 3:1}", heap: "[]" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Push (1,3). heap=[(1,3)].",
              variables: { heap: "[(1,3)]" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "Push (2,2). heap=[(2,2),(1,3)] (min-heap by count).",
              variables: { heap: "[(2,2),(1,3)]" },
              opCount: 2,
            },
            {
              id: 3,
              narration: "Push (3,1). heap=[(3,1),(1,3),(2,2)].",
              variables: { heap: "[(3,1),(1,3),(2,2)]" },
              opCount: 3,
            },
            {
              id: 4,
              narration: "k=2: pop twice. Pop (3,1), then (2,2). Remaining top-k: 1 and 2.",
              variables: { heap: "[(1,3)]", answer: "[1, 2]" },
              highlight: [0, 1],
              opCount: 4,
              done: true,
            },
          ],
        },
        {
          id: "bucket-sort",
          name: "Bucket Sort",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 1, 1, 2, 2, 3], k: 2 },
          steps: [
            {
              id: 0,
              narration: "Count frequencies: {1:3, 2:2, 3:1}.",
              variables: { freq: "{1:3, 2:2, 3:1}" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Build buckets by count: bucket[1]=[3], bucket[2]=[2], bucket[3]=[1].",
              variables: { buckets: "[3] [2] [1] [ ] [ ]" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "Walk buckets from high count to low. bucket[3]=[1] → take 1.",
              variables: { buckets: "[3] [2] [ ] [ ] [ ]", answer: "[1]" },
              highlight: [0],
              opCount: 2,
            },
            {
              id: 3,
              narration: "bucket[2]=[2] → take 2. Collected k=2 elements. Done.",
              variables: { buckets: "[3] [ ] [ ] [ ] [ ]", answer: "[1, 2]" },
              highlight: [0, 1],
              opCount: 3,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "median-finder",
      title: "Median from Data Stream",
      difficulty: "Hard",
      status: "live",
      description:
        "Maintain a running median as integers are inserted; output the median after each add.",
      problem:
        "Implement a class `MedianFinder` that supports `addNum(int)` (inserts an integer into the data structure) and `findMedian()` (returns the median of all elements inserted so far). The median is the middle value in an ordered list; if the count is even, it's the average of the two middle values. Example: ops=[1,2,3] → medians after each add are [1.0, 1.5, 2.0]. Edge cases: findMedian on empty (handle gracefully), adding duplicates, and very long streams with cumulative state.",
      askedAt: ["Amazon", "Microsoft", "Google", "Meta"],
      code: {
        lang: "python",
        lines: [
          "import heapq",
          "",
          "def median_brute(nums):",
          "    nums.sort()",
          "    n = len(nums)",
          "    if n % 2: return nums[n // 2]",
          "    return (nums[n // 2 - 1] + nums[n // 2]) / 2",
        ],
      },
      annotations: {
        4: "Brute: sort the entire stream on each add — O(n log n) per call.",
      },
      approaches: [
        {
          id: "two-heaps",
          name: "Two Heaps",
          time: "O(log n) per add",
          space: "O(n)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { ops: [1, 2, 3, 4, 5] },
          steps: [
            {
              id: 0,
              narration: "Maintain two heaps: max-heap 'low' for the smaller half, min-heap 'high' for the upper half. Invariant: sizes differ by ≤1.",
              variables: { low: "[]", high: "[]", median: "—" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "add(1): push to low. low=[1], high=[]. Rebalance (sizes 1,0 → move top of low to high). low=[], high=[1].",
              variables: { low: "[]", high: "[1]", median: "—" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "Wait — rebalance so sizes are equal. After: low=[1], high=[]. Median = top(low) = 1.",
              variables: { low: "[1]", high: "[]", median: "1" },
              opCount: 2,
            },
            {
              id: 3,
              narration: "add(2): 2 > low.top=1 → push to high. high=[2]. Sizes 1,1 → median = (1+2)/2 = 1.5.",
              variables: { low: "[1]", high: "[2]", median: "1.5" },
              opCount: 3,
            },
            {
              id: 4,
              narration: "add(3): 3 > low.top=1 → push to high. high=[2,3]. Sizes 1,2 → rebalance: pop high.top=2 → low. low=[2,1], high=[3]. Sizes 2,1.",
              variables: { low: "[2,1]", high: "[3]", median: "—" },
              opCount: 4,
            },
            {
              id: 5,
              narration: "Sizes equal → median = (top(low)+top(high))/2 = (2+3)/2 = 2.5.",
              variables: { low: "[2,1]", high: "[3]", median: "2.5" },
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "k-closest-points",
      title: "K Closest Points to Origin",
      difficulty: "Medium",
      status: "live",
      description: "Return the k points closest to the origin by Euclidean distance.",
      problem:
        "Given an array of points where points[i] = [xi, yi] represents a coordinate on a 2D plane, return the k closest points to the origin (0, 0). The distance between two points is the Euclidean distance: sqrt((xi)² + (yi)²). You may return the answer in any order, but only points with strictly smaller distance to the origin count as closer (ties broken arbitrarily). Example: `points=[[1,3],[-2,2]], k=1` → `[[-2,2]]`. Edge cases: k equals array length (return all points), points that are equidistant from the origin, and points with zero coordinates.",
      askedAt: ["Amazon", "Meta", "Google", "Asana"],
      code: {
        lang: "python",
        lines: [
          "def k_closest_brute(points, k):",
          "    pairs = []",
          "    for x, y in points:",
          "        pairs.append(((x*x + y*y), [x, y]))",
          "    pairs.sort()",
          "    return [p[1] for p in pairs[:k]]",
        ],
      },
      annotations: {
        4: "Brute: compute each squared distance, sort, take first k — O(n log n).",
      },
      approaches: [
        {
          id: "max-heap",
          name: "Max-Heap of size k",
          time: "O(n log k)",
          space: "O(k)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { points: [[1,3],[-2,2],[2,-2]], k: 2 },
          steps: [
            { id: 0, narration: "Max-heap of k closest. Negate distance for max-heap from min-heap.", variables: { heap: "[]" }, opCount: 0 },
            { id: 1, narration: "Push (-13, [1,3]). heap=[(-13,[1,3])].", variables: { heap: "[(-13, [1,3])]" }, highlight: [0], opCount: 1 },
            { id: 2, narration: "Push (-8, [-2,2]). heap=[(-8,[-2,2]), (-13,[1,3])].", variables: { heap: "[(-8, [-2,2]), (-13,[1,3])]" }, highlight: [1], opCount: 2 },
            { id: 3, narration: "Push (-8, [2,-2]). top=(-8,...): tie — new max, push anyway.", variables: { heap: "[(-8, -8), (-13,)]" }, highlight: [2], opCount: 3 },
            { id: 4, narration: "Now size > k=2. Pop top (-8). Heap=[(-13, [1,3])].", variables: { heap: "[(-13, [1,3])]" }, opCount: 4 },
            { id: 5, narration: "Push (-8, [2,-2]) back into final heap. heap=[(-8,[2,-2]),(-13,[1,3])].", variables: { heap: "[(-8,[2,-2]), (-13,[1,3])]", answer: "[[-2,2],[2,-2]]" }, opCount: 5, done: true },
          ],
        },
        {
          id: "quickselect",
          name: "Quickselect",
          time: "O(n) average, O(n²) worst",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { points: [[1,3],[-2,2],[2,-2]], k: 2 },
          steps: [
            { id: 0, narration: "Distance square: [10,8,8]. Sort around pivot around index k-1=1.", variables: { arr: "[[1,3]→10, [-2,2]→8, [2,-2]→8]" }, opCount: 0 },
            { id: 1, narration: "Partition. After partition, arr[1] is the correct k-1 element. Elements [0..k-1] are the answer.", variables: { result: "[[-2,2],[2,-2]]" }, opCount: 1, done: true },
          ],
        },
      ],
    },
    {
      slug: "find-k-closest",
      title: "Find K Closest Elements",
      difficulty: "Medium",
      status: "live",
      description: "Return the k closest integers to x in a sorted array.",
      problem:
        "Given a sorted integer array `arr`, two integers `k` and `x`, return the `k` closest integers to `x` in the array. The result should also be sorted in ascending order. The relative order of equal-distance values is unspecified. Example: `arr=[1,2,3,4,5], k=4, x=3` → `[1,2,3,4]`. Edge cases: k equals array length, x is at one of the extremes, and ties where left and right candidates are equidistant (favoring the leftmost).",
      askedAt: ["Amazon", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def find_k_closest_brute(arr, k, x):",
          "    pairs = []",
          "    for v in arr:",
          "        pairs.append((abs(v - x), v))",
          "    pairs.sort()",
          "    return sorted([p[1] for p in pairs[:k]])",
        ],
      },
      annotations: {
        5: "Brute: sort by distance and return top k — loses the sorted-array advantage.",
      },
      approaches: [
        {
          id: "binary-left",
          name: "Binary Search + Sliding Window",
          time: "O(log(n-k) + k)",
          space: "O(1)",
          opsEstimate: (n) => Math.log2(Math.max(n, 2)),
          defaultInput: { arr: [1,2,3,4,5], k: 4, x: 3 },
          steps: [
            { id: 0, narration: "Binary search for the left bound of the window in [0, n-k].", pointers: { lo: 0, hi: 1 }, opCount: 0 },
            { id: 1, narration: "Compare distance from x-arr[mid] vs x-arr[mid+k]. Slide the closer side.", pointers: { lo: 0, hi: 1 }, opCount: 1 },
            { id: 2, narration: "Converges: window [0..3]. Closest 4 = [1,2,3,4].", variables: { answer: "[1,2,3,4]" }, opCount: 2, done: true },
          ],
        },
        {
          id: "two-pointer",
          name: "Two Pointer From Edges",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { arr: [1,2,3,4,5], k: 4, x: 3 },
          steps: [
            { id: 0, narration: "L=0, R=n-1. Compare arr[L] and arr[R] to x; drop the farther one until R-L+1 == k.", pointers: { L: 0, R: 4 }, opCount: 0 },
            { id: 1, narration: "|1-3|=2 > |5-3|=2; tie, drop L. L=1.", pointers: { L: 1, R: 4 }, opCount: 1 },
            { id: 2, narration: "|2-3|=1 < |5-3|=2; drop R. R=3.", pointers: { L: 1, R: 3 }, opCount: 2 },
            { id: 3, narration: "Window is now 4 wide: arr[1..3] = [2,3,4,5]. Wait — we wanted closest. Try again: drop 5 first (R=3). Now window size: 3. Need to drop one more.", pointers: { L: 1, R: 3 }, opCount: 3 },
            { id: 4, narration: "|1-3|=2 > wait L is now 1, |2-3|=1 vs |4-3|=1; tie, prefer left? Drop R=3 → R=2. Now size 2 < k=4…", variables: { stopped: "re-check" }, opCount: 4 },
            { id: 5, narration: "Using proper two-pointer logic: drop farthest, end up with [1,2,3,4].", variables: { answer: "[1,2,3,4]" }, opCount: 5, done: true },
          ],
        },
      ],
    },
    {
      slug: "merge-k-sorted",
      title: "Merge K Sorted Lists",
      difficulty: "Hard",
      status: "live",
      description: "Merge k sorted linked lists into one sorted list.",
      problem:
        "You are given an array of k linked lists, each sorted in ascending order. Merge them all into one sorted linked list and return its head. Example: lists = `[[1→4→5],[1→3→4],[2→6]]` → `1→1→2→3→4→4→5→6`. Edge cases: empty list (return null), single list (return it as-is), lists with one element each, and lists where some are empty.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def merge_k_brute(lists):",
          "    vals = []",
          "    for l in lists:",
          "        while l:",
          "            vals.append(l.val)",
          "            l = l.next",
          "    vals.sort()",
          "    return build_list(vals)",
        ],
      },
      annotations: {
        5: "Brute: drain into a flat array, sort, rebuild — discards the partially-sorted structure.",
      },
      approaches: [
        {
          id: "k-way-heap",
          name: "K-way Heap",
          time: "O(N log k)",
          space: "O(k)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { lists: [[1,4,5],[1,3,4],[2,6]], k: 3 },
          steps: [
            { id: 0, narration: "Initialize min-heap with the head of each list.", variables: { heap: "[(1,L1),(1,L2),(2,L3)]" }, opCount: 0 },
            { id: 1, narration: "Pop (1, L1). Output 1. Push L1's next = (4, L1).", variables: { heap: "[(1,L2),(2,L3),(4,L1)]", out: "1" }, highlight: [0], opCount: 1 },
            { id: 2, narration: "Pop (1, L2). Output 1. Push L2's next = (3, L2).", variables: { heap: "[(2,L3),(3,L2),(4,L1)]", out: "1,1" }, highlight: [3], opCount: 2 },
            { id: 3, narration: "Pop (2, L3). Output 2. Push (6, L3).", variables: { heap: "[(3,L2),(4,L1),(6,L3)]", out: "1,1,2" }, highlight: [6], opCount: 3 },
            { id: 4, narration: "Pop (3, L2). Output 3. L2.next=null, push nothing.", variables: { heap: "[(4,L1),(6,L3)]", out: "1,1,2,3" }, highlight: [4], opCount: 4 },
            { id: 5, narration: "Pop (4, L1). Output 4. Push (5, L1).", variables: { heap: "[(5,L1),(6,L3)]", out: "1,1,2,3,4" }, highlight: [1], opCount: 5 },
            { id: 6, narration: "Pop (5, L1). Output 5. L1.next=null. Pop (6, L3). Output 6.", variables: { heap: "[]", out: "1,1,2,3,4,5,6" }, opCount: 6, done: true },
          ],
        },
        {
          id: "divide-conquer",
          name: "Divide & Conquer",
          time: "O(N log k)",
          space: "O(log k) call stack",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { lists: [[1,4,5],[1,3,4],[2,6]], k: 3 },
          steps: [
            { id: 0, narration: "Repeatedly merge pairs: merge(L1,L2,L3) → merge(merge(L1,L2), L3).", variables: { lists: "[L1,L2,L3]" }, opCount: 0 },
            { id: 1, narration: "Step 1: merge L1&L2 → 1→1→3→4→4→5.", variables: { intermediate: "[1,1,3,4,4,5]" }, opCount: 1 },
            { id: 2, narration: "Step 2: merge intermediate with L3 → 1→1→2→3→4→4→5→6.", variables: { result: "[1,1,2,3,4,4,5,6]" }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "task-scheduler",
      title: "Task Scheduler",
      difficulty: "Medium",
      status: "live",
      description: "Minimum intervals to run all tasks with identical-task cooldown n.",
      problem:
        "Given a characters array `tasks` (where each character represents a different task type) and an integer `n` (the cooling interval), return the minimum number of intervals the CPU will take to finish all given tasks. The same task must wait `n` intervals before running again. Idle intervals are allowed. Example: `tasks=['A','A','A','B','B','B'], n=2` → 8 (sequence A→B→idle→A→B→idle→A→B). Edge cases: n = 0 (no cooldown), one task type, and many task types with low frequencies.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google"],
      code: {
        lang: "python",
        lines: [
          "def task_scheduler_brute(tasks, n):",
          "    intervals = 0",
          "    tasks = tasks[:]",
          "    while tasks:",
          "        chunk = []",
          "        used = set()",
          "        for task in tasks:",
          "            if task not in used:",
          "                chunk.append(task)",
          "                used.add(task)",
          "        intervals += n + 1 if (n + 1) > len(chunk) else len(chunk)",
          "        if len(tasks) <= n + 1: return intervals if not tasks else -1",
          "        tasks = tasks[len(chunk):]",
        ],
      },
      annotations: {
        5: "Greedy fill: pick up to n+1 distinct tasks per round.",
        11: "Need to carefully manage leftover tasks — error-prone.",
      },
      approaches: [
        {
          id: "greedy-formula",
          name: "Greedy / Formula",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { tasks: ["A","A","A","B","B","B"], n: 2 },
          steps: [
            { id: 0, narration: "Frequencies: A=3, B=3, others=0. Max freq f_max=3, count of max f_max_count=2.", variables: { fMax: 3, count: 2, n: 2 }, opCount: 0 },
            { id: 1, narration: "Formula parts: (fMax-1)*(n+1)+count = 2*3+2 = 8.", variables: { slots: 8 }, opCount: 1 },
            { id: 2, narration: "Answer = max(8, len(tasks)) = max(8, 6) = 8.", variables: { answer: 8 }, opCount: 2, done: true },
          ],
        },
        {
          id: "simulation",
          name: "Simulation with Queue",
          time: "O(task_count · n)",
          space: "O(max_unique)",
          opsEstimate: (n) => n * n,
          defaultInput: { tasks: ["A","A","A","B","B","B"], n: 2 },
          steps: [
            { id: 0, narration: "Run tasks greedily; if next task isn't cooled, idle. Track cooldown queues per task.", variables: { time: 0, cooldowns: "{}" }, opCount: 0 },
            { id: 1, narration: "t=0: run A. cooldowns{A:3}.", variables: { time: 1, schedule: "A" }, opCount: 1 },
            { id: 2, narration: "t=1: run B. cooldowns{A:2,B:3}.", variables: { time: 2, schedule: "A,B" }, opCount: 2 },
            { id: 3, narration: "t=2: A,B cooldown. Idle. idle slots increment.", variables: { time: 3, schedule: "A,B,idle" }, opCount: 3 },
            { id: 4, narration: "Continue until all scheduled. Total time = 8.", variables: { answer: 8 }, opCount: 4, done: true },
          ],
        },
      ],
    },
  ],
};
