import type { Pattern } from "@/types/content";

export const linkedList: Pattern = {
  slug: "linked-list",
  title: "Linked List",
  tagline: "Two-pointer, fast/slow, in-place reversal.",
  status: "live",
  icon: "Link",
  topics: [
    {
      slug: "reverse-list",
      title: "Reverse Linked List",
      difficulty: "Easy",
      status: "live",
      description:
        "Reverse a singly linked list in place and return the new head.",
      problem:
        "Given the head of a singly linked list, reverse the list in place and return the new head. Reverse direction of all next pointers. Example: 1→2→3→4→5 becomes 5→4→3→2→1. Constraints: 0 ≤ n ≤ 5000. Edge cases: empty list (return null), single node (return that node unchanged), and a two-node list.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Apple"],
      code: {
        lang: "python",
        lines: [
          "def reverse_list_brute(arr):",
          "    vals = []",
          "    for x in arr: vals.append(x)",
          "    vals.reverse()",
          "    out = build_list(vals)",
          "    return out",
        ],
      },
      annotations: {
        2: "Brute-force approach is to dump the values into a list.",
        3: "Reverse that list.",
        4: "Build a new linked list from the reversed values — defeats the in-place constraint.",
      },
      approaches: [
        {
          id: "iterative",
          name: "Iterative",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4, 5] },
          steps: [
            {
              id: 0,
              narration: "Init prev=null, cur=head (1). next will be saved before each flip.",
              pointers: { cur: 0 },
              variables: { prev: "null", cur: "1", next: "—" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Save next=2. Flip: cur.next = prev (1→null). Advance: prev=1, cur=2.",
              pointers: { prev: 0, cur: 1 },
              variables: { prev: "1", cur: "2", next: "2" },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Save next=3. Flip: 2→1. Advance: prev=2, cur=3.",
              pointers: { prev: 1, cur: 2 },
              variables: { prev: "2", cur: "3", next: "3" },
              highlight: [0, 1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Save next=4. Flip: 3→2. Advance: prev=3, cur=4.",
              pointers: { prev: 2, cur: 3 },
              variables: { prev: "3", cur: "4", next: "4" },
              highlight: [0, 1, 2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Save next=5. Flip: 4→3. Advance: prev=4, cur=5.",
              pointers: { prev: 3, cur: 4 },
              variables: { prev: "4", cur: "5", next: "5" },
              highlight: [0, 1, 2, 3],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Save next=null. Flip: 5→4. cur=null, stop. prev=5 is the new head.",
              pointers: { prev: 4 },
              variables: { prev: "5", cur: "null", next: "null" },
              highlight: [0, 1, 2, 3, 4],
              opCount: 5,
              done: true,
            },
          ],
        },
        {
          id: "recursive",
          name: "Recursive",
          time: "O(n)",
          space: "O(n) call stack",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4, 5] },
          steps: [
            {
              id: 0,
              narration: "Base: reverse(5) → returns 5. Unwind and rewire pointers on the way back.",
              pointers: { cur: 4 },
              variables: { stack: "[r(5)]", newHead: "5" },
              highlight: [4],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Return to reverse(4). 4.next.next = 4 → 5→4. 4.next = null.",
              pointers: { cur: 3 },
              variables: { stack: "[r(4)]", newHead: "5" },
              highlight: [3, 4],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Return to reverse(3). 3→null, 4→3.",
              pointers: { cur: 2 },
              variables: { stack: "[r(3)]", newHead: "5" },
              highlight: [2, 3, 4],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Return to reverse(2). 2→null, 3→2.",
              pointers: { cur: 1 },
              variables: { stack: "[r(2)]", newHead: "5" },
              highlight: [1, 2, 3, 4],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Return to reverse(1). 1→null, 2→1.",
              pointers: { cur: 0 },
              variables: { stack: "[r(1)]", newHead: "5" },
              highlight: [0, 1, 2, 3, 4],
              opCount: 4,
            },
            {
              id: 5,
              narration: "Return newHead=5. List is 5→4→3→2→1.",
              variables: { stack: "[]", newHead: "5", list: "5→4→3→2→1" },
              highlight: [0, 1, 2, 3, 4],
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "detect-cycle",
      title: "Detect Linked List Cycle",
      difficulty: "Easy",
      status: "live",
      description:
        "Determine if a linked list has a cycle. A cycle exists when a node's next points to a previously visited node.",
      problem:
        "Given `head`, the head of a linked list, determine if the linked list has a cycle in it. There is a cycle if some node's `next` pointer can be reached again by continuously following the `next` pointer. Return `true` if there is a cycle, `false` otherwise. The constraint is O(1) extra space. Example: 3→2→0→-4 where -4's next points back to 2 → cycle. Edge cases: empty list, single node with self-loop, single node no self-loop.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def has_cycle_brute(head):",
          "    vals = []",
          "    while head:",
          "        vals.append(head)",
          "        head = head.next",
          "                if head in vals: return True",
          "    return False",
        ],
      },
      annotations: {
        4: "Walk the list storing every node reference seen.",
        6: "If we revisit a node we have a cycle.",
      },
      approaches: [
        {
          id: "hash-set",
          name: "Hash Set",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [3, 2, 0, -4], pos: 1 },
          steps: [
            {
              id: 0,
              narration: "Walk the list, storing each node's address in a set. If we revisit, there's a cycle.",
              variables: { seen: "{}", cur: "3(0)" },
              pointers: { i: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Visit 3(0). Not in set. Insert.",
              variables: { seen: "{3(0)}", cur: "2(1)" },
              pointers: { i: 1 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Visit 2(1). Not in set. Insert.",
              variables: { seen: "{3(0), 2(1)}", cur: "0(2)" },
              pointers: { i: 2 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Visit 0(2). Not in set. Insert.",
              variables: { seen: "{3(0),2(1),0(2)}", cur: "-4(3)" },
              pointers: { i: 3 },
              highlight: [2],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Visit -4(3). next → node 2(1). Insert -4(3).",
              variables: { seen: "{3(0),2(1),0(2),-4(3)}", cur: "2(1)" },
              pointers: { i: 1 },
              highlight: [3],
              opCount: 4,
            },
            {
              id: 5,
              narration: "About to visit 2(1) again — already in set. Cycle detected!",
              variables: { seen: "{3(0),2(1),0(2),-4(3)}", answer: "true" },
              pointers: { i: 1 },
              highlight: [1, 3],
              opCount: 5,
              done: true,
            },
          ],
        },
        {
          id: "floyd",
          name: "Floyd's Tortoise & Hare",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [3, 2, 0, -4], pos: 1 },
          steps: [
            {
              id: 0,
              narration: "Two pointers start at head: slow moves 1 step, fast moves 2 steps each round.",
              pointers: { slow: 0, fast: 0 },
              variables: { slow: "0", fast: "0" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "Step 1: slow=3(0)→2(1), fast=3(0)→0(2)→-4(3).",
              pointers: { slow: 1, fast: 3 },
              variables: { slow: "2(1)", fast: "-4(3)" },
              opCount: 1,
            },
            {
              id: 2,
              narration: "Step 2: slow=2(1)→0(2), fast=-4(3)→2(1)→0(2).",
              pointers: { slow: 2, fast: 2 },
              variables: { slow: "0(2)", fast: "0(2)" },
              opCount: 2,
            },
            {
              id: 3,
              narration: "Step 3: slow=0(2)→-4(3), fast=0(2)→-4(3)→2(1).",
              pointers: { slow: 3, fast: 1 },
              variables: { slow: "-4(3)", fast: "2(1)" },
              opCount: 3,
            },
            {
              id: 4,
              narration: "Step 4: slow=-4(3)→2(1), fast=2(1)→0(2)→-4(3).",
              pointers: { slow: 1, fast: 3 },
              variables: { slow: "2(1)", fast: "-4(3)" },
              opCount: 4,
            },
            {
              id: 5,
              narration: "Step 5: slow=2(1), fast=2(1). slow == fast → cycle!",
              pointers: { slow: 1, fast: 1 },
              variables: { slow: "2(1)", fast: "2(1)", answer: "true" },
              highlight: [1],
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "merge-two-lists",
      title: "Merge Two Sorted Lists",
      difficulty: "Easy",
      status: "live",
      description:
        "Merge two sorted linked lists into one sorted list by splicing nodes.",
      problem:
        "Merge two sorted linked lists `list1` and `list2` into one sorted list by splicing nodes (not rebuilding). Return the head of the merged list. Example: 1→2→4 merged with 1→3→4 → 1→1→2→3→4→4. Edge cases: one list empty (return the other), both empty (return null), and lists of widely different lengths.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Apple"],
      code: {
        lang: "python",
        lines: [
          "def merge_two_lists_brute(a, b):",
          "    vals = []",
          "    while a: vals.append(a.val); a = a.next",
          "    while b: vals.append(b.val); b = b.next",
          "    vals.sort()",
          "    return build_list(vals)",
        ],
      },
      annotations: {
        5: "Concatenate both lists into a single array, then sort — but this loses the splice optimization.",
      },
      approaches: [
        {
          id: "iterative",
          name: "Iterative",
          time: "O(n+m)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { a: [1, 2, 4], b: [1, 3, 4] },
          steps: [
            {
              id: 0,
              narration: "Compare heads of a and b. Pick the smaller, attach to tail, advance that list.",
              pointers: { a: 0, b: 0 },
              variables: { a: "1", b: "1", tail: "dummy" },
              highlight: [0, 3],
              opCount: 0,
            },
            {
              id: 1,
              narration: "1==1, take from a. tail→1(a). Advance a to 2.",
              pointers: { a: 1, b: 0 },
              variables: { a: "2", b: "1", tail: "1(a)" },
              highlight: [1, 3],
              opCount: 1,
            },
            {
              id: 2,
              narration: "2 > 1, take from b. tail→1(b). Advance b to 3.",
              pointers: { a: 1, b: 4 },
              variables: { a: "2", b: "3", tail: "1(b)" },
              highlight: [1, 4],
              opCount: 2,
            },
            {
              id: 3,
              narration: "2 < 3, take from a. tail→2. Advance a to 4.",
              pointers: { a: 2, b: 4 },
              variables: { a: "4", b: "3", tail: "2" },
              highlight: [2, 4],
              opCount: 3,
            },
            {
              id: 4,
              narration: "4 > 3, take from b. tail→3. Advance b to 4.",
              pointers: { a: 2, b: 5 },
              variables: { a: "4", b: "4", tail: "3" },
              highlight: [2, 5],
              opCount: 4,
            },
            {
              id: 5,
              narration: "4 == 4, take from a. tail→4(a). Advance a → null.",
              pointers: { a: 6, b: 5 },
              variables: { a: "null", b: "4", tail: "4(a)" },
              highlight: [2, 5],
              opCount: 5,
            },
            {
              id: 6,
              narration: "a is null, splice remaining b: tail→4(b). Merged: 1,1,2,3,4,4.",
              pointers: { a: 6, b: 6 },
              variables: { a: "null", b: "null", tail: "4(b)", answer: "[1,1,2,3,4,4]" },
              highlight: [0, 1, 2, 3, 4, 5],
              opCount: 6,
              done: true,
            },
          ],
        },
        {
          id: "recursive",
          name: "Recursive",
          time: "O(n+m)",
          space: "O(n+m) call stack",
          opsEstimate: (n) => n,
          defaultInput: { a: [1, 2, 4], b: [1, 3, 4] },
          steps: [
            {
              id: 0,
              narration: "Base: if either list is null, return the other. Otherwise compare heads.",
              variables: { a: "1", b: "1", call: "merge(1a,1b)" },
              pointers: { a: 0, b: 0 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "1==1. Pick a's 1. Recurse on a=2 vs b=1. Returned sublist will be tacked on.",
              variables: { a: "2", b: "1", call: "merge(2,1)" },
              pointers: { a: 1, b: 0 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "2>1. Pick b's 1. Recurse on a=2 vs b=3.",
              variables: { a: "2", b: "3", call: "merge(2,3)" },
              pointers: { a: 1, b: 4 },
              highlight: [3],
              opCount: 2,
            },
            {
              id: 3,
              narration: "2<3. Pick a's 2. Recurse on a=4 vs b=3.",
              variables: { a: "4", b: "3", call: "merge(4,3)" },
              pointers: { a: 2, b: 4 },
              highlight: [1],
              opCount: 3,
            },
            {
              id: 4,
              narration: "4>3. Pick b's 3. Recurse on a=4 vs b=4.",
              variables: { a: "4", b: "4", call: "merge(4,4)" },
              pointers: { a: 2, b: 5 },
              highlight: [4],
              opCount: 4,
            },
            {
              id: 5,
              narration: "4==4. Pick a's 4. Recurse on a=null vs b=4 → returns b's 4. Wire: 4(a)→4(b).",
              variables: { a: "null", b: "4", call: "merge(null,4)" },
              pointers: { a: 6, b: 5 },
              highlight: [2, 5],
              opCount: 5,
            },
            {
              id: 6,
              narration: "Unwind: each frame returns its chosen node already linked to the rest. Final: 1,1,2,3,4,4.",
              variables: { answer: "[1,1,2,3,4,4]", stack: "[]" },
              highlight: [0, 1, 2, 3, 4, 5],
              opCount: 6,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "add-two-numbers",
      title: "Add Two Numbers",
      difficulty: "Medium",
      status: "live",
      description: "Add two non-negative numbers stored as reversed linked lists.",
      problem:
        "You are given two non-empty linked lists representing two non-negative integers, stored in reverse order (the most significant digit is the tail). Add the two numbers and return the sum as a linked list (same reverse-order format). Example: 2→4→3 + 5→6→4 → 7→0→8 (342 + 465 = 807). Edge cases: one list empty, both zero (`[0]`), a carry propagating to a new most-significant digit, and lists of different lengths.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def add_two_numbers_brute(a, b):",
          "    def to_int(node):",
          "        v, p = 0, 1",
          "        while node:",
          "            v += node.val * p",
          "            p *= 10",
          "            node = node.next",
          "        return v",
          "    s = to_int(a) + to_int(b)",
          "    head = cur = ListNode(s % 10)",
          "    s //= 10",
          "    while s:",
          "        cur.next = ListNode(s % 10)",
          "        cur = cur.next",
          "        s //= 10",
          "    return head",
        ],
      },
      annotations: {
        1: "Reverse the link list as a real number — works only for small values.",
        11: "Convert the sum back into a reversed linked list, one digit at a time.",
      },
      approaches: [
        {
          id: "carry-walk",
          name: "Two-Pointer Walk with Carry",
          time: "O(max(n,m))",
          space: "O(max(n,m))",
          opsEstimate: (n) => n,
          defaultInput: { a: [2, 4, 3], b: [5, 6, 4] },
          steps: [
            { id: 0, narration: "Walk both lists with a carry. dummy = head.", variables: { dummy: "(0)", carry: 0 }, pointers: { a: 0, b: 0 }, opCount: 0 },
            { id: 1, narration: "2+5+0=7 → write 7, carry 0. a.next, b.next.", variables: { carry: 0, list: "[7]" }, pointers: { a: 1, b: 1 }, highlight: [0, 3], opCount: 1 },
            { id: 2, narration: "4+6+0=10 → write 0, carry 1.", variables: { carry: 1, list: "[7,0]" }, pointers: { a: 2, b: 2 }, highlight: [1, 4], opCount: 2 },
            { id: 3, narration: "3+4+1=8 → write 8, carry 0. Both done.", variables: { carry: 0, list: "[7,0,8]" }, pointers: { a: 6, b: 5 }, highlight: [2, 5], opCount: 3 },
            { id: 4, narration: "Carry is 0, no extra. Result = [7,0,8].", variables: { carry: 0, answer: "[7,0,8]" }, opCount: 4, done: true },
          ],
        },
        {
          id: "pad-lists",
          name: "Pad and Walk (cleaner)",
          time: "O(max(n,m))",
          space: "O(max(n,m))",
          opsEstimate: (n) => n,
          defaultInput: { a: [2, 4, 3], b: [5, 6, 4] },
          steps: [
            { id: 0, narration: "Pad the shorter list with zeros so lengths match. Same carry walk.", variables: { a: "[2,4,3]", b: "[5,6,4]" }, opCount: 0 },
            { id: 1, narration: "Build sum digit by digit at each position (units, tens, hundreds).", variables: { list: "[7,0,8]" }, opCount: 1, done: true },
          ],
        },
      ],
    },
    {
      slug: "palindrome-list",
      title: "Palindrome Linked List",
      difficulty: "Easy",
      status: "live",
      description: "Decide whether a singly linked list is a palindrome.",
      problem:
        "Given the `head` of a singly linked list with integer values, return `true` if it is a palindrome, `false` otherwise. Use O(n) time and O(1) extra space. Example: 1→2→2→1 → true; 1→2 → false. Edge cases: empty list or single node (return true), and lists with odd length where the middle element can be skipped.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Apple"],
      code: {
        lang: "python",
        lines: [
          "def is_palindrome_brute(head):",
          "    vals = []",
          "    while head:",
          "        vals.append(head.val)",
          "        head = head.next",
          "    return vals == vals[::-1]",
        ],
      },
      annotations: {
        2: "Brute force dumps the list to an array, then compares to its reverse.",
      },
      approaches: [
        {
          id: "reverse-half",
          name: "Reverse Second Half",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 2, 1] },
          steps: [
            { id: 0, narration: "Use fast/slow to find the mid. Reverse the second half in place.", variables: { slow: 0, fast: 0 }, pointers: { slow: 0, fast: 0 }, opCount: 0 },
            { id: 1, narration: "fast moves 2, slow 1. After full walk, slow points at mid (index 2).", variables: { slow: 2, fast: 6 }, pointers: { slow: 2, fast: 6 }, highlight: [2], opCount: 1 },
            { id: 2, narration: "Reverse the second half (2,1) → (1,2).", variables: { second: "[1,2]" }, pointers: { rev: 1 }, highlight: [1, 2], opCount: 2 },
            { id: 3, narration: "Walk: 1==1 ✓, 2==2 ✓. Match!", variables: { match: "1==1, 2==2" }, pointers: { L: 0, R: 1 }, opCount: 3 },
            { id: 4, narration: "All matched. Palindrome = true.", variables: { answer: "true" }, opCount: 4, done: true },
          ],
        },
        {
          id: "stack",
          name: "Stack (push first half)",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 2, 1] },
          steps: [
            { id: 0, narration: "Walk with slow/fast. Push slow values onto a stack.", variables: { stack: "[]", slow: 0, fast: 0 }, opCount: 0 },
            { id: 1, narration: "Push 1 → stack=[1]. Push 2 → stack=[1,2].", variables: { stack: "[1,2]" }, opCount: 1 },
            { id: 2, narration: "Reached mid. Pop & compare against second half.", variables: { stack: "[1,2]" }, opCount: 2 },
            { id: 3, narration: "Pop 2 vs 2 ✓. Pop 1 vs 1 ✓.", variables: { stack: "[]" }, opCount: 3 },
            { id: 4, narration: "Stack empty + matched. Palindrome.", variables: { answer: "true" }, opCount: 4, done: true },
          ],
        },
      ],
    },
    {
      slug: "remove-nth-from-end",
      title: "Remove N-th Node From End",
      difficulty: "Medium",
      status: "live",
      description: "Remove the n-th node from the end of a linked list.",
      problem:
        "Given the `head` of a linked list, remove the n-th node from the end and return the head. Example: 1→2→3→4→5, n=2 → 1→2→3→5 (removed 4). Constraints: n is guaranteed valid (1 ≤ n ≤ length). Edge cases: n equals the list length (remove the head), single-node list (return null), and removing the tail.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Apple"],
      code: {
        lang: "python",
        lines: [
          "def remove_nth_brute(head, n):",
          "    vals = []",
          "    cur = head",
          "    while cur:",
          "        vals.append(cur.val)",
          "        cur = cur.next",
          "    vals.pop(len(vals) - n)",
          "    return build_list(vals)",
        ],
      },
      annotations: {
        6: "Brute: copy to array, skip the n-th-from-last, rebuild — uses O(n) extra.",
      },
      approaches: [
        {
          id: "two-pointer-gap",
          name: "Two-Pointer Gap",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4, 5], n: 2 },
          steps: [
            { id: 0, narration: "Place a dummy before head. Advance fast by n+1 so the gap between slow and fast is exactly n.", variables: { slow: "dummy", fast: "head" }, pointers: { slow: 0, fast: 0 }, opCount: 0 },
            { id: 1, narration: "Move fast 3 times (n=2 → n+1=3) so fast is at index 3 (val 4).", variables: { fast: "node(4)" }, pointers: { fast: 3 }, highlight: [3], opCount: 1 },
            { id: 2, narration: "Move both at same speed. slow at 1, fast at 4.", variables: { slow: "1", fast: "4" }, pointers: { slow: 0, fast: 3 }, opCount: 2 },
            { id: 3, narration: "slow at 2, fast at 5.", variables: { slow: "2", fast: "5" }, pointers: { slow: 1, fast: 4 }, opCount: 3 },
            { id: 4, narration: "slow at 3, fast=null. Loop ends. slow.next.next=val 5.", variables: { slow: "3" }, pointers: { slow: 2, fast: 6 }, opCount: 4 },
            { id: 5, narration: "Set slow.next = slow.next.next. val 4 skipped. List: 1→2→3→5.", variables: { result: "[1,2,3,5]", answer: "[1,2,3,5]" }, highlight: [3], opCount: 5, done: true },
          ],
        },
        {
          id: "count-twice",
          name: "Count Length, Walk Twice",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4, 5], n: 2 },
          steps: [
            { id: 0, narration: "First pass: count length = 5. Target index = 5 - 2 = 3.", variables: { len: 5, target: 3 }, opCount: 0 },
            { id: 1, narration: "Second pass: walk to index 2. slow.next.next = slow.next.next.next.", variables: { slow: "3" }, opCount: 1, done: true },
          ],
        },
      ],
    },
    {
      slug: "reorder-list",
      title: "Reorder List",
      difficulty: "Medium",
      status: "live",
      description: "Reorder list so L0→L1→…→Ln becomes L0→Ln→L1→Ln-1→…",
      problem:
        "Given the head of a singly linked list L0→L1→…→Ln-1→Ln, reorder it in place to: L0→Ln→L1→Ln-1→L2→Ln-2→…. The reordering must use only O(1) extra space and may not modify node values. Example: 1→2→3→4 → 1→4→2→3. Edge cases: empty list, single node, two nodes, and odd-length lists.",
      askedAt: ["Amazon", "Microsoft", "Meta"],
      code: {
        lang: "python",
        lines: [
          "def reorder_brute(head):",
          "    vals = []",
          "    while head:",
          "        vals.append(head.val)",
          "        head = head.next",
          "    n = len(vals)",
          "    order = []",
          "    for i in range(n // 2):",
          "        order.append(vals[i])",
          "        order.append(vals[n - 1 - i])",
          "    if n % 2: order.append(vals[n // 2])",
          "    return build_list(order)",
        ],
      },
      annotations: {
        9: "Interleave front and back elements into the desired order, then rebuild — defeats in-place.",
      },
      approaches: [
        {
          id: "reverse-merge",
          name: "Midpoint + Reverse + Merge",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4] },
          steps: [
            { id: 0, narration: "Find mid with slow/fast. slow points at index 2 (val 3).", variables: { slow: "3", fast: "null" }, pointers: { slow: 2, fast: 6 }, opCount: 0 },
            { id: 1, narration: "Reverse the second half: 3→4 becomes 4→3.", variables: { second: "[4,3]" }, pointers: { rev: 0 }, highlight: [2, 3], opCount: 1 },
            { id: 2, narration: "Merge alternately: take from first half then second half.", variables: { first: "[1,2]", second: "[4,3]" }, opCount: 2 },
            { id: 3, narration: "Take 1, then 4. List so far: 1→4.", variables: { list: "[1,4]" }, highlight: [0, 1], opCount: 3 },
            { id: 4, narration: "Take 2, then 3. Final: 1→4→2→3.", variables: { list: "[1,4,2,3]", answer: "[1,4,2,3]" }, highlight: [0, 1, 2, 3], opCount: 4, done: true },
          ],
        },
        {
          id: "deque-pull",
          name: "Deque Mock-up",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4] },
          steps: [
            { id: 0, narration: "Push values into a deque. Pop front, then pop back, repeat.", variables: { dq: "[4,3,2,1]" }, opCount: 0 },
            { id: 1, narration: "Pop front → 1. Pop back → 4.", variables: { order: "[1,4]" }, opCount: 1 },
            { id: 2, narration: "Pop front → 2. Pop back → 3. Order = [1,4,2,3].", variables: { order: "[1,4,2,3]" }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "swap-pairs",
      title: "Swap Nodes in Pairs",
      difficulty: "Medium",
      status: "live",
      description: "Swap every two adjacent nodes in a linked list.",
      problem:
        "Given a linked list, swap every two adjacent nodes and return the head. You must solve the problem in place with O(1) extra space. Example: 1→2→3→4 → 2→1→4→3. Edge cases: empty list (no change), single node (no change), and odd-length list (the last node stays put).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Apple"],
      code: {
        lang: "python",
        lines: [
          "def swap_pairs_brute(head):",
          "    vals = []",
          "    while head:",
          "        vals.append(head.val)",
          "        head = head.next",
          "    for i in range(0, len(vals) - 1, 2):",
          "        vals[i], vals[i+1] = vals[i+1], vals[i]",
          "    return build_list(vals)",
        ],
      },
      annotations: {
        5: "Brute: dump to array, swap pairs, rebuild — not in place.",
      },
      approaches: [
        {
          id: "iterative",
          name: "Iterative Pointer Rewire",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4] },
          steps: [
            { id: 0, narration: "dummy→1→2→3→4. prev=dummy, cur=1.", variables: { prev: "dummy", cur: "1" }, pointers: { prev: 0, cur: 0 }, opCount: 0 },
            { id: 1, narration: "next = 2. cur.next = next.next = 3. next.next = cur = 1. prev.next = next = 2.", variables: { state: "dummy→2→1→3→…" }, pointers: { prev: 0, cur: 0 }, highlight: [0, 1, 2], opCount: 1 },
            { id: 2, narration: "Advance: prev = cur = 1. cur = cur.next = 3.", variables: { prev: "1", cur: "3" }, pointers: { prev: 1, cur: 2 }, opCount: 2 },
            { id: 3, narration: "next = 4. Swap pair (3,4): 4.next=3. prev.next=4. List: 2→1→4→3.", variables: { state: "2→1→4→3" }, pointers: { prev: 1, cur: 2 }, highlight: [2, 3], opCount: 3 },
            { id: 4, narration: "cur.next = null → loop ends. Done.", variables: { answer: "[2,1,4,3]" }, opCount: 4, done: true },
          ],
        },
        {
          id: "recursive",
          name: "Recursive",
          time: "O(n)",
          space: "O(n) call stack",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 2, 3, 4] },
          steps: [
            { id: 0, narration: "Base: head or head.next is null → return head.", variables: { call: "swap(1→2→3→4)" }, opCount: 0 },
            { id: 1, narration: "Swap head (1) and head.next (2). Recurse on rest.", variables: { call: "swap(rest)" }, opCount: 1 },
            { id: 2, narration: "Rest swaps (3,4) → 4→3. Wire 2.next = 4→3. Return 2→1→4→3.", variables: { answer: "[2,1,4,3]" }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "lru-cache",
      title: "LRU Cache",
      difficulty: "Medium",
      status: "live",
      description: "Design an LRU cache with O(1) get and put.",
      problem:
        "Design a data structure that follows the Least Recently Used (LRU) cache eviction policy with O(1) get and put. Implement `LRUCache(int capacity)` and the methods `get(key)` and `put(key, value)`. When a key is accessed (via get or put), it becomes the most recently used. When the cache is full, evict the least recently used entry to make room. Example: capacity 2, ops: `put(1,1), put(2,2), get(1)=1, put(3,3), get(2)=-1`. Edge cases: capacity 0 (every put evicts), repeated put on same key (updates value + recency), and multiple `get` misses.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google", "Apple"],
      code: {
        lang: "python",
        lines: [
          "class LRUBrute:",
          "    def __init__(self, capacity):",
          "        self.capacity = capacity",
          "        self.cache = {}",
          "",
          "    def get(self, key):",
          "        if key not in self.cache: return -1",
          "        val = self.cache.pop(key)",
          "        self.cache[key] = val",
          "        return val",
        ],
      },
      annotations: {
        3: "Brute: use a regular dict; on access, delete + re-insert to bump recency to the end.",
        8: "Recency = insertion order in Python dict; popping and reinserting moves it to MRU.",
      },
      approaches: [
        {
          id: "ordered-dict",
          name: "OrderedDict",
          time: "O(1) get/put",
          space: "O(capacity)",
          opsEstimate: (n) => 1,
          defaultInput: { cap: 2, ops: ["put(1,1)","put(2,2)","get(1)","put(3,3)","get(2)"] },
          steps: [
            { id: 0, narration: "OrderedDict = dict that tracks insertion order. move_to_end = bump recency.", variables: { cache: "{}", order: "[]" }, opCount: 0 },
            { id: 1, narration: "put(1,1): cache={1:1} LRU.", variables: { cache: "{1:1}", order: "[1]" }, opCount: 1 },
            { id: 2, narration: "put(2,2): cache={1:1, 2:2} LRU=1, MRU=2.", variables: { cache: "{1:1, 2:2}", order: "[1,2]" }, opCount: 2 },
            { id: 3, narration: "get(1): found. Move 1 to end. Order = [2,1]. Return 1.", variables: { cache: "{1:1, 2:2}", order: "[2,1]" }, opCount: 3 },
            { id: 4, narration: "put(3,3): full. Popitem(last=False) evicts LRU=2. Insert 3.", variables: { cache: "{1:1, 3:3}", order: "[1,3]" }, opCount: 4 },
            { id: 5, narration: "get(2): not present. Return -1.", variables: { answer: -1 }, opCount: 5, done: true },
          ],
        },
        {
          id: "doubly-linked",
          name: "Doubly-Linked List + Hash",
          time: "O(1) get/put",
          space: "O(capacity)",
          opsEstimate: (n) => 1,
          defaultInput: { cap: 2, ops: ["put(1,1)","put(2,2)","get(1)","put(3,3)","get(2)"] },
          steps: [
            { id: 0, narration: "HashMap<key, node>. Doubly-linked list with dummy head & tail.", variables: { map: "{}", head: "d", tail: "d", size: 0 }, opCount: 0 },
            { id: 1, narration: "put(1,1): new node. Insert at tail-prev. map={1:node1}. size=1.", variables: { map: "{1:n1}", size: 1 }, opCount: 1 },
            { id: 2, narration: "put(2,2): new node. Insert at tail-prev. map={1,2}. size=2.", variables: { map: "{1,2}", size: 2 }, opCount: 2 },
            { id: 3, narration: "get(1): find node1 in O(1). Unlink, reinsert at tail-prev (MRU). Return 1.", variables: { map: "{1,2}", size: 2 }, opCount: 3 },
            { id: 4, narration: "put(3,3): full. Evict head-next (LRU=2). Insert 3 at MRU. map={1,3}.", variables: { map: "{1,3}", size: 2 }, opCount: 4 },
            { id: 5, narration: "get(2): -1.", variables: { answer: -1 }, opCount: 5, done: true },
          ],
        },
      ],
    },
  ],
};
