import type { Pattern } from "@/types/content";

export const monotonicStack: Pattern = {
  slug: "monotonic-stack",
  title: "Monotonic Stack",
  tagline: "Next-greater in O(n).",
  status: "live",
  icon: "ChevronUp",
  topics: [
    {
      slug: "next-greater",
      title: "Next Greater Element",
      difficulty: "Medium",
      status: "live",
      description:
        "For each index, find the nearest greater element to its right. Return -1 if none.",
      problem:
        "Given a circular array `nums` (or a regular array, depending on variant), for each element find the next greater element to its right. Return an array of equal size where each entry is the nearest strictly greater value or -1 if none exists. Example: [2,1,2,4,3] → [4,2,4,-1,-1]. Edge cases: strictly decreasing array (all -1), strictly increasing array (next index for each), duplicates where next-greater must be strictly greater.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def next_greater_brute(nums):",
          "    n = len(nums)",
          "    ans = [-1] * n",
          "    for i in range(n):",
          "        for j in range(i + 1, n):",
          "            if nums[j] > nums[i]:",
          "                ans[i] = nums[j]",
          "                break",
          "    return ans",
        ],
      },
      annotations: {
        5: "Brute: for each i, scan rightward to find the first element > nums[i] — O(n²).",
      },
      approaches: [
        {
          id: "monotonic",
          name: "Monotonic Stack (decreasing)",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [2, 1, 2, 4, 3] },
          steps: [
            {
              id: 0,
              narration: "Stack holds indices whose next-greater hasn't been found. Push i=0.",
              variables: { stack: "[0]", ans: "[-1,-1,-1,-1,-1]" },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "arr[1]=1 < arr[top=0]=2 — no pop. Push i=1.",
              variables: { stack: "[0,1]", ans: "[-1,-1,-1,-1,-1]" },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 1,
            },
            {
              id: 2,
              narration: "arr[2]=2 > arr[top=1]=1 — pop 1, ans[1]=2. Still arr[2]=2 == arr[top=0]=2, no pop. Push i=2.",
              variables: { stack: "[0,2]", ans: "[-1,2,-1,-1,-1]" },
              pointers: { i: 2 },
              highlight: [1, 2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "arr[3]=4 > arr[top=2]=2 — pop 2, ans[2]=4. arr[3]=4 > arr[top=0]=2 — pop 0, ans[0]=4. Stack empty. Push i=3.",
              variables: { stack: "[3]", ans: "[4,2,4,-1,-1]" },
              pointers: { i: 3 },
              highlight: [0, 2, 3],
              opCount: 3,
            },
            {
              id: 4,
              narration: "arr[4]=3 < arr[top=3]=4 — no pop. Push i=4.",
              variables: { stack: "[3,4]", ans: "[4,2,4,-1,-1]" },
              pointers: { i: 4 },
              highlight: [4],
              opCount: 4,
            },
            {
              id: 5,
              narration: "End of array. Remaining stack indices get -1. Answer: [4, 2, 4, -1, -1].",
              variables: { stack: "[]", ans: "[4,2,4,-1,-1]" },
              opCount: 5,
              done: true,
            },
          ],
        },
        {
          id: "brute",
          name: "Brute Force",
          time: "O(n²)",
          space: "O(1)",
          opsEstimate: (n) => n * n,
          defaultInput: { array: [2, 1, 2, 4, 3] },
          steps: [
            {
              id: 0,
              narration: "For each i, scan j=i+1..n until arr[j] > arr[i].",
              pointers: { i: 0, j: 1 },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=0: arr[1]=1 not > 2. j=2: arr[2]=2 not > 2. j=3: arr[3]=4 > 2. ans[0]=4.",
              pointers: { i: 0, j: 3 },
              variables: { ans: "[4,-1,-1,-1,-1]" },
              highlight: [0, 3],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=1: arr[2]=2 > 1. ans[1]=2.",
              pointers: { i: 1, j: 2 },
              variables: { ans: "[4,2,-1,-1,-1]" },
              highlight: [1, 2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=2: arr[3]=4 > 2. ans[2]=4.",
              pointers: { i: 2, j: 3 },
              variables: { ans: "[4,2,4,-1,-1]" },
              highlight: [2, 3],
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=3: scan j=4. arr[4]=3 not > 4. End. ans[3]=-1.",
              pointers: { i: 3, j: 4 },
              variables: { ans: "[4,2,4,-1,-1]" },
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=4: no j>i. ans[4]=-1. Done.",
              pointers: { i: 4 },
              variables: { ans: "[4,2,4,-1,-1]" },
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "largest-rectangle",
      title: "Largest Rectangle in Histogram",
      difficulty: "Hard",
      status: "live",
      description:
        "Given bar heights, find the largest rectangle that can fit inside the histogram.",
      problem:
        "Given an array of bar heights in a histogram (each bar has width 1), find the area of the largest rectangle that can be formed using a contiguous sequence of bars. Example: [2,1,5,6,2,3] → 10 (the rectangle with height 5 spanning bars 2 and 3). Edge cases: single bar, all same heights, strictly decreasing or increasing heights.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Google", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def largest_brute(heights):",
          "    n = len(heights)",
          "    best = 0",
          "    for i in range(n):",
          "        h = heights[i]",
          "        l = r = i",
          "        while l > 0 and heights[l - 1] >= h: l -= 1",
          "        while r < n - 1 and heights[r + 1] >= h: r += 1",
          "        best = max(best, h * (r - l + 1))",
          "    return best",
        ],
      },
      annotations: {
        5: "Brute: for each bar, expand left and right to find the max width where all bars are >= h, then update best.",
      },
      approaches: [
        {
          id: "monotonic",
          name: "Monotonic Stack (single pass)",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { heights: [2, 1, 5, 6, 2, 3] },
          steps: [
            {
              id: 0,
              narration: "Stack holds indices of bars in increasing height. Push i=0 (h=2).",
              variables: { stack: "[0]", max: 0 },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=1, h=1 < heights[0]=2 — pop 0. Compute area: h=2, width=1-(-1)-1=1, area=2. Push 1.",
              variables: { stack: "[1]", max: 2 },
              pointers: { i: 1 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=2, h=5 >= heights[1]=1 — push.",
              variables: { stack: "[1,2]", max: 2 },
              pointers: { i: 2 },
              highlight: [2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=3, h=6 >= heights[2]=5 — push.",
              variables: { stack: "[1,2,3]", max: 2 },
              pointers: { i: 3 },
              highlight: [3],
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=4, h=2 < heights[3]=6 — pop 3. Area: h=6, width=4-2-1=1, area=6. h=2 < heights[2]=5 — pop 2. Area: h=5, width=4-1-1=2, area=10. max=10.",
              variables: { stack: "[1,4]", max: 10 },
              pointers: { i: 4 },
              highlight: [2, 3],
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=5, h=3 >= heights[4]=2 — push.",
              variables: { stack: "[1,4,5]", max: 10 },
              pointers: { i: 5 },
              highlight: [5],
              opCount: 5,
            },
            {
              id: 6,
              narration: "End of array. Pop 5: width=6-4-1=1, area=3. Pop 4: width=6-1-1=4, area=8. Pop 1: width=6-(-1)-1=6, area=6.",
              variables: { stack: "[]", max: 10 },
              highlight: [2, 3],
              opCount: 6,
            },
            {
              id: 7,
              narration: "All bars drained. max=10 — bars at indices 2 and 3 form the rectangle 5×2.",
              variables: { stack: "[]", max: 10 },
              highlight: [2, 3],
              opCount: 7,
              done: true,
            },
          ],
        },
        {
          id: "brute",
          name: "Brute Force (per-bar expansion)",
          time: "O(n²)",
          space: "O(1)",
          opsEstimate: (n) => n * n,
          defaultInput: { heights: [2, 1, 5, 6, 2, 3] },
          steps: [
            {
              id: 0,
              narration: "For each bar i, expand left and right while heights >= heights[i].",
              pointers: { i: 0 },
              variables: { max: 0 },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=0, h=2: cannot expand left/right (h[1]=1 < 2). Area = 1×2 = 2.",
              pointers: { i: 0 },
              variables: { max: 2, area: 2 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=1, h=1: expand fully to width=6. Area = 6×1 = 6.",
              pointers: { i: 1 },
              variables: { max: 6, area: 6 },
              highlight: [0, 1, 2, 3, 4, 5],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=2, h=5: expand right until h[3]=6 OK, then h[4]=2 stops. Width=2. Area = 2×5 = 10. max=10.",
              pointers: { i: 2 },
              variables: { max: 10, area: 10 },
              highlight: [2, 3],
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=3, h=6: no expand. Area = 1×6 = 6.",
              pointers: { i: 3 },
              variables: { max: 10, area: 6 },
              highlight: [3],
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=4, h=2: expand to width=3 (indices 3..5 stopped by h[3]=6 boundary). Area=6.",
              pointers: { i: 4 },
              variables: { max: 10, area: 6 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "i=5, h=3: no expand. Area=3.",
              pointers: { i: 5 },
              variables: { max: 10, area: 3 },
              opCount: 6,
            },
            {
              id: 7,
              narration: "Done. Largest rectangle = 10 (bars at i=2,3).",
              variables: { max: 10 },
              highlight: [2, 3],
              opCount: 7,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "daily-temperatures",
      title: "Daily Temperatures",
      difficulty: "Easy",
      status: "live",
      description:
        "For each day, return how many days until a warmer temperature (0 if none).",
      problem:
        "Given a list of daily temperatures, return an array such that answer[i] is the number of days you have to wait until a warmer temperature. If there is no future day with a warmer temperature, set answer[i] = 0. Example: [73,74,75,71,69,72,76,73] → [1,1,4,2,1,1,0,0]. Edge cases: strictly decreasing temperatures (all 0s), single day (0).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def daily_brute(t):",
          "    n = len(t)",
          "    ans = [0] * n",
          "    for i in range(n):",
          "        for j in range(i + 1, n):",
          "            if t[j] > t[i]:",
          "                ans[i] = j - i",
          "                break",
          "    return ans",
        ],
      },
      annotations: {
        5: "Brute: for each i, scan rightward to find the next warmer day and record distance — O(n²).",
      },
      approaches: [
        {
          id: "monotonic",
          name: "Monotonic Stack",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { t: [55, 38, 83, 81, 84] },
          steps: [
            {
              id: 0,
              narration: "Stack holds day indices waiting for a warmer day. Push i=0 (55).",
              variables: { stack: "[(0,55)]", ans: "[0,0,0,0,0]" },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=1, t=38 < 55 — no pop (we want strictly greater). Push 1.",
              variables: { stack: "[(0,55),(1,38)]", ans: "[0,0,0,0,0]" },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=2, t=83 > 38 — pop 1, ans[1]=2-1=1. 83 > 55 — pop 0, ans[0]=2-0=2. Push 2.",
              variables: { stack: "[(2,83)]", ans: "[2,1,0,0,0]" },
              pointers: { i: 2 },
              highlight: [0, 1, 2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=3, t=81 < 83 — push 3.",
              variables: { stack: "[(2,83),(3,81)]", ans: "[2,1,0,0,0]" },
              pointers: { i: 3 },
              highlight: [3],
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=4, t=84 > 81 — pop 3, ans[3]=4-3=1. 84 > 83 — pop 2, ans[2]=4-2=2. Push 4.",
              variables: { stack: "[(4,84)]", ans: "[2,1,2,1,0]" },
              pointers: { i: 4 },
              highlight: [2, 3, 4],
              opCount: 4,
            },
            {
              id: 5,
              narration: "End of input. Remaining stack entries stay 0 (no warmer day). Answer: [2, 1, 2, 1, 0].",
              variables: { stack: "[(4,84)]", ans: "[2,1,2,1,0]" },
              opCount: 5,
              done: true,
            },
          ],
        },
      ],
    },
  ],
};
