import type { Pattern } from "@/types/content";

export const slidingWindow: Pattern = {
  slug: "sliding-window",
  title: "Sliding Window",
  tagline: "Maintain a moving window with O(1) updates.",
  status: "live",
  icon: "Square",
  topics: [
    {
      slug: "max-sum-subarray",
      title: "Max Sum Subarray of Size K",
      difficulty: "Easy",
      status: "live",
      description: "Find the maximum sum of any contiguous subarray of size k.",
      problem:
        "Given an array of positive integers `nums` and an integer `k`, find the maximum sum of any contiguous subarray of size exactly `k`. Example: `nums=[2,1,5,1,3,2], k=3` → 9 (subarray [5,1,3]). Edge cases: k equals the array length (just the total sum), k = 1 (the max element), and arrays containing zeros.",
      askedAt: ["Amazon", "Meta", "Microsoft"],
      code: {
        lang: "python",
        lines: [
          "def max_sum_subarray_brute(nums, k):",
          "    n = len(nums)",
          "    best = 0",
          "    for i in range(n - k + 1):",
          "        s = 0",
          "        for j in range(i, i + k):",
          "            s += nums[j]",
          "        best = max(best, s)",
          "    return best",
        ],
      },
      annotations: {
        4: "For each starting index i, sum the next k elements.",
        8: "Update the best sum across all subarrays.",
      },
      approaches: [
        {
          id: "brute",
          name: "Brute Force",
          time: "O(n*k)",
          space: "O(1)",
          opsEstimate: (n) => n * 3,
          defaultInput: { array: [2, 1, 5, 1, 3, 2], k: 3 },
          steps: [
            { id: 0, narration: "Sum first window [2,1,5] = 8.", pointers: { L: 0, R: 2 }, highlight: [0, 1, 2], variables: { sum: 8, max: 8 }, opCount: 1 },
            { id: 1, narration: "Slide to [1,5,1] = 7. max stays 8.", pointers: { L: 1, R: 3 }, highlight: [1, 2, 3], variables: { sum: 7, max: 8 }, opCount: 2 },
            { id: 2, narration: "Slide to [5,1,3] = 9. New max!", pointers: { L: 2, R: 4 }, highlight: [2, 3, 4], variables: { sum: 9, max: 9 }, opCount: 3 },
            { id: 3, narration: "Slide to [1,3,2] = 6. max=9.", pointers: { L: 3, R: 5 }, highlight: [3, 4, 5], variables: { sum: 6, max: 9 }, opCount: 4, done: true },
          ],
        },
        {
          id: "sliding",
          name: "Sliding Window",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [2, 1, 5, 1, 3, 2], k: 3 },
          steps: [
            { id: 0, narration: "Initial window [2,1,5]. sum=8, max=8.", pointers: { L: 0, R: 2 }, highlight: [0, 1, 2], variables: { sum: 8, max: 8 }, opCount: 1 },
            { id: 1, narration: "Add arr[R+1]=1 → sum=9. Subtract arr[L]=2 → sum=7. L++.", pointers: { L: 1, R: 3 }, highlight: [1, 2, 3], variables: { sum: 7, max: 8 }, opCount: 2 },
            { id: 2, narration: "Add 3, subtract 1 → sum=9. L++. max=9.", pointers: { L: 2, R: 4 }, highlight: [2, 3, 4], variables: { sum: 9, max: 9 }, opCount: 3 },
            { id: 3, narration: "Add 2, subtract 5 → sum=6. L++. End.", pointers: { L: 3, R: 5 }, highlight: [3, 4, 5], variables: { sum: 6, max: 9 }, opCount: 4, done: true },
          ],
        },
      ],
    },
    {
      slug: "longest-substring-no-repeat",
      title: "Longest Substring Without Repeating Characters",
      difficulty: "Medium",
      status: "live",
      description: "Find the length of the longest substring with all unique characters.",
      problem:
        "Given a string `s`, find the length of the longest substring without repeating characters. The substring is contiguous. Example: `s='abcabcbb'` → 3 (`'abc'`). `s='pwwkew'` → 3 (`'wke'`). The string consists of ASCII characters and may be up to 5·10^4 long. Edge cases: empty string (length 0), single character (length 1), all the same character (`bbbbb` → 1).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def length_of_longest_substring_brute(s):",
          "    n = len(s)",
          "    best = 0",
          "    for i in range(n):",
          "        seen = set()",
          "        for j in range(i, n):",
          "            if s[j] in seen: break",
          "            seen.add(s[j])",
          "        best = max(best, len(seen))",
          "    return best",
        ],
      },
      annotations: {
        5: "Expand the substring until a duplicate is hit.",
        8: "Each starting i yields a unique-character length; track the best.",
      },
      approaches: [
        {
          id: "hash",
          name: "Hash Map (last-seen index)",
          time: "O(n)",
          space: "O(min(n, alphabet))",
          opsEstimate: (n) => n,
          defaultInput: { s: "abcabcbb" },
          steps: [
            { id: 0, narration: "L=0,R=0. seen={}. max=0.", pointers: { L: 0, R: 0 }, variables: { seen: "{}", max: 0 }, opCount: 0 },
            { id: 1, narration: "Add 'a'. seen={a:0}. R++. window='a'. max=1.", pointers: { L: 0, R: 1 }, variables: { seen: "{a:0}", max: 1 }, opCount: 1 },
            { id: 2, narration: "Add 'b'. seen={a:0,b:1}. R++. window='ab'. max=2.", pointers: { L: 0, R: 2 }, variables: { seen: "{a:0,b:1}", max: 2 }, opCount: 2 },
            { id: 3, narration: "Add 'c'. seen={…,c:2}. R++. window='abc'. max=3.", pointers: { L: 0, R: 3 }, variables: { seen: "{a:0,b:1,c:2}", max: 3 }, opCount: 3 },
            { id: 4, narration: "Next is 'a' — already seen at 0. Jump L to 1.", pointers: { L: 1, R: 4 }, highlight: [1, 2, 3, 4], variables: { seen: "{a:0,b:1,c:2}", max: 3 }, opCount: 4 },
            { id: 5, narration: "Continue: 'b' at 1, jump L to 2. 'c' at 2, jump L to 3.", pointers: { L: 3, R: 7 }, highlight: [3, 4, 5, 6, 7], variables: { max: 3 }, opCount: 5, done: true },
          ],
        },
      ],
    },
    {
      slug: "min-window-substring",
      title: "Minimum Window Substring",
      difficulty: "Hard",
      status: "live",
      description: "Find the smallest substring of s that contains all characters of t.",
      problem:
        "Given two strings `s` and `t`, return the minimum-window substring of `s` such that every character in `t` (including duplicates) is included in the window. If no such window exists, return the empty string. Example: `s='ADOBECODEBANC', t='ABC'` → `'BANC'`. Both strings may be up to 10^5; `t` can be longer than `s` (return ''). Edge cases: empty t ('' is a window), t a single character, and s containing all of t.",
      askedAt: ["Amazon", "Microsoft", "Google", "Uber"],
      code: {
        lang: "python",
        lines: [
          "def min_window_brute(s, t):",
          "    from collections import Counter",
          "    need = Counter(t)",
          "    n = len(s)",
          "    best = ''",
          "    for i in range(n):",
          "        for j in range(i, n):",
          "            window = Counter(s[i:j+1])",
          "            if all(window[c] >= need[c] for c in t):",
          "                if best == '' or j - i + 1 < len(best):",
          "                    best = s[i:j+1]",
          "    return best",
        ],
      },
      annotations: {
        6: "Try every possible window [i..j].",
        8: "Check if the window contains all required letters with sufficient counts.",
        9: "Update best when we find a smaller window.",
      },
      approaches: [
        {
          id: "sliding",
          name: "Sliding Window + Counter",
          time: "O(n + m)",
          space: "O(min(n, alphabet))",
          opsEstimate: (n) => n,
          defaultInput: { s: "ADOBECODEBANC", t: "ABC" },
          steps: [
            { id: 0, narration: "Build need={A:1,B:1,C:1}. need=3, have=0.", variables: { need: "{A:1,B:1,C:1}", have: 0 }, opCount: 0 },
            { id: 1, narration: "Expand R. ADOBEC → A,B,C all hit. have=3. window=ADOBEC.", pointers: { L: 0, R: 5 }, highlight: [0, 1, 2, 3, 4, 5], variables: { window: "ADOBEC" }, opCount: 1 },
            { id: 2, narration: "Shrink L. Drop A → have=2. window=DOBEC.", pointers: { L: 1, R: 5 }, highlight: [1, 2, 3, 4, 5], variables: { window: "DOBEC" }, opCount: 2 },
            { id: 3, narration: "Move R. CODEBANC. Re-hit B,C. have=2 — wait for A.", pointers: { L: 1, R: 9 }, variables: { window: "DOBECODEBA" }, opCount: 3 },
            { id: 4, narration: "Reach A at idx=10. have=3 again. window=BANC.", pointers: { L: 6, R: 10 }, highlight: [6, 7, 8, 9, 10], variables: { window: "BANC", best: "BANC" }, opCount: 4, done: true },
          ],
        },
      ],
    },
    {
      slug: "max-sum-distinct-k",
      title: "Maximum Sum of Distinct Subarrays With Length K",
      difficulty: "Medium",
      status: "live",
      description: "Find the maximum sum of any k-length subarray containing no duplicates.",
      problem:
        "Given an integer array `nums` and an integer `k`, find the maximum sum of any contiguous subarray of length exactly k that contains no duplicate elements. Example: `nums=[1,5,4,2,9,9,9], k=3` → 11 (`[5,4,2]`, skipping `[2,9,9]` and `[9,9,9]`). Edge cases: arrays shorter than k (return 0), k = 1 (sum equals max element if no dupes), and inputs where duplicates make every k-window invalid.",
      askedAt: ["Amazon", "Google"],
      code: {
        lang: "python",
        lines: [
          "def max_sum_distinct_k_brute(nums, k):",
          "    n = len(nums)",
          "    best = 0",
          "    for i in range(n - k + 1):",
          "        window = nums[i:i+k]",
          "        if len(set(window)) == k:",
          "            best = max(best, sum(window))",
          "    return best",
        ],
      },
      annotations: {
        4: "Slice a candidate k-window.",
        5: "Skip windows that contain duplicates (set size < k).",
      },
      approaches: [
        {
          id: "freq-window",
          name: "Frequency Window",
          time: "O(n)",
          space: "O(min(n, k))",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 5, 4, 2, 9, 9, 9], k: 3 },
          steps: [
            { id: 0, narration: "Map keeps counts inside [L..R]. Sum slides with R++. Maintain distinct check.", variables: { freq: "{}", sum: 0, best: 0 }, pointers: { L: 0, R: -1 }, opCount: 0 },
            { id: 1, narration: "R=0, nums[0]=1. freq={1:1}. sum=1. distinct? yes.", variables: { freq: "{1}", sum: 1 }, pointers: { L: 0, R: 0 }, opCount: 1 },
            { id: 2, narration: "R=1, nums[1]=5. freq={1:1,5:1}. sum=6. window=2 wide.", variables: { freq: "{1,5}", sum: 6 }, pointers: { L: 0, R: 1 }, opCount: 2 },
            { id: 3, narration: "R=2, nums[2]=4. freq={1,5,4}. sum=10. window size = k=3. distinct ✓. best=10.", variables: { freq: "{1,5,4}", sum: 10, best: 10 }, pointers: { L: 0, R: 2 }, highlight: [0,1,2], opCount: 3 },
            { id: 4, narration: "Slide: drop nums[0]=1, sum=9. R=3: add nums[3]=2. sum=11. best=11.", variables: { freq: "{5,4,2}", sum: 11, best: 11 }, pointers: { L: 1, R: 3 }, highlight: [1,2,3], opCount: 4 },
            { id: 5, narration: "Slide: drop 5, add nums[4]=9. sum=15. freq={4,2,9}. best=15.", variables: { freq: "{4,2,9}", sum: 15, best: 15 }, pointers: { L: 2, R: 4 }, highlight: [2,3,4], opCount: 5 },
            { id: 6, narration: "Slide: drop 4, add nums[5]=9. freq={2,9:1→2}. Duplicate! Shrink L until distinct.", variables: { freq: "{2,9:2,...}", sum: 20 }, pointers: { L: 3, R: 5 }, highlight: [3,4,5], opCount: 6 },
            { id: 7, narration: "After shrinking L past both 9s: window too small. Best stays 15.", variables: { best: 15, answer: 15 }, opCount: 7, done: true },
          ],
        },
        {
          id: "set-window",
          name: "Set + Sliding Sum",
          time: "O(n)",
          space: "O(min(n, k))",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 5, 4, 2, 9, 9, 9], k: 3 },
          steps: [
            { id: 0, narration: "Maintain a set of the k elements currently in window. Try growing until duplicate; reset.", variables: { set: "{}", best: 0 }, opCount: 0 },
            { id: 1, narration: "Add 1, 5, 4. set={1,5,4}. sum=10. best=10.", variables: { set: "{1,5,4}", best: 10 }, opCount: 1 },
            { id: 2, narration: "Add 2 (window now [5,4,2]). sum=11. best=11.", variables: { set: "{5,4,2}", best: 11 }, opCount: 2 },
            { id: 3, narration: "Add 9 (window [4,2,9]). sum=15. best=15.", variables: { set: "{4,2,9}", best: 15 }, opCount: 3 },
            { id: 4, narration: "Add 9 again → duplicate. Reset window and try fresh start.", variables: { best: 15 }, opCount: 4, done: true },
          ],
        },
      ],
    },
    {
      slug: "permutation-in-string",
      title: "Permutation in String",
      difficulty: "Medium",
      status: "live",
      description: "Decide whether s2 contains a permutation of s1 as a substring.",
      problem:
        "Given two strings `s1` and `s2`, return true if `s2` contains a permutation of `s1`, or false otherwise. In other words, return true if one of `s1`'s permutations is a substring of `s2`. Strings consist of lowercase English letters and `s2` may be up to 10^4 long. Example: `s1='ab', s2='eidbaooo'` → true. Edge cases: `s1` longer than `s2` (false), `s1` is a single character, and `s2 = 'a'`.",
      askedAt: ["Amazon", "Microsoft", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def check_inclusion_brute(s1, s2):",
          "    from itertools import permutations",
          "    for p in permutations(s1):",
          "        if ''.join(p) in s2:",
          "            return True",
          "    return False",
        ],
      },
      annotations: {
        2: "Generate all permutations of s1 — only feasible for very short inputs.",
        3: "Check each permutation as a substring of s2.",
      },
      approaches: [
        {
          id: "fixed-count",
          name: "Fixed-Window + Counter Match",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { s1: "ab", s2: "eidbaooo" },
          steps: [
            { id: 0, narration: "need = {a:1,b:1}. Slide a window of length 2 across s2.", variables: { need: "{a:1,b:1}" }, opCount: 0 },
            { id: 1, narration: "Window 'ei': counts {e:1,i:1}. need mismatch → no.", variables: { window: "'ei'" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "Window 'id': mismatch → no.", variables: { window: "'id'" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "Window 'db': mismatch → no.", variables: { window: "'db'" }, pointers: { i: 2 }, opCount: 3 },
            { id: 4, narration: "Window 'ba': counts {b:1,a:1} == need → return true.", variables: { window: "'ba'", answer: "true" }, pointers: { i: 3 }, highlight: [3, 4], opCount: 4, done: true },
          ],
        },
        {
          id: "delta",
          name: "Counting Difference",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { s1: "ab", s2: "eidbaooo" },
          steps: [
            { id: 0, narration: "diff[c] = count in window − count in need. Slide; decrement when match, increment on remove.", variables: { diff: "{...}" }, opCount: 0 },
            { id: 1, narration: "Init with first 2 chars of s2: diff = {e:+1, i:+1, a:-1, b:-1}.", variables: { diff: "{e:+1,i:+1,a:-1,b:-1}" }, opCount: 1 },
            { id: 2, narration: "Slide: remove 'e', add 'd'. Adjust diff. all-zero? no.", variables: { diff: "{...}" }, opCount: 2 },
            { id: 3, narration: "Continue. At window 'ba': diff all 0 → match.", variables: { answer: "true" }, opCount: 3, done: true },
          ],
        },
      ],
    },
    {
      slug: "sliding-window-maximum",
      title: "Sliding Window Maximum",
      difficulty: "Hard",
      status: "live",
      description: "Compute the max in every k-length window as it slides across the array.",
      problem:
        "Given an integer array `nums` and a sliding window of size `k` that moves from left to right by one position at a time, return an array of the maximum in each window position. The runtime must be O(n). Example: `nums=[1,3,-1,-3,5,3,6,7], k=3` → `[3,3,5,5,6,7]`. Edge cases: k = 1 (output equals input), k equals array length (single max), and inputs with negative values only.",
      askedAt: ["Amazon", "Google", "Microsoft", "Citadel"],
      code: {
        lang: "python",
        lines: [
          "def max_sliding_window_brute(nums, k):",
          "    res = []",
          "    for i in range(len(nums) - k + 1):",
          "        res.append(max(nums[i:i+k]))",
          "    return res",
        ],
      },
      annotations: {
        3: "For each window starting at i, scan the k elements for the maximum.",
      },
      approaches: [
        {
          id: "deque",
          name: "Monotonic Deque",
          time: "O(n)",
          space: "O(k)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 3, -1, -3, 5, 3, 6, 7], k: 3 },
          steps: [
            { id: 0, narration: "Deque holds indices of candidates in decreasing order of nums[i].", variables: { dq: "[]", res: "[]" }, opCount: 0 },
            { id: 1, narration: "i=0, nums[0]=1. Pop while back<nums[i] (no). Push 0. dq=[0].", variables: { dq: "[0]" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "i=1, nums[1]=3 > nums[0]=1 → pop back. Push 1. dq=[1].", variables: { dq: "[1]" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "i=2, nums[2]=-1 < nums[1]=3 → push 2. dq=[1,2]. i-k+1=0, dq[0]=1 in window. Append nums[1]=3.", variables: { dq: "[1,2]", res: "[3]" }, pointers: { i: 2 }, highlight: [0,1,2], opCount: 3 },
            { id: 4, narration: "i=3, nums[3]=-3. Push. dq=[1,2,3]. i-k+1=1, window OK. nums[dq[0]]=3. Append.", variables: { dq: "[1,2,3]", res: "[3,3]" }, pointers: { i: 3 }, highlight: [1,2,3], opCount: 4 },
            { id: 5, narration: "i=4, nums[4]=5. Pop 3, 2 (all <5). dq=[1]. Push 4. dq=[1,4]. i-k+1=2, dq[0]=1 → in window. nums[dq[0]]=3 (still 3!). Append 3.", variables: { dq: "[1,4]", res: "[3,3,3]" }, pointers: { i: 4 }, highlight: [2,3,4], opCount: 5 },
            { id: 6, narration: "i=5: nums[5]=3 < nums[4]=5 → push. dq=[1,4,5]. i-k+1=3 → dq[0]=1 not in window; pop front.", variables: { dq: "[4,5]", res: "[3,3,3,5]" }, pointers: { i: 5 }, opCount: 6 },
            { id: 7, narration: "i=6: nums[6]=6 >5,>3. Pop,pop. dq=[4]. Push 6. dq=[4,6]. Append nums[4]=5.", variables: { dq: "[4,6]", res: "[3,3,3,5,5]" }, pointers: { i: 6 }, opCount: 7 },
            { id: 8, narration: "i=7: nums[7]=7 >6 → pop. dq=[4]. Push 7. dq=[4,7]. Window start=5. dq[0]=4 < 5. Pop front. dq=[7]. Append nums[7]=7.", variables: { dq: "[7]", res: "[3,3,3,5,5,6,7]" }, pointers: { i: 7 }, highlight: [5,6,7], opCount: 8, done: true },
          ],
        },
        {
          id: "heap",
          name: "Max-Heap (lazy deletion)",
          time: "O(n log k)",
          space: "O(k)",
          opsEstimate: (n) => n * Math.log2(Math.max(n, 2)),
          defaultInput: { array: [1, 3, -1, -3, 5, 3, 6, 7], k: 3 },
          steps: [
            { id: 0, narration: "Max-heap of (-val, idx) pairs. Top is window max; discard top if idx is out of window.", variables: { heap: "[]" }, opCount: 0 },
            { id: 1, narration: "Insert first k=3: (-1,0),(-3,1),(1,2). Heap top = -3 → idx=0. i=0 ↦ window starts at -2, idx 0 is out! Wait — values are (-val, idx); top is smallest key (largest val) = (-3,1). val=3. idx=1 ≥ 0 → in window.", variables: { heap: "[-3(1), -1(0), 1(2)]", res: "[3]" }, opCount: 1 },
            { id: 2, narration: "Slide: add nums[3]=-3. Top of heap val=3, idx=1 in window. Append.", variables: { heap: "[...]", res: "[3,3]" }, opCount: 2 },
            { id: 3, narration: "Continue. res grows to [3,3,3,5,5,6,7].", variables: { res: "[3,3,3,5,5,6,7]" }, opCount: 3, done: true },
          ],
        },
      ],
    },
  ],
};
