import type { Pattern } from "@/types/content";

export const stack: Pattern = {
  slug: "stack",
  title: "Stack",
  tagline: "LIFO: monotonic, matching, and eval stacks.",
  status: "live",
  icon: "Layers",
  topics: [
    {
      slug: "valid-parentheses",
      title: "Valid Parentheses",
      difficulty: "Easy",
      status: "live",
      description: "Check if a string of brackets is balanced and well-nested.",
      problem:
        "Given a string `s` containing just the characters '(){}[]', determine if the input string is valid — every opening bracket has a matching closing bracket of the same type, and brackets close in the correct nested order. Example: '()[]{}' → true; '([)]' → false. Edge cases: empty string (returns true), single character (returns false), and nested cases like '({[]})'.",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def is_valid_brute(s):",
          "    while '()' in s or '[]' in s or '{}' in s:",
          "        s = s.replace('()', '').replace('[]', '').replace('{}', '')",
          "    return s == ''",
        ],
      },
      annotations: {
        1: "Repeatedly strip adjacent matching pairs.",
        3: "If we end up with an empty string, all pairs were matched.",
      },
      approaches: [
        {
          id: "stack",
          name: "Stack",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { s: "()[]{}" },
          steps: [
            { id: 0, narration: "Stack empty.", variables: { stack: "[]" }, opCount: 0 },
            { id: 1, narration: "'(' is open — push.", variables: { stack: "['(']" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "')' matches '(' — pop.", variables: { stack: "[]" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "'[' — push.", variables: { stack: "['[']" }, pointers: { i: 2 }, opCount: 3 },
            { id: 4, narration: "']' matches — pop.", variables: { stack: "[]" }, pointers: { i: 3 }, opCount: 4 },
            { id: 5, narration: "'{' — push. '}' matches — pop. End. Valid.", variables: { stack: "[]" }, pointers: { i: 5 }, opCount: 5, done: true },
          ],
        },
      ],
    },
    {
      slug: "min-stack",
      title: "Min Stack",
      difficulty: "Easy",
      status: "live",
      description: "Design a stack that supports push, pop, top, and getMin in O(1).",
      problem:
        "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time O(1). Implement the MinStack class with the methods `push(val)`, `pop()`, `top()`, and `getMin()`. Example: `push(-2), push(0), push(-3), getMin() → -3, pop(), top() → 0, getMin() → -2`. Edge cases: popping the only element, pushing equal minimum values multiple times, and popping without pushing.",
      askedAt: ["Amazon", "Microsoft", "Snap"],
      code: {
        lang: "python",
        lines: [
          "class MinStack:",
          "    def __init__(self):",
          "        self.stack = []",
          "",
          "    def push(self, val):",
          "        cur_min = min(val, self.stack[-1][1] if self.stack else val)",
          "        self.stack.append((val, cur_min))",
        ],
      },
      annotations: {
        4: "Each stack frame stores both the value and the running minimum at that depth.",
        5: "The minimum after this push is min(val, current_min) — O(1).",
      },
      approaches: [
        {
          id: "two-stacks",
          name: "Two Stacks",
          time: "O(1) per op",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { ops: ["push(-2)","push(0)","push(-3)","getMin","pop","top","getMin"] },
          steps: [
            { id: 0, narration: "main=[], mins=[].", variables: { main: "[]", mins: "[]" }, opCount: 0 },
            { id: 1, narration: "push(-2). main=[-2], mins=[-2].", variables: { main: "[-2]", mins: "[-2]" }, opCount: 1 },
            { id: 2, narration: "push(0). main=[-2,0], mins=[-2,0]? No — min(-2,0)=-2. mins=[-2,-2].", variables: { main: "[-2,0]", mins: "[-2,-2]" }, opCount: 2 },
            { id: 3, narration: "push(-3). main=[-2,0,-3], mins=[-2,-2,-3].", variables: { main: "[-2,0,-3]", mins: "[-2,-2,-3]" }, opCount: 3 },
            { id: 4, narration: "getMin → mins.top = -3.", variables: { answer: "-3" }, opCount: 4 },
            { id: 5, narration: "pop -3. main=[-2,0], mins=[-2,-2].", variables: { main: "[-2,0]", mins: "[-2,-2]" }, opCount: 5 },
            { id: 6, narration: "top → main.top = 0. getMin → -2.", variables: { top: "0", min: "-2" }, opCount: 6, done: true },
          ],
        },
      ],
    },
    {
      slug: "daily-temperatures",
      title: "Daily Temperatures",
      difficulty: "Medium",
      status: "live",
      description: "For each day, how many days until a warmer temperature?",
      problem:
        "Given an array of integers `temperatures` representing daily temperatures, return an array `answer` where `answer[i]` is the number of days you must wait until a warmer temperature. If there is no future day with a warmer temperature, set `answer[i]=0`. Example: `[73,74,75,71,69,72,76,73]` → `[1,1,4,2,1,1,0,0]`. Edge cases: temperatures decreasing (all zeros except last), all equal (last is 0, others 0), and last element always 0.",
      askedAt: ["Amazon", "Microsoft", "Meta"],
      code: {
        lang: "python",
        lines: [
          "def daily_temperatures_brute(temps):",
          "    n = len(temps)",
          "    ans = [0] * n",
          "    for i in range(n):",
          "        for j in range(i + 1, n):",
          "            if temps[j] > temps[i]:",
          "                ans[i] = j - i",
          "                break",
          "    return ans",
        ],
      },
      annotations: {
        4: "For each day i, scan forward to find the next warmer day.",
        6: "Stop at the first warmer day; that's the answer for this day.",
      },
      approaches: [
        {
          id: "monotonic",
          name: "Monotonic Stack",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { t: [73, 74, 75, 71, 69, 72, 76, 73] },
          steps: [
            { id: 0, narration: "Push 73. stack=[(0,73)].", variables: { stack: "[(0,73)]" }, pointers: { i: 0 }, opCount: 0 },
            { id: 1, narration: "74 > 73 — pop 73, fill ans[0]=1. push (1,74).", variables: { stack: "[(1,74)]", ans: "[1,0,…]" }, pointers: { i: 1 }, opCount: 1 },
            { id: 2, narration: "75 > 74 — pop, ans[1]=1. push (2,75).", variables: { stack: "[(2,75)]", ans: "[1,1,…]" }, pointers: { i: 2 }, opCount: 2 },
            { id: 3, narration: "71 < 75 — push. stack=[(2,75),(3,71)].", variables: { stack: "[(2,75),(3,71)]" }, pointers: { i: 3 }, opCount: 3 },
            { id: 4, narration: "69 < 71 — push.", variables: { stack: "[(2,75),(3,71),(4,69)]" }, pointers: { i: 4 }, opCount: 4 },
            { id: 5, narration: "72 > 69 — pop(4,69), ans[4]=1. 72 > 71 — pop(3,71), ans[3]=2. push(5,72).", variables: { stack: "[(2,75),(5,72)]", ans: "[1,1,…,2,1]" }, pointers: { i: 5 }, opCount: 5, done: true },
          ],
        },
      ],
    },
    {
      slug: "decode-string",
      title: "Decode String",
      difficulty: "Medium",
      status: "live",
      description: "Decode an encoded string like '3[a2[c]]' using nested stacks.",
      problem:
        "Given an encoded string, return its decoded form. The encoding rule is: `k[encoded_string]`, where `encoded_string` inside the brackets is repeated exactly `k` times. Note that `k` is guaranteed to be a positive integer. Strings may be nested. Example: `'3[a2[c]]'` → `'accaccacc'`. Edge cases: empty brackets (skip), numbers larger than 9, and nested depth up to a few levels.",
      askedAt: ["Amazon", "Google", "Microsoft", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def decode_string_brute(s):",
          "    result = ''",
          "    i = 0",
          "    while i < len(s):",
          "        if s[i].isdigit():",
          "            j = i",
          "            while s[j].isdigit(): j += 1",
          "            k = int(s[i:j])",
          "            # find matching ']'",
          "            open_count = 1",
          "            inner_end = j + 1",
          "            while open_count > 0:",
          "                if s[inner_end] == '[': open_count += 1",
          "                if s[inner_end] == ']': open_count -= 1",
          "                inner_end += 1",
          "            inner = s[j + 1:inner_end - 1]",
          "            result += decode_string_brute(inner) * k",
          "            i = inner_end",
          "        else:",
          "            result += s[i]",
          "            i += 1",
          "    return result",
        ],
      },
      annotations: {
        5: "Parse the leading number k.",
        8: "Find the matching close bracket by counting nested brackets.",
        13: "Recurse on the inner encoded string and repeat k times.",
      },
      approaches: [
        {
          id: "two-stacks",
          name: "Two Stacks (count + string)",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { s: "3[a2[c]]" },
          steps: [
            { id: 0, narration: "Two stacks: countStack and resStack.", variables: { countStack: "[]", resStack: "[]", cur: "''" }, opCount: 0 },
            { id: 1, narration: "'3': push 3 to countStack. cur=''.", variables: { countStack: "[3]", cur: "''" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "'[': push cur='' to resStack. cur=''.", variables: { resStack: "[\"\"]", cur: "''" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "'a' literal → cur='a'.", variables: { cur: "'a'" }, pointers: { i: 2 }, opCount: 3 },
            { id: 4, narration: "'2': push 2 to countStack.", variables: { countStack: "[3,2]", cur: "'a'" }, pointers: { i: 3 }, opCount: 4 },
            { id: 5, narration: "'[': push cur='a' to resStack. cur=''.", variables: { resStack: "[\"\", 'a']", cur: "''" }, pointers: { i: 4 }, opCount: 5 },
            { id: 6, narration: "'c' literal → cur='c'.", variables: { cur: "'c'" }, pointers: { i: 5 }, opCount: 6 },
            { id: 7, narration: "']': pop top resStack 'a', top count 2 → cur = 'a' + 'c'*2 = 'acc'.", variables: { cur: "'acc'" }, pointers: { i: 6 }, opCount: 7 },
            { id: 8, narration: "']': pop top resStack '', top count 3 → cur = '' + 'acc'*3 = 'accaccacc'.", variables: { cur: "'accaccacc'", answer: "'accaccacc'" }, pointers: { i: 7 }, opCount: 8, done: true },
          ],
        },
        {
          id: "recursive",
          name: "Recursive Index-Walk",
          time: "O(n)",
          space: "O(d) depth",
          opsEstimate: (n) => n,
          defaultInput: { s: "3[a2[c]]" },
          steps: [
            { id: 0, narration: "Recursive helper(i). At '[' parse number, recurse to find ']', repeat, advance i.", variables: { i: 0 }, opCount: 0 },
            { id: 1, narration: "Parse '3[' → call helper on 'a2[c]]'.", variables: { i: 0 }, opCount: 1 },
            { id: 2, narration: "Inner helper: parse '2[' → recurse on 'c]'.", variables: { i: 2 }, opCount: 2 },
            { id: 3, narration: "Inner returns 'c', repeat 2 → 'cc'. i points past ']'.", variables: { inner: "'cc'" }, opCount: 3 },
            { id: 4, narration: "Outer: 'cc' * 3 → 'cccccc'… wait, suffix chars. Result = 'accaccacc'.", variables: { answer: "'accaccacc'" }, opCount: 4, done: true },
          ],
        },
      ],
    },
    {
      slug: "longest-valid-parens",
      title: "Longest Valid Parentheses",
      difficulty: "Hard",
      status: "live",
      description: "Find the length of the longest well-formed parenthesis substring.",
      problem:
        "Given a string `s` containing just '(' and ')', return the length of the longest well-formed (balanced) parentheses substring. A well-formed substring has each '(' matched with a subsequent ')' and the matches nest correctly. Example: '(()' → 2; ')()())' → 4; '' → 0. Edge cases: empty string (0), all ')' (0), and alternating (returns 2).",
      askedAt: ["Amazon", "Google", "Microsoft"],
      code: {
        lang: "python",
        lines: [
          "def longest_valid_parens_brute(s):",
          "    n = len(s)",
          "    best = 0",
          "    for i in range(n):",
          "        for j in range(i + 1, n + 1, 2):",
          "            sub = s[i:j]",
          "            stack = []",
          "            valid = True",
          "            for c in sub:",
          "                if c == '(': stack.append(c)",
          "                elif stack: stack.pop()",
          "                else: valid = False; break",
          "            if valid and not stack: best = max(best, len(sub))",
          "    return best",
        ],
      },
      annotations: {
        4: "Try every even-length substring starting at i.",
        10: "Validate using a stack; reject on mismatch or leftover items.",
      },
      approaches: [
        {
          id: "stack",
          name: "Stack of Indices",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { s: ")()())" },
          steps: [
            { id: 0, narration: "Push -1 as base. Then push indices; pop on ')'. Length = i - stack[-1].", variables: { stack: "[-1]" }, opCount: 0 },
            { id: 1, narration: "i=0, ')': stack[-1]=-1, push 0. stack=[-1, 0].", variables: { stack: "[-1, 0]" }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "i=1, '(' → push 1. stack=[-1, 0, 1].", variables: { stack: "[-1, 0, 1]" }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "i=2, ')' → pop 1. len = 2 - (-1) = 3? Wait: len = i - stack[-1] = 2 - 0 = 2.", variables: { stack: "[-1, 0]", best: 2 }, pointers: { i: 2 }, opCount: 3 },
            { id: 4, narration: "i=3, '(' → push 3. stack=[-1, 0, 3].", variables: { stack: "[-1, 0, 3]" }, pointers: { i: 3 }, opCount: 4 },
            { id: 5, narration: "i=4, ')' → pop 3. len = 4 - 0 = 4. best = 4.", variables: { stack: "[-1, 0]", best: 4 }, pointers: { i: 4 }, opCount: 5 },
            { id: 6, narration: "i=5, ')' → pop 0. len = 5 - (-1) = 6? No, len = i - stack[-1] = 5 - (-1) = 6, but substring ends at 5 not at end. best stays 4.", variables: { stack: "[-1]", best: 4 }, pointers: { i: 5 }, opCount: 6, done: true },
          ],
        },
        {
          id: "two-sweep",
          name: "Two Sweeps",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { s: ")()())" },
          steps: [
            { id: 0, narration: "Left→right: left=right=0, best=0. If ')' > '(' reset.", variables: { left: 0, right: 0, best: 0 }, opCount: 0 },
            { id: 1, narration: "':)' → right=1. right>left → reset, left=right=0.", variables: { left: 0, right: 0 }, pointers: { i: 0 }, opCount: 1 },
            { id: 2, narration: "'(': left=1. ')' : right=1. Match. best = 2.", variables: { left: 1, right: 1, best: 2 }, pointers: { i: 1 }, opCount: 2 },
            { id: 3, narration: "'(': left=2. ')' : right=2. best = 4.", variables: { left: 2, right: 2, best: 4 }, pointers: { i: 2 }, opCount: 3 },
            { id: 4, narration: "'(': left=3. ')' : right=3. best = 6.", variables: { left: 3, right: 3, best: 6 }, pointers: { i: 3 }, opCount: 4 },
            { id: 5, narration: "Final pass: same logic right→left. Clamp best correctly.", variables: { best: 4 }, opCount: 5, done: true },
          ],
        },
      ],
    },
    {
      slug: "evaluate-rpn",
      title: "Evaluate Reverse Polish Notation",
      difficulty: "Medium",
      status: "live",
      description: "Evaluate an arithmetic expression written in Reverse Polish Notation.",
      problem:
        "Evaluate the value of an arithmetic expression in Reverse Polish Notation (postfix). Valid operators are '+', '-', '*', '/'. Each operand may be an integer or another expression. Division should truncate toward zero. Example: `['2','1','+','3','*']` → 9 (equivalent to `((2+1)*3)`); `['4','13','5','/','+']` → 6 (4 + 13/5 = 4 + 2 = 6). Edge cases: single number (return it), expression with just two operands and one operator, and integer overflow handling.",
      askedAt: ["Amazon", "Google", "Microsoft"],
      code: {
        lang: "python",
        lines: [
          "def eval_rpn_brute(tokens):",
          "    from math import trunc",
          "    while len(tokens) > 1:",
          "        for i in range(len(tokens) - 2):",
          "            if tokens[i] in '+-*/' and not tokens[i+1].startswith(('+','-','*','/')) and not tokens[i+2].startswith(('+','-','*','/')):",
          "                a, b = int(tokens[i+1]), int(tokens[i+2])",
          "                if tokens[i] == '+': res = a + b",
          "                elif tokens[i] == '-': res = a - b",
          "                elif tokens[i] == '*': res = a * b",
          "                else: res = trunc(a / b)",
          "                tokens = tokens[:i] + [str(res)] + tokens[i+3:]",
          "                break",
          "    return int(tokens[0])",
        ],
      },
      annotations: {
        3: "Scan for the first operator with two numeric operands next to it.",
        14: "Replace those 3 tokens with the reduced result and continue.",
      },
      approaches: [
        {
          id: "stack",
          name: "Stack",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { tokens: ["2","1","+","3","*"] },
          steps: [
            { id: 0, narration: "stack=[].", variables: { stack: "[]" }, opCount: 0 },
            { id: 1, narration: "'2' → push 2.", variables: { stack: "[2]" }, opCount: 1 },
            { id: 2, narration: "'1' → push 1.", variables: { stack: "[2,1]" }, opCount: 2 },
            { id: 3, narration: "'+': pop 2,1 → 2+1=3 → push 3.", variables: { stack: "[3]" }, opCount: 3 },
            { id: 4, narration: "'3' → push 3.", variables: { stack: "[3,3]" }, opCount: 4 },
            { id: 5, narration: "'*': pop 3,3 → 9 → push 9.", variables: { stack: "[9]", answer: 9 }, opCount: 5, done: true },
          ],
        },
        {
          id: "reduce",
          name: "Reduce in Place",
          time: "O(n²)",
          space: "O(n)",
          opsEstimate: (n) => n * n,
          defaultInput: { tokens: ["2","1","+","3","*"] },
          steps: [
            { id: 0, narration: "Find first operator with two numbers, reduce, repeat.", variables: { tokens: "['2','1','+','3','*']" }, opCount: 0 },
            { id: 1, narration: "Reduce '2','1','+' → '3'.", variables: { tokens: "['3','3','*']" }, opCount: 1 },
            { id: 2, narration: "Reduce '3','3','*' → '9'. Done.", variables: { tokens: "['9']", answer: 9 }, opCount: 2, done: true },
          ],
        },
      ],
    },
  ],
};
