import type { Pattern } from "@/types/content";

export const trees: Pattern = {
  slug: "trees",
  title: "Trees",
  tagline: "DFS, BFS, and recursive decomposition.",
  status: "live",
  icon: "GitBranch",
  topics: [
    {
      slug: "max-depth",
      title: "Maximum Depth of Binary Tree",
      difficulty: "Easy",
      status: "live",
      description:
        "Return the number of nodes along the longest path from the root down to the farthest leaf.",
      problem:
        "Given the root of a binary tree, return its maximum depth — the number of nodes along the longest path from the root down to the farthest leaf. Example: [3,9,20,null,null,15,7] → 3. Edge cases: empty tree (depth 0), single node (depth 1), skewed left or right tree (depth = n).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Apple"],
      code: {
        lang: "python",
        lines: [
          "def max_depth_brute(root):",
          "    if root is None: return 0",
          "    from collections import deque",
          "    q = deque([(root, 1)])",
          "    best = 0",
          "    while q:",
          "        node, d = q.popleft()",
          "        best = max(best, d)",
          "        if node.left: q.append((node.left, d + 1))",
          "        if node.right: q.append((node.right, d + 1))",
          "    return best",
        ],
      },
      annotations: {
        3: "Brute: BFS level-by-level, tracking depth per node — O(n) but uses a queue.",
      },
      approaches: [
        {
          id: "dfs-recursive",
          name: "DFS Recursive",
          time: "O(n)",
          space: "O(h) call stack",
          opsEstimate: (n) => n,
          defaultInput: { t: [3, 9, 20, null, null, 15, 7] },
          steps: [
            {
              id: 0,
              narration: "Tree (level-order): 3 → (9, 20) → (null,null,15,7). depth(root)=1 + max(depth(L), depth(R)).",
              variables: { depth: "3", tree: "3(9,20(15,7))" },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Recurse left into 9. Its children are null → depth(9)=1.",
              pointers: { node: 1 },
              variables: { call: "depth(9)", depth: "1" },
              highlight: [1],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Back up: depth(9)=1. Now recurse right into 20.",
              pointers: { node: 2 },
              variables: { call: "depth(20)", left: "1" },
              highlight: [2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "At 20, recurse left into 15. 15 has no children → depth(15)=1.",
              pointers: { node: 4 },
              variables: { call: "depth(15)", depth: "1" },
              highlight: [4],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Back at 20, recurse right into 7. depth(7)=1.",
              pointers: { node: 5 },
              variables: { call: "depth(7)", depth: "1" },
              highlight: [5],
              opCount: 4,
            },
            {
              id: 5,
              narration: "depth(20) = 1 + max(1,1) = 2. Back at root: depth = 1 + max(1,2) = 3.",
              variables: { depth: "3", answer: "3" },
              highlight: [0],
              opCount: 5,
              done: true,
            },
          ],
        },
        {
          id: "bfs-iterative",
          name: "BFS Iterative",
          time: "O(n)",
          space: "O(w) queue",
          opsEstimate: (n) => n,
          defaultInput: { t: [3, 9, 20, null, null, 15, 7] },
          steps: [
            {
              id: 0,
              narration: "Queue starts with [(3, level 1)]. Each level increments depth by 1.",
              variables: { queue: "[(3,1)]", depth: "0" },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Process level 1: pop 3, push children 9 and 20 at level 2. depth=1.",
              variables: { queue: "[(9,2),(20,2)]", depth: "1" },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Process level 2: pop 9 (no kids), pop 20 (push 15 and 7 at level 3). depth=2.",
              variables: { queue: "[(15,3),(7,3)]", depth: "2" },
              highlight: [1, 2],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Process level 3: pop 15 (no kids), pop 7 (no kids). depth=3.",
              variables: { queue: "[]", depth: "3" },
              highlight: [4, 5],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Queue empty. Answer = 3.",
              variables: { queue: "[]", answer: "3" },
              opCount: 4,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "invert-tree",
      title: "Invert Binary Tree",
      difficulty: "Easy",
      status: "live",
      description:
        "Swap every node's left and right children to produce the mirror image of the tree.",
      problem:
        "Given the root of a binary tree, invert the tree (swap every left and right child) and return the root. Example: root=[4,2,7,1,3,6,9] → [4,7,2,9,6,3,1]. Edge cases: empty tree (return null), single node (return as-is), and asymmetric trees.",
      askedAt: ["Amazon", "Google", "Microsoft"],
      code: {
        lang: "python",
        lines: [
          "def invert_brute(root):",
          "    if root is None: return None",
          "    left = invert_brute(root.left)",
          "    right = invert_brute(root.right)",
          "    root.left = right",
          "    root.right = left",
          "    return root",
        ],
      },
      annotations: {
        2: "Brute: recursive — invert left, invert right, then swap them. Simple but uses call stack space.",
      },
      approaches: [
        {
          id: "dfs-recursive",
          name: "DFS Recursive",
          time: "O(n)",
          space: "O(h)",
          opsEstimate: (n) => n,
          defaultInput: { t: [4, 2, 7, 1, 3, 6, 9] },
          steps: [
            {
              id: 0,
              narration: "At root 4: swap children (L=2, R=7) → (L=7, R=2). Recurse on each.",
              pointers: { node: 0 },
              variables: { swap: "2↔7" },
              highlight: [0, 1, 2],
              opCount: 0,
            },
            {
              id: 1,
              narration: "At node 7 (now left): swap its kids (L=6, R=9) → (L=9, R=6).",
              pointers: { node: 2 },
              variables: { swap: "6↔9" },
              highlight: [2, 4, 5],
              opCount: 1,
            },
            {
              id: 2,
              narration: "At node 2 (now right): swap its kids (L=1, R=3) → (L=3, R=1).",
              pointers: { node: 1 },
              variables: { swap: "1↔3" },
              highlight: [1, 3, 4],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Leaves 9, 6, 3, 1 have no children — base case, nothing to swap.",
              pointers: { node: 3 },
              variables: { note: "leaves" },
              highlight: [3, 4, 5, 6],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Unwind. Tree is now: 4 → (7, 2) → (9, 6, 3, 1).",
              variables: { tree: "4(7(9,6),2(3,1))" },
              highlight: [0, 1, 2, 3, 4, 5, 6],
              opCount: 4,
              done: true,
            },
          ],
        },
        {
          id: "bfs",
          name: "BFS",
          time: "O(n)",
          space: "O(w)",
          opsEstimate: (n) => n,
          defaultInput: { t: [4, 2, 7, 1, 3, 6, 9] },
          steps: [
            {
              id: 0,
              narration: "Queue: [4]. Pop 4, swap its kids (2↔7), enqueue 7 and 2.",
              pointers: { node: 0 },
              variables: { queue: "[4]", swap: "2↔7" },
              highlight: [0, 1, 2],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Pop 7. Swap its kids (6↔9), enqueue 9 and 6.",
              pointers: { node: 2 },
              variables: { queue: "[2,7]", swap: "6↔9" },
              highlight: [2, 4, 5],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Pop 2. Swap its kids (1↔3), enqueue 3 and 1.",
              pointers: { node: 1 },
              variables: { queue: "[9,6,2]", swap: "1↔3" },
              highlight: [1, 3, 4],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Pop 9 — leaf, skip. Pop 6 — leaf, skip.",
              variables: { queue: "[3,1]" },
              highlight: [5, 6],
              opCount: 3,
            },
            {
              id: 4,
              narration: "Pop 3 — leaf. Pop 1 — leaf. Queue empty. Done.",
              variables: { queue: "[]", tree: "4(7(9,6),2(3,1))" },
              highlight: [0, 1, 2, 3, 4, 5, 6],
              opCount: 4,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "validate-bst",
      title: "Validate Binary Search Tree",
      difficulty: "Medium",
      status: "live",
      description:
        "Decide whether a binary tree is a valid BST: for every node, all left-descendants < node < all right-descendants.",
      problem:
        "Given the root of a binary tree, determine if it is a valid Binary Search Tree. A BST is valid if for every node, all keys in the left subtree are strictly less than the node's key and all keys in the right subtree are strictly greater. Example: [2,1,3] → true; [5,1,4,null,null,3,6] → false (3 is in the right subtree of 5 but less than 5). Edge cases: empty tree, single node, duplicates (must disallow).",
      askedAt: ["Amazon", "Microsoft", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def is_bst_brute(root):",
          "    vals = []",
          "    def inorder(n):",
          "        if not n: return",
          "        inorder(n.left)",
          "        vals.append(n.val)",
          "        inorder(n.right)",
          "    inorder(root)",
          "    return all(vals[i] < vals[i+1] for i in range(len(vals)-1))",
        ],
      },
      annotations: {
        9: "Brute: collect inorder traversal, then check it's strictly increasing — O(n) time, O(n) space for vals.",
      },
      approaches: [
        {
          id: "inorder",
          name: "Inorder Traversal",
          time: "O(n)",
          space: "O(h)",
          opsEstimate: (n) => n,
          defaultInput: { t: [5, 1, 4, null, null, 3, 6] },
          steps: [
            {
              id: 0,
              narration: "Inorder traversal of a valid BST yields strictly increasing values. Walk left, visit, walk right.",
              variables: { prev: "—", traversal: "[]" },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Go left to 1. No left child. Visit 1. prev=1.",
              pointers: { node: 1 },
              variables: { prev: "1", traversal: "[1]" },
              highlight: [1],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Visit root 5. 5 > prev=1 ✓. prev=5.",
              pointers: { node: 0 },
              variables: { prev: "5", traversal: "[1,5]" },
              highlight: [0],
              opCount: 2,
            },
            {
              id: 3,
              narration: "Go right to 4. Visit 4. 4 < prev=5 ✗ — invalid BST!",
              pointers: { node: 2 },
              variables: { prev: "4", traversal: "[1,5,4]", valid: "false" },
              highlight: [0, 2],
              opCount: 3,
              done: true,
            },
          ],
        },
        {
          id: "recurse-bounds",
          name: "Recursive with min/max bounds",
          time: "O(n)",
          space: "O(h)",
          opsEstimate: (n) => n,
          defaultInput: { t: [5, 1, 4, null, null, 3, 6] },
          steps: [
            {
              id: 0,
              narration: "Each subtree must lie in (min, max). Root 5 gets bounds (-∞, +∞).",
              pointers: { node: 0 },
              variables: { bounds: "(-∞, +∞)" },
              highlight: [0],
              opCount: 0,
            },
            {
              id: 1,
              narration: "Left subtree of 5: bounds (-∞, 5). Visit 1 — 1 in range. Recurse with bounds (-∞, 5).",
              pointers: { node: 1 },
              variables: { bounds: "(-∞, 5)", ok: "✓" },
              highlight: [1],
              opCount: 1,
            },
            {
              id: 2,
              narration: "Right subtree of 5: bounds (5, +∞). Visit 4 — 4 < 5 ✗ — invalid!",
              pointers: { node: 2 },
              variables: { bounds: "(5, +∞)", ok: "✗", valid: "false" },
              highlight: [0, 2],
              opCount: 2,
              done: true,
            },
          ],
        },
      ],
    },
  ],
};
