import type { Pattern } from "@/types/content";

export const twoPointers: Pattern = {
  slug: "two-pointers",
  title: "Two Pointers",
  tagline: "Sweep two indices to cut O(n²) down to O(n).",
  status: "live",
  icon: "ArrowLeftRight",
  topics: [
    {
      slug: "two-sum",
      title: "Two Sum (sorted array)",
      difficulty: "Easy",
      status: "live",
      description:
        "Given a sorted array and a target, find two numbers that add to the target.",
      problem:
        "Given a 1-indexed sorted array of integers `nums` (already sorted in non-decreasing order) and a `target`, return the 1-indexed positions of two numbers that add up to `target`. Each input has exactly one solution, and you cannot use the same element twice. Example: `nums=[1,3,4,5,7,11,16], target=14` returns `[2,6]` (3 + 11). Edge cases: target equals twice an element, target smaller than the smallest pair, and target larger than the sum of all positive pairs.",
      askedAt: ["Amazon", "Google", "Meta"],
      code: {
        lang: "python",
        lines: [
          "def two_sum_brute(nums, target):",
          "    n = len(nums)",
          "    for i in range(n):",
          "        for j in range(i + 1, n):",
          "            if nums[i] + nums[j] == target:",
          "                return [i, j]",
          "    return []",
        ],
      },
      annotations: {
        3: "Pair i with every later j; we never revisit past pairs.",
        5: "Stop at the first match — only one valid pair is guaranteed.",
      },
      approaches: [
        {
          id: "brute",
          name: "Brute Force",
          time: "O(n²)",
          space: "O(1)",
          opsEstimate: (n) => n * n,
          defaultInput: { array: [1, 3, 4, 5, 7, 11, 16], target: 14 },
          steps: [
            {
              id: 0,
              narration: "Try every pair (i, j).",
              pointers: { i: 0, j: 1 },
              highlight: [0, 1],
              opCount: 0,
            },
            {
              id: 1,
              narration: "1 + 3 = 4 < 14. Move j forward.",
              pointers: { i: 0, j: 2 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "1 + 4 = 5 < 14. Move j forward.",
              pointers: { i: 0, j: 3 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "1 + 5 = 6 < 14. Move j forward.",
              pointers: { i: 0, j: 4 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "1 + 7 = 8 < 14. Move j forward.",
              pointers: { i: 0, j: 5 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "1 + 11 = 12 < 14. Move j forward.",
              pointers: { i: 0, j: 6 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "1 + 16 = 17 > 14. Reset j and move i.",
              pointers: { i: 1, j: 6 },
              opCount: 6,
            },
            {
              id: 7,
              narration: "3 + 11 = 14 == target. Found it!",
              pointers: { i: 1, j: 5 },
              highlight: [1, 5],
              opCount: 12,
              done: true,
            },
          ],
        },
        {
          id: "two-pointers",
          name: "Sort + Two Pointers",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 3, 4, 5, 7, 11, 16], target: 14 },
          steps: [
            {
              id: 0,
              narration: "Place L at start, R at end.",
              pointers: { L: 0, R: 6 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "1 + 16 = 17 > 14 — move R in.",
              pointers: { L: 0, R: 5 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "1 + 11 = 12 < 14 — move L out.",
              pointers: { L: 1, R: 5 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "3 + 11 = 14 == target. Found.",
              pointers: { L: 1, R: 5 },
              highlight: [1, 5],
              opCount: 3,
              done: true,
            },
          ],
        },
        {
          id: "hash",
          name: "Hash Map",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 3, 4, 5, 7, 11, 16], target: 14 },
          steps: [
            {
              id: 0,
              narration: "Initialize empty map.",
              variables: { map: "{}" },
              opCount: 0,
            },
            {
              id: 1,
              narration: "i=0: need 13. Insert 1.",
              variables: { map: "{1→0}" },
              pointers: { i: 0 },
              highlight: [0],
              opCount: 1,
            },
            {
              id: 2,
              narration: "i=1: need 11. Insert 3.",
              variables: { map: "{1→0, 3→1}" },
              pointers: { i: 1 },
              highlight: [1],
              opCount: 2,
            },
            {
              id: 3,
              narration: "i=2: need 10. Insert 4.",
              variables: { map: "{1→0, 3→1, 4→2}" },
              pointers: { i: 2 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "i=3: need 9. Insert 5.",
              variables: { map: "{1→0, 3→1, 4→2, 5→3}" },
              pointers: { i: 3 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "i=4: need 7. Insert 7.",
              variables: { map: "{1→0, 3→1, 4→2, 5→3, 7→4}" },
              pointers: { i: 4 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "i=5: need 3. Hit! 11 + 3 = 14.",
              variables: { map: "{1→0, 3→1, 4→2, 5→3, 7→4}" },
              pointers: { i: 5 },
              highlight: [1, 5],
              opCount: 6,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "three-sum",
      title: "3Sum",
      difficulty: "Medium",
      status: "live",
      description:
        "Find all unique triplets in an array that sum to zero.",
      problem:
        "Given an integer array `nums`, return all triplets `[nums[i], nums[j], nums[k]]` such that `i != j != k` and the three numbers sum to zero. The solution set must not contain duplicate triplets, and can be returned in any order. Example: `nums=[-1,0,1,2,-1,-4]` returns `[[-1,-1,2],[-1,0,1]]`. Edge cases: arrays shorter than 3 elements (return []), all-zero arrays (return [[0,0,0]] at most once), and inputs with multiple equal values that must be deduplicated.",
      askedAt: ["Amazon", "Meta", "Google", "Adobe"],
      code: {
        lang: "python",
        lines: [
          "def three_sum_brute(nums):",
          "    n = len(nums)",
          "    res = set()",
          "    for i in range(n):",
          "        for j in range(i + 1, n):",
          "            for k in range(j + 1, n):",
          "                if nums[i] + nums[j] + nums[k] == 0:",
          "                    res.add(tuple(sorted([nums[i], nums[j], nums[k]])))",
          "    return [list(t) for t in res]",
        ],
      },
      annotations: {
        3: "Enumerate every distinct triplet of indices, three at a time.",
        7: "Sort the values to canonicalize a triplet before adding it to the set.",
        8: "Convert the set of tuples to a list-of-lists for return.",
      },
      approaches: [
        {
          id: "two-pointers",
          name: "Sort + Two Pointers",
          time: "O(n²)",
          space: "O(1)",
          opsEstimate: (n) => n * n,
          defaultInput: { array: [-4, -1, -1, 0, 1, 2], target: 0 },
          steps: [
            {
              id: 0,
              narration: "Sort the array, then for each i sweep L/R.",
              pointers: { i: 0, L: 1, R: 5 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "-4 + (-1) + 2 = -3 < 0. Move L.",
              pointers: { i: 0, L: 2, R: 5 },
              opCount: 1,
            },
            {
              id: 2,
              narration: "-4 + (-1) + 2 = -3 < 0. Move L.",
              pointers: { i: 0, L: 3, R: 5 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "-4 + 0 + 2 = -2 < 0. Move L.",
              pointers: { i: 0, L: 4, R: 5 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "-4 + 1 + 2 = -1 < 0. Move L.",
              pointers: { i: 0, L: 5, R: 5 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "L meets R. Next i.",
              pointers: { i: 1, L: 2, R: 5 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "-1 + (-1) + 2 = 0. Found triplet!",
              pointers: { i: 1, L: 2, R: 5 },
              highlight: [1, 2, 5],
              opCount: 6,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "container-water",
      title: "Container With Most Water",
      difficulty: "Medium",
      status: "live",
      description:
        "Find two lines that together with the x-axis form a container holding the most water.",
      problem:
        "Given an integer array `height` of length n where each entry is the height of a vertical line at that x-coordinate, find two lines that together with the x-axis form a container that holds the most water. The container area between lines i and j is `min(height[i], height[j]) * (j - i)`. Example: `[1,8,6,2,5,4,8,3,7]` → 49 (between indices 1 and 8). Edge cases: arrays of length 2 (just one pair), arrays with equal heights throughout, and inputs where the max area is at the extremes.",
      askedAt: ["Amazon", "Google", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def max_area_brute(height):",
          "    best = 0",
          "    for i in range(len(height)):",
          "        for j in range(i + 1, len(height)):",
          "            area = min(height[i], height[j]) * (j - i)",
          "            if area > best: best = area",
          "    return best",
        ],
      },
      annotations: {
        4: "Area depends on the shorter wall and the distance — both must be checked.",
        5: "Take the maximum area found across all (i, j) pairs.",
      },
      approaches: [
        {
          id: "two-pointers",
          name: "Two Pointers",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [1, 8, 6, 2, 5, 4, 8, 3, 7], target: 0 },
          steps: [
            {
              id: 0,
              narration: "L=0, R=8. Width=8, area=1*8=8.",
              pointers: { L: 0, R: 8 },
              variables: { area: 8, max: 8 },
              opCount: 0,
            },
            {
              id: 1,
              narration: "1<7. Move L. Width=7, area=min(8,7)*7=49.",
              pointers: { L: 1, R: 8 },
              variables: { area: 49, max: 49 },
              highlight: [1, 8],
              opCount: 1,
            },
            {
              id: 2,
              narration: "8>3. Move R. Width=6, area=min(8,3)*6=18.",
              pointers: { L: 1, R: 7 },
              variables: { area: 18, max: 49 },
              opCount: 2,
            },
            {
              id: 3,
              narration: "8>7. Move R. Width=5, area=min(8,7)*5=35.",
              pointers: { L: 1, R: 6 },
              variables: { area: 35, max: 49 },
              opCount: 3,
            },
            {
              id: 4,
              narration: "8==8. Move R. Width=4, area=min(8,2)*4=8.",
              pointers: { L: 1, R: 5 },
              variables: { area: 8, max: 49 },
              opCount: 4,
            },
            {
              id: 5,
              narration: "8>5. Move R. Width=3, area=min(8,5)*3=15.",
              pointers: { L: 1, R: 4 },
              variables: { area: 15, max: 49 },
              opCount: 5,
            },
            {
              id: 6,
              narration: "8>2. Move R. Width=2, area=min(8,2)*2=4.",
              pointers: { L: 1, R: 3 },
              variables: { area: 4, max: 49 },
              opCount: 6,
            },
            {
              id: 7,
              narration: "8>6. Move R. Width=1, area=8.",
              pointers: { L: 1, R: 2 },
              variables: { area: 8, max: 49 },
              opCount: 7,
              done: true,
            },
          ],
        },
      ],
    },
    {
      slug: "valid-palindrome",
      title: "Valid Palindrome",
      difficulty: "Easy",
      status: "live",
      description: "Decide if a string reads the same forward and backward (ignoring non-alphanumeric).",
      problem:
        "Given a string `s`, return `true` if it is a palindrome after removing all non-alphanumeric characters and treating uppercase as lowercase. Example: `'A man, a plan, a canal: Panama'` → `true`. `race a car` → `false`. The input length is at most 2·10^5. Edge cases: empty string (returns `true`), strings with all punctuation or spaces, and strings of length 1.",
      askedAt: ["Amazon", "Microsoft", "Meta"],
      code: {
        lang: "python",
        lines: [
          "def is_palindrome_brute(s):",
          "    t = ''.join(c.lower() for c in s if c.isalnum())",
          "    n = len(t)",
          "    for i in range(n // 2):",
          "        if t[i] != t[n - 1 - i]:",
          "            return False",
          "    return True",
        ],
      },
      annotations: {
        2: "Filter out non-alphanumeric characters and normalize case in one pass.",
        4: "Compare the first half to the reversed second half — half the comparisons.",
      },
      approaches: [
        {
          id: "two-pointers",
          name: "Two Pointers",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { s: "A man, a plan, a canal: Panama" },
          steps: [
            { id: 0, narration: "L at index 0, R at last index. Skip non-alphanumerics.", pointers: { L: 0, R: 29 }, variables: { s: "'A man,…'" }, opCount: 0 },
            { id: 1, narration: "'A'.lower()='a' vs 'a'. Match. L++ → ' ' (skip). R-- → 'm'.", pointers: { L: 2, R: 28 }, variables: { s: "A_man…" }, opCount: 1 },
            { id: 2, narration: "'m' vs 'm'. Match. L→a, R→a.", pointers: { L: 2, R: 25 }, variables: { s: "..." }, opCount: 2 },
            { id: 3, narration: "Continue matching a↔a, n↔n, a↔a, … center reached.", pointers: { L: 14, R: 14 }, opCount: 3 },
            { id: 4, narration: "L >= R without mismatch. Palindrome!", variables: { answer: "true" }, opCount: 4, done: true },
          ],
        },
        {
          id: "reverse",
          name: "Reverse & Compare",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { s: "A man, a plan, a canal: Panama" },
          steps: [
            { id: 0, narration: "Build filtered string t='amanaplanacanalpanama'.", variables: { t: "'amanaplanacanalpanama'" }, opCount: 0 },
            { id: 1, narration: "t[::-1] = same string (palindrome).", variables: { rev: "'amanaplanacanalpanama'" }, opCount: 1 },
            { id: 2, narration: "t == rev → true.", variables: { answer: "true" }, opCount: 2, done: true },
          ],
        },
      ],
    },
    {
      slug: "move-zeroes",
      title: "Move Zeroes",
      difficulty: "Easy",
      status: "live",
      description: "Move all zeros to the end while preserving the order of non-zero elements, in place.",
      problem:
        "Given an integer array `nums`, move all `0`'s to the end of it while maintaining the relative order of the non-zero elements. The modification must happen in place without making a copy of the array. Example: `[0,1,0,3,12]` → `[1,3,12,0,0]`. Edge cases: arrays already with all non-zeros (no change), arrays of all zeros, and arrays where zeros are already at the end.",
      askedAt: ["Amazon", "Meta", "Apple"],
      code: {
        lang: "python",
        lines: [
          "def move_zeroes_brute(nums):",
          "    result = []",
          "    zero_count = 0",
          "    for x in nums:",
          "        if x != 0: result.append(x)",
          "        else: zero_count += 1",
          "    return result + [0] * zero_count",
        ],
      },
      annotations: {
        5: "Partition non-zero values into the output list, preserving order.",
        6: "Count zeros that get appended at the end.",
        7: "Concatenate, padding with the zeros at the back.",
      },
      approaches: [
        {
          id: "two-pass",
          name: "Two Pointers (snowball)",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [0, 1, 0, 3, 12] },
          steps: [
            { id: 0, narration: "snowball=0 — count of zeros seen in current window.", variables: { snowball: 0 }, pointers: { i: 0 }, opCount: 0 },
            { id: 1, narration: "i=0, nums[0]=0. snowball=1. Slide window.", variables: { snowball: 1 }, pointers: { i: 0 }, highlight: [0], opCount: 1 },
            { id: 2, narration: "i=1, nums[1]=1. Swap left zero with this 1 → nums=[1,0,0,3,12].", variables: { snowball: 1 }, pointers: { i: 1 }, highlight: [0, 1], opCount: 2 },
            { id: 3, narration: "i=2, nums[2]=0. snowball=2 (window has 2 zeros).", variables: { snowball: 2 }, pointers: { i: 2 }, highlight: [1, 2], opCount: 3 },
            { id: 4, narration: "i=3, nums[3]=3. Swap with first 0. nums=[1,3,0,0,12]. snowball=2.", variables: { snowball: 2 }, pointers: { i: 3 }, highlight: [1, 3], opCount: 4 },
            { id: 5, narration: "i=4, nums[4]=12. Swap. nums=[1,3,12,0,0]. Done.", variables: { snowball: 2 }, highlight: [2, 4], opCount: 5, done: true },
          ],
        },
        {
          id: "fill-and-zero",
          name: "Fill Then Zero",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [0, 1, 0, 3, 12] },
          steps: [
            { id: 0, narration: "Write non-zeros to the front, tracking insertIdx.", pointers: { insertIdx: 0 }, variables: { array: "[0,1,0,3,12]" }, opCount: 0 },
            { id: 1, narration: "i=0: zero, skip.", variables: { array: "[0,1,0,3,12]" }, pointers: { i: 0, insertIdx: 0 }, opCount: 1 },
            { id: 2, narration: "i=1: 1 is non-zero. array[insertIdx]=1; insertIdx=1.", variables: { array: "[1,1,0,3,12]" }, pointers: { i: 1, insertIdx: 1 }, highlight: [0], opCount: 2 },
            { id: 3, narration: "i=2: zero, skip.", variables: { array: "[1,1,0,3,12]" }, pointers: { i: 2, insertIdx: 1 }, opCount: 3 },
            { id: 4, narration: "i=3: 3 non-zero. array[1]=3; insertIdx=2.", variables: { array: "[1,3,0,3,12]" }, pointers: { i: 3, insertIdx: 2 }, highlight: [1], opCount: 4 },
            { id: 5, narration: "i=4: 12 non-zero. array[2]=12; insertIdx=3.", variables: { array: "[1,3,12,3,12]" }, pointers: { i: 4, insertIdx: 3 }, highlight: [2], opCount: 5 },
            { id: 6, narration: "Fill from insertIdx to end with zeros: array[3]=0, array[4]=0.", variables: { array: "[1,3,12,0,0]" }, pointers: { insertIdx: 3 }, opCount: 6, done: true },
          ],
        },
      ],
    },
    {
      slug: "sort-colors",
      title: "Sort Colors",
      difficulty: "Medium",
      status: "live",
      description: "Sort an array of 0, 1, 2 in place using constant extra space.",
      problem:
        "Given an array `nums` containing only the integers 0, 1, and 2, sort it in place so that equal values are adjacent, with 0s first, then 1s, then 2s. Use a one-pass algorithm with O(1) extra space. Example: `[2,0,2,1,1,0]` → `[0,0,1,1,2,2]`. Edge cases: already sorted arrays, arrays with only one or two distinct colors, and inputs with all 2s.",
      askedAt: ["Amazon", "Microsoft", "Google"],
      code: {
        lang: "python",
        lines: [
          "def sort_colors_brute(nums):",
          "    counts = [0, 0, 0]",
          "    for x in nums:",
          "        counts[x] += 1",
          "    idx = 0",
          "    for color in range(3):",
          "        for _ in range(counts[color]):",
          "            nums[idx] = color",
          "            idx += 1",
        ],
      },
      annotations: {
        4: "Bucket each color into one of three counters.",
        6: "Write each color back into the array a known number of times.",
      },
      approaches: [
        {
          id: "dutch-flag",
          name: "Dutch National Flag (3-way partition)",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [2, 0, 2, 1, 1, 0] },
          steps: [
            { id: 0, narration: "three-way partition: region [0..low-1] are 0s, [low..mid-1] are 1s, [high+1..end] are 2s.", variables: { low: 0, mid: 0, high: 5 }, pointers: { mid: 0 }, highlight: [0,5], opCount: 0 },
            { id: 1, narration: "mid=0, nums[0]=2. Swap mid↔high=5. high--. → [0,0,2,1,1,2].", variables: { low: 0, mid: 0, high: 4 }, pointers: { mid: 0 }, highlight: [0, 5], opCount: 1 },
            { id: 2, narration: "mid=0, nums[0]=0. Swap mid↔low. low++, mid++. → [0,0,2,1,1,2].", variables: { low: 1, mid: 1, high: 4 }, highlight: [0, 1], opCount: 2 },
            { id: 3, narration: "mid=1, nums[1]=0. Swap mid↔low=1. low++, mid++. → [0,0,2,1,1,2].", variables: { low: 2, mid: 2, high: 4 }, highlight: [1, 2], opCount: 3 },
            { id: 4, narration: "mid=2, nums[2]=2. Swap mid↔high=4. high--.", variables: { low: 2, mid: 2, high: 3 }, highlight: [2, 4], opCount: 4 },
            { id: 5, narration: "mid=2, nums[2]=2. Swap mid↔high=3. high--.", variables: { low: 2, mid: 2, high: 2 }, highlight: [2, 3], opCount: 5 },
            { id: 6, narration: "mid=2, nums[2]=1. Just mid++. → [0,0,1,1,2,2].", variables: { low: 2, mid: 3, high: 2 }, highlight: [2, 3], opCount: 6 },
            { id: 7, narration: "mid > high. Sorted!", variables: { array: "[0,0,1,1,2,2]" }, opCount: 7, done: true },
          ],
        },
        {
          id: "count-sort",
          name: "Counting Sort",
          time: "O(n)",
          space: "O(1) (3 keys)",
          opsEstimate: (n) => n,
          defaultInput: { array: [2, 0, 2, 1, 1, 0] },
          steps: [
            { id: 0, narration: "Count zeros, ones, twos. counts = [2, 2, 2].", variables: { counts: "[2,2,2]" }, opCount: 0 },
            { id: 1, narration: "Overwrite array: 0,0 then 1,1 then 2,2.", variables: { array: "[0,0,1,1,2,2]" }, highlight: [0,1,2,3,4,5], opCount: 1, done: true },
          ],
        },
      ],
    },
    {
      slug: "trapping-rain-water",
      title: "Trapping Rain Water",
      difficulty: "Hard",
      status: "live",
      description: "Compute how much water the bars can trap between them.",
      problem:
        "Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining. Example: `[0,1,0,2,1,0,1,3,2,1,2,1]` → 6. Constraints: n ≤ 2·10^5, height[i] ≤ 10^5. Edge cases: flat arrays (0 water), strictly decreasing arrays (0 water), and inputs with a single peak trapping maximum water.",
      askedAt: ["Amazon", "Google", "Meta", "Bloomberg"],
      code: {
        lang: "python",
        lines: [
          "def trap_brute(height):",
          "    total = 0",
          "    n = len(height)",
          "    for i in range(n):",
          "        left = max(height[:i + 1])",
          "        right = max(height[i:])",
          "        water = min(left, right) - height[i]",
          "        if water > 0: total += water",
          "    return total",
        ],
      },
      annotations: {
        4: "Compute the max on both sides — rescans are expensive.",
        5: "Water at i is the min of the two boundaries minus the bar's own height.",
      },
      approaches: [
        {
          id: "two-pointers",
          name: "Two Pointers",
          time: "O(n)",
          space: "O(1)",
          opsEstimate: (n) => n,
          defaultInput: { array: [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1] },
          steps: [
            { id: 0, narration: "L=0, R=11. Track max on each side as we move.", pointers: { L: 0, R: 11 }, variables: { lMax: 0, rMax: 0, water: 0 }, opCount: 0 },
            { id: 1, narration: "h[L]=0 < h[R]=1. lMax=0. Water += 0-0=0. L++.", pointers: { L: 1, R: 11 }, variables: { lMax: 0 }, opCount: 1 },
            { id: 2, narration: "h[L]=1 < h[R]=1 → move L. lMax=1.", pointers: { L: 2, R: 11 }, variables: { lMax: 1 }, opCount: 2 },
            { id: 3, narration: "h[L]=0 < h[R]=1. Water += min(1,?) - 0 = 1. L++. water=1.", pointers: { L: 3, R: 11 }, variables: { lMax: 1, water: 1 }, highlight: [2], opCount: 3 },
            { id: 4, narration: "h[L]=2 > h[R]=1 → move R. rMax=1.", pointers: { L: 3, R: 10 }, variables: { rMax: 1 }, opCount: 4 },
            { id: 5, narration: "h[L]=2 ≤ h[R]=2 → move L. lMax=2.", pointers: { L: 4, R: 10 }, variables: { lMax: 2 }, opCount: 5 },
            { id: 6, narration: "h[L]=1 < h[R]=2. Water += min(2,2)-1 = 1. water=2. L++.", pointers: { L: 5, R: 10 }, variables: { lMax: 2, water: 2 }, highlight: [4], opCount: 6 },
            { id: 7, narration: "h[L]=0 < h[R]=2. +min(2,2)-0=2. water=4.", pointers: { L: 6, R: 10 }, variables: { water: 4 }, highlight: [5], opCount: 7 },
            { id: 8, narration: "h[L]=1 < h[R]=2. +min(2,2)-1=1. water=5.", pointers: { L: 7, R: 10 }, variables: { water: 5 }, highlight: [6], opCount: 8 },
            { id: 9, narration: "h[L]=3 > h[R]=2 → move R. Process remaining R until L>R.", pointers: { L: 7, R: 9 }, variables: { rMax: 2 }, opCount: 9 },
            { id: 10, narration: "Final total water = 6.", variables: { water: 6, answer: 6 }, opCount: 10, done: true },
          ],
        },
        {
          id: "prefix-max",
          name: "Precompute Max L/R",
          time: "O(n)",
          space: "O(n)",
          opsEstimate: (n) => n,
          defaultInput: { array: [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1] },
          steps: [
            { id: 0, narration: "Build leftMax[i] = max(height[0..i]).", variables: { leftMax: "[0,1,1,2,2,2,2,3,3,3,3,3]" }, opCount: 0 },
            { id: 1, narration: "Build rightMax[i] = max(height[i..n-1]).", variables: { rightMax: "[3,3,3,3,3,3,3,3,2,2,2,1]" }, opCount: 1 },
            { id: 2, narration: "water += min(L[i],R[i]) - height[i] for every i.", variables: { water: 6 }, opCount: 2, done: true },
          ],
        },
      ],
    },
  ],
};